import {
  faShieldHalved,
  faShieldHeart,
  faCrosshairs,
  faUserNinja,
  faCross,
  faBolt,
  faHatWizard,
  faSkull,
  faPaw,
  faFlask,
  faBreadSlice,
  faVial,
  faHammer,
  faDice,
} from "@fortawesome/free-solid-svg-icons";
import type { BiSClassTaxonomy, BiSGearEntry, BiSSpecData } from "../types";
import retributionPaladinTalents from "../assets/BiS Talents/Paladin - Retribution.png";
import { PALADIN_BIS_SPECS } from "./bisPaladin";
import { DRUID_BIS_SPECS } from "./bisDruid";
import { HUNTER_BIS_SPECS } from "./bisHunter";
import { MAGE_BIS_SPECS } from "./bisMage";
import { PRIEST_BIS_SPECS } from "./bisPriest";
import { ROGUE_BIS_SPECS } from "./bisRogue";
import { SHAMAN_BIS_SPECS } from "./bisShaman";
import { WARLOCK_BIS_SPECS } from "./bisWarlock";
import { WARRIOR_BIS_SPECS } from "./bisWarrior";

export const BIS_CLASSES: BiSClassTaxonomy[] = [
  {
    slug: "warrior",
    name: "Warrior",
    icon: faShieldHalved,
    specs: [
      { slug: "arms", name: "Arms", hasData: false },
      { slug: "fury", name: "Fury", hasData: true },
      { slug: "protection", name: "Protection", hasData: true },
    ],
  },
  {
    slug: "paladin",
    name: "Paladin",
    icon: faShieldHeart,
    specs: [
      { slug: "holy", name: "Holy", hasData: true },
      { slug: "protection", name: "Protection", hasData: false },
      { slug: "retribution", name: "Retribution", hasData: true },
    ],
  },
  {
    slug: "hunter",
    name: "Hunter",
    icon: faCrosshairs,
    specs: [
      { slug: "beast-mastery", name: "Beast Mastery", hasData: false },
      { slug: "marksmanship", name: "Marksmanship", hasData: true },
      { slug: "survival", name: "Survival", hasData: false },
    ],
  },
  {
    slug: "rogue",
    name: "Rogue",
    icon: faUserNinja,
    specs: [
      { slug: "assassination", name: "Assassination", hasData: false },
      { slug: "combat", name: "Combat", hasData: true },
      { slug: "subtlety", name: "Subtlety", hasData: false },
    ],
  },
  {
    slug: "priest",
    name: "Priest",
    icon: faCross,
    specs: [
      { slug: "discipline", name: "Discipline", hasData: false },
      { slug: "holy", name: "Holy", hasData: true },
      { slug: "shadow", name: "Shadow", hasData: true },
    ],
  },
  {
    slug: "shaman",
    name: "Shaman",
    icon: faBolt,
    specs: [
      { slug: "elemental", name: "Elemental", hasData: true },
      { slug: "enhancement", name: "Enhancement", hasData: true },
      { slug: "restoration", name: "Restoration", hasData: true },
    ],
  },
  {
    slug: "mage",
    name: "Mage",
    icon: faHatWizard,
    specs: [
      { slug: "arcane", name: "Arcane", hasData: true },
      { slug: "fire", name: "Fire", hasData: true },
      { slug: "frost", name: "Frost", hasData: true },
    ],
  },
  {
    slug: "warlock",
    name: "Warlock",
    icon: faSkull,
    specs: [
      { slug: "affliction", name: "Affliction", hasData: true },
      { slug: "demonology", name: "Demonology", hasData: false },
      { slug: "destruction", name: "Destruction", hasData: true },
    ],
  },
  {
    slug: "druid",
    name: "Druid",
    icon: faPaw,
    specs: [
      { slug: "balance", name: "Balance", hasData: true },
      { slug: "feral-dps", name: "Feral DPS", hasData: true },
      { slug: "feral-tank", name: "Feral Tank", hasData: true },
      { slug: "restoration", name: "Restoration", hasData: true },
    ],
  },
];

const PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Eye of Rend",
    entry: 12587,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Warchief Rend Blackhand (20%)",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer (12%)",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare (15%)",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish (15%)",
  },
  {
    slot: "Wrist",
    item: "Vambraces of the Sadist",
    entry: 13400,
    enchant: "Bracer - Superior Strength",
    source: "Stratholme (Live)",
    detail: "Timmy the Cruel (20%)",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Strength",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Omokk's Girth Restrainer",
    entry: 13959,
    enchant: null,
    source: "Quest Reward",
    detail: "Warlord's Command (H)",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Bloodmail Boots",
    entry: 14616,
    enchant: "Boots - Greater Agility",
    source: "Scholomance",
    detail: "Multiple Bosses (4%)",
  },
  {
    slot: "Ring 1",
    item: "Painweaver Band",
    entry: 13098,
    enchant: null,
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath (23%)",
  },
  {
    slot: "Ring 2",
    item: "Blackstone Ring",
    entry: 17713,
    enchant: null,
    source: "Maraudon",
    detail: "Princess Theradras (25%)",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan (15%)",
  },
  {
    slot: "Weapon",
    item: "Arcanite Reaper",
    entry: 12784,
    enchant: "Weapon - Crusader",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
];

const PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crown of Destruction",
    entry: 18817,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros (11%)",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer (12%)",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare (15%)",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish (15%)",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah (4%)",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Strength",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros (12%)",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Savage Gladiator Greaves",
    entry: 11731,
    enchant: "Boots - Greater Agility",
    source: "Blackrock Depths",
    detail: "Anub'shiah (11%)",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg (5%)",
  },
  {
    slot: "Ring 2",
    item: "Painweaver Band",
    entry: 13098,
    enchant: null,
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath (23%)",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan (15%)",
  },
  {
    slot: "Weapon",
    item: "Sulfuras, Hand of Ragnaros",
    entry: 17182,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Crafted",
  },
];

const PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crown of Destruction",
    entry: 18817,
    enchant: "Arcanum of Rapidity",
    source: "Molten Core",
    detail: "Ragnaros (11%)",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer (12%)",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare (15%)",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish (15%)",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah (4%)",
  },
  {
    slot: "Hands",
    item: "Flameguard Gauntlets",
    entry: 19143,
    enchant: "Gloves - Greater Strength",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg (5%)",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros (12%)",
  },
  {
    slot: "Legs",
    item: "Eldritch Reinforced Legplates",
    entry: 18380,
    enchant: "Arcanum of Rapidity",
    source: "Dire Maul (West)",
    detail: "Prince Tortheldrin (23%)",
  },
  {
    slot: "Feet",
    item: "Bloodmail Boots",
    entry: 14616,
    enchant: "Boots - Greater Agility",
    source: "Scholomance",
    detail: "Multiple Bosses (4%)",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg (5%)",
  },
  {
    slot: "Ring 2",
    item: "Don Julio's Band",
    entry: 19325,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan (15%)",
  },
  {
    slot: "Weapon",
    item: "Sulfuras, Hand of Ragnaros",
    entry: 17182,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Crafted",
  },
];

const PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Helm of Endless Rage",
    entry: 19372,
    enchant: "Arcanum of Rapidity",
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Drake Talon Pauldrons",
    entry: 19394,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Back",
    item: "Cloak of Draconic Might",
    entry: 19436,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish (15%)",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah (4%)",
  },
  {
    slot: "Hands",
    item: "Flameguard Gauntlets",
    entry: 19143,
    enchant: "Gloves - Greater Strength",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg (5%)",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros (12%)",
  },
  {
    slot: "Legs",
    item: "Legguards of the Fallen Crusader",
    entry: 19402,
    enchant: "Arcanum of Rapidity",
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Feet",
    item: "Chromatic Boots",
    entry: 19387,
    enchant: "Boots - Greater Agility",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg (5%)",
  },
  {
    slot: "Ring 2",
    item: "Circle of Applied Force",
    entry: 19432,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Flamegor",
  },
  {
    slot: "Trinket 1",
    item: "Scrolls of Blinding Light",
    entry: 19343,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan (15%)",
  },
  {
    slot: "Weapon",
    item: "Sulfuras, Hand of Ragnaros",
    entry: 17182,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Crafted",
  },
];

// Phase 4 (Zul'Gurub) only changes the shoulder enchant vs. Phase 3 — everything
// else carries over unchanged per the BiS guide.
const PHASE_4_GEAR: BiSGearEntry[] = PHASE_3_GEAR.map((entry) =>
  entry.slot === "Shoulder" ? { ...entry, enchant: "Zandalar Signet of Might" } : entry,
);

const PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Avenger's Crown",
    entry: 21387,
    enchant: "Arcanum of Rapidity",
    source: "Quest Reward",
    detail: "Avenger's Crown quest chain",
  },
  {
    slot: "Neck",
    item: "Barbed Choker",
    entry: 21664,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Shoulder",
    item: "Avenger's Pauldrons",
    entry: 21391,
    enchant: "Zandalar Signet of Might",
    source: "Quest Reward",
    detail: "Avenger's Pauldrons quest chain",
  },
  {
    slot: "Back",
    item: "Cloak of Concentrated Hatred",
    entry: 21701,
    enchant: "Cloak - Lesser Agility",
    source: "Ahn'Qiraj",
    detail: "The Prophet Skeram",
  },
  {
    slot: "Chest",
    item: "Avenger's Breastplate",
    entry: 21389,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Avenger's Breastplate quest chain",
  },
  {
    slot: "Wrist",
    item: "Hive Defiler Wristguards",
    entry: 21618,
    enchant: "Bracer - Superior Strength",
    source: "Ahn'Qiraj",
    detail: "Princess Huhuran",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Annihilation",
    entry: 21581,
    enchant: "Gloves - Superior Agility",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros (12%)",
  },
  {
    slot: "Legs",
    item: "Avenger's Legguards",
    entry: 21390,
    enchant: "Arcanum of Rapidity",
    source: "Quest Reward",
    detail: "Avenger's Legguards quest chain",
  },
  {
    slot: "Feet",
    item: "Avenger's Greaves",
    entry: 21388,
    enchant: "Boots - Greater Agility",
    source: "Quest Reward",
    detail: "Avenger's Greaves quest chain",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg (5%)",
  },
  {
    slot: "Ring 2",
    item: "Ring of the Qiraji Fury",
    entry: 21677,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Trinket 1",
    item: "Scrolls of Blinding Light",
    entry: 19343,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan (15%)",
  },
  {
    slot: "Weapon",
    item: "Sulfuras, Hand of Ragnaros",
    entry: 17182,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Crafted",
  },
  {
    slot: "Relic",
    item: "Libram of Fervor",
    entry: 23203,
    enchant: null,
    source: "Auction House",
    detail: "World Drop",
  },
];

const PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Avenger's Crown",
    entry: 21387,
    enchant: "Arcanum of Rapidity",
    source: "Quest Reward",
    detail: "Avenger's Crown quest chain",
  },
  {
    slot: "Neck",
    item: "Stormrage's Talisman of Seething",
    entry: 23053,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Avenger's Pauldrons",
    entry: 21391,
    enchant: "Might of the Scourge",
    source: "Quest Reward",
    detail: "Avenger's Pauldrons quest chain",
  },
  {
    slot: "Back",
    item: "Shroud of Dominion",
    entry: 23045,
    enchant: "Cloak - Lesser Agility",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Chest",
    item: "Avenger's Breastplate",
    entry: 21389,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Avenger's Breastplate quest chain",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Vengeance",
    entry: 22936,
    enchant: "Bracer - Superior Strength",
    source: "Naxxramas",
    detail: "Anub'Rekhan",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Annihilation",
    entry: 21581,
    enchant: "Gloves - Superior Agility",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Girdle of the Mentor",
    entry: 23219,
    enchant: null,
    source: "Naxxramas",
    detail: "Instructor Razuvious",
  },
  {
    slot: "Legs",
    item: "Avenger's Legguards",
    entry: 21390,
    enchant: "Arcanum of Rapidity",
    source: "Quest Reward",
    detail: "Avenger's Legguards quest chain",
  },
  {
    slot: "Feet",
    item: "Avenger's Greaves",
    entry: 21388,
    enchant: "Boots - Greater Agility",
    source: "Quest Reward",
    detail: "Avenger's Greaves quest chain",
  },
  {
    slot: "Ring 1",
    item: "Band of Unnatural Forces",
    entry: 23038,
    enchant: null,
    source: "Naxxramas",
    detail: "Loatheb",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg (5%)",
  },
  {
    slot: "Trinket 1",
    item: "Scrolls of Blinding Light",
    entry: 19343,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Trinket 2",
    item: "Kiss of the Spider",
    entry: 22954,
    enchant: null,
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Weapon",
    item: "Might of Menethil",
    entry: 22798,
    enchant: "Weapon - Crusader",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Relic",
    item: "Libram of Fervor",
    entry: 23203,
    enchant: null,
    source: "Auction House",
    detail: "World Drop",
  },
];

export const RETRIBUTION_PALADIN_BIS: BiSSpecData = {
  classSlug: "paladin",
  specSlug: "retribution",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: PHASE_6_GEAR },
  ],
  talentImage: retributionPaladinTalents,
  classGuide: {
    introduction:
      "Paladins bring major raid utility through their Blessings. Retribution isn't a top damage spec, but the utility it brings more than makes up for it.",
    rotationNote:
      "Mana management matters a lot for Retribution Paladins — downrank Consecration or Seal of Command when mana gets tight.",
    singleTarget: [
      "Keep Sanctity Aura up.",
      "Maintain the Seal of the Crusader Judgement debuff — Auto Attack keeps refreshing it.",
      "Maintain Seal of Command.",
      "Use Judgement.",
      "Use Consecration when Vengeance procs.",
      "Use Hammer of Wrath once the target drops below 20% health.",
      "Use Exorcism against Undead or Demon targets.",
      "Use Consecration if there's mana to spare.",
    ],
    aoe: [
      "Use Consecration.",
      "Use Holy Wrath against Undead or Demon packs.",
      "Otherwise, follow the single-target rotation.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Elixir of the Mongoose",
      alternatives: "Elixir of Greater Agility, Greater Arcane Elixir",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Blessed Sunfruit, Smoked Desert Dumplings",
      note: "Smoked Desert Dumplings only become available from Phase 5 onward.",
    },
    { category: "Potions", slug: "potions", icon: faVial, best: "Major Mana Potion" },
    { category: "Weapon Buffs", slug: "weaponBuffs", icon: faHammer, best: "Elemental Sharpening Stone" },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Juju Might, Juju Power, Ground Scorpok Assay, R.O.I.D.S., Cerebral Cortex Compound",
    },
  ],
};

const BIS_SPEC_DATA: BiSSpecData[] = [
  RETRIBUTION_PALADIN_BIS,
  ...PALADIN_BIS_SPECS,
  ...DRUID_BIS_SPECS,
  ...HUNTER_BIS_SPECS,
  ...MAGE_BIS_SPECS,
  ...PRIEST_BIS_SPECS,
  ...ROGUE_BIS_SPECS,
  ...SHAMAN_BIS_SPECS,
  ...WARLOCK_BIS_SPECS,
  ...WARRIOR_BIS_SPECS,
];

export function getBiSSpecData(classSlug: string, specSlug: string): BiSSpecData | undefined {
  return BIS_SPEC_DATA.find((d) => d.classSlug === classSlug && d.specSlug === specSlug);
}
