import {
  faFlask,
  faBreadSlice,
  faVial,
  faHammer,
  faDice,
} from "@fortawesome/free-solid-svg-icons";
import type { BiSGearEntry, BiSSpecData } from "../types";
import balanceDruidTalents from "../assets/BiS Talents/Druid - Balance.png";
import feralDpsDruidTalents from "../assets/BiS Talents/Druid - Feral DPS.png";
import feralTankDruidTalents from "../assets/BiS Talents/Druid - Feral Tank.png";
import restorationDruidTalents from "../assets/BiS Talents/Druid - Restoration.png";

const BALANCE_DRUID_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Diana's Pearl Necklace",
    entry: 22403,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Cannon Master Willey",
  },
  {
    slot: "Shoulder",
    item: "Burial Shawl",
    entry: 18681,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Scholomance",
    detail: "Lord Alexei Barov",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Robes of the Royal Crown",
    entry: 11924,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Wrist",
    item: "Manacle Cuffs",
    entry: 11962,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "The Love Potion",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Ban'thok Sash",
    entry: 11662,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Omnicast Boots",
    entry: 11822,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Ring 1",
    item: "Eye of Orgrimmar",
    entry: 12545,
    enchant: null,
    source: "Quest Reward",
    detail: "The Princess Saved?",
  },
  {
    slot: "Ring 2",
    item: "Cyclopean Band",
    entry: 11824,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Trinket 1",
    item: "Eye of the Beast",
    entry: 13968,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Witchblade",
    entry: 13964,
    enchant: "Weapon - Spell Power",
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
];

const BALANCE_DRUID_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Burial Shawl",
    entry: 18681,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Scholomance",
    detail: "Lord Alexei Barov",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Cenarion Bracers",
    entry: 16830,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Omnicast Boots",
    entry: 11822,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Staff of Dominance",
    entry: 18842,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
];

const BALANCE_DRUID_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Arcanum of Focus",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Burial Shawl",
    entry: 18681,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Scholomance",
    detail: "Lord Alexei Barov",
  },
  {
    slot: "Back",
    item: "Amplifying Cloak",
    entry: 18350,
    enchant: "Cloak - Greater Resistance",
    source: "Dire Maul (West)",
    detail: "Magister Kalendris",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Sublime Wristguards",
    entry: 18497,
    enchant: "Bracer - Greater Intellect",
    source: "Dire Maul (North)",
    detail: "Guard Mol'dar, Guard Slip'kik",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Arcanum of Focus",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Waterspout Boots",
    entry: 18322,
    enchant: "Boots - Minor Speed",
    source: "Dire Maul (East)",
    detail: "Hydrospawn",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Aurastone Hammer",
    entry: 17105,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Tome of Arcane Domination",
    entry: 19308,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const BALANCE_DRUID_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Brood Lord",
    entry: 19378,
    enchant: "Cloak - Greater Resistance",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Flarecore Leggings",
    entry: 19165,
    enchant: "Arcanum of Focus",
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Feet",
    item: "Waterspout Boots",
    entry: 18322,
    enchant: "Boots - Minor Speed",
    source: "Dire Maul (East)",
    detail: "Hydrospawn",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Tome of Arcane Domination",
    entry: 19308,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const BALANCE_DRUID_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of Consumption",
    entry: 19857,
    enchant: "Cloak - Greater Resistance",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Bloodtinged Gloves",
    entry: 19929,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Jin'do the Hexxer",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Arcanum of Focus",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Jin'do's Bag of Whammies",
    entry: 19891,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Jin'do the Hexxer",
  },
];

const BALANCE_DRUID_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Amulet of Vek'nilash",
    entry: 21608,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Devoured",
    entry: 22731,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Arcanum of Focus",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Royal Scepter of Vek'lor",
    entry: 21597,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Relic",
    item: "Idol of the Moon",
    entry: 23197,
    enchant: null,
    source: "Auction House",
    detail: "BoE World Drop",
  },
];

const BALANCE_DRUID_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Gem of Trapped Innocents",
    entry: 23057,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Rime Covered Mantle",
    entry: 22983,
    enchant: "Power of the Scourge",
    source: "Naxxramas",
    detail: "Gluth",
  },
  {
    slot: "Back",
    item: "Cloak of the Necropolis",
    entry: 23050,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Arcanum of Focus",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Band of the Inevitable",
    entry: 23031,
    enchant: null,
    source: "Naxxramas",
    detail: "Noth the Plaguebringer",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "The Restrained Essence of Sapphiron",
    entry: 23046,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Weapon",
    item: "Brimstone Staff",
    entry: 22800,
    enchant: "Weapon - Spell Power",
    source: "Naxxramas",
    detail: "Loatheb",
  },
  {
    slot: "Relic",
    item: "Idol of the Moon",
    entry: 23197,
    enchant: null,
    source: "Auction House",
    detail: "BoE World Drop",
  },
];

export const BALANCE_DRUID_BIS: BiSSpecData = {
  classSlug: "druid",
  specSlug: "balance",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: BALANCE_DRUID_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: BALANCE_DRUID_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: BALANCE_DRUID_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: BALANCE_DRUID_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: BALANCE_DRUID_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: BALANCE_DRUID_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: BALANCE_DRUID_PHASE_6_GEAR },
  ],
  talentImage: balanceDruidTalents,
  classGuide: {
    introduction: "Although Balance Druids don't deal large amounts of damage, they bring great utility with their aura provided by Moonkin Form, as well as spells such as Innervate and Rebirth.",
    singleTarget: [
      "Maintain Moonfire.",
      "Cast Starfire.",
      "Cast Wrath if the target will die before your next Starfire cast finishes.",
    ],
    aoe: [
      "For 1 additional target:",
      "Maintain Moonfire on both targets.",
      "Cast Starfire.",
      "For large pulls:",
      "Cast Moonfire on up to 3 targets.",
      "Cast Hurricane. (Make sure to also use Barkskin if there is a chance you will get interrupted).",
      "Cast Starfire.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Flask of Supreme Power",
      alternatives: "Greater Arcane Elixir",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Wizard Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

const FERAL_DPS_DRUID_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Wolfshead Helm",
    entry: 8345,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "Trainer (225)",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Cadaverous Armor",
    entry: 14637,
    enchant: "Chest - Greater Stats",
    source: "Scholomance",
    detail: "Lord Alex Barov",
  },
  {
    slot: "Wrist",
    item: "Blackmist Armguards",
    entry: 12966,
    enchant: "Bracer - Superior Strength",
    source: "Blackrock Spire (Upper)",
    detail: "The Beast",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Agility",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Cloudrunner Girdle",
    entry: 13252,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Swiftwalker Boots",
    entry: 12553,
    enchant: "Boots - Greater Agility",
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Ring 1",
    item: "Blackstone Ring",
    entry: 17713,
    enchant: null,
    source: "Maraudon",
    detail: "Princess Theradras",
  },
  {
    slot: "Ring 2",
    item: "Magma Forged Band",
    entry: 22255,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Secret Safe",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
];

const FERAL_DPS_DRUID_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Wolfshead Helm",
    entry: 8345,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "Trainer (225)",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Cloak of the Shrouded Mists",
    entry: 17102,
    enchant: "Cloak - Lesser Agility",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Chest",
    item: "Cadaverous Armor",
    entry: 14637,
    enchant: "Chest - Greater Stats",
    source: "Scholomance",
    detail: "Lord Alex Barov",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Agility",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Cloudrunner Girdle",
    entry: 13252,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Swiftwalker Boots",
    entry: 12553,
    enchant: "Boots - Greater Agility",
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Ring 1",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
];

const FERAL_DPS_DRUID_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Wolfshead Helm",
    entry: 8345,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "Trainer (225)",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Cloak of the Shrouded Mists",
    entry: 17102,
    enchant: "Cloak - Lesser Agility",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Chest",
    item: "Cadaverous Armor",
    entry: 14637,
    enchant: "Chest - Greater Stats",
    source: "Scholomance",
    detail: "Lord Alex Barov",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Agility",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Cloudrunner Girdle",
    entry: 13252,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Swiftwalker Boots",
    entry: 12553,
    enchant: "Boots - Greater Agility",
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Ring 1",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 2",
    item: "Don Julio's Band",
    entry: 19325,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
];

const FERAL_DPS_DRUID_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Wolfshead Helm",
    entry: 8345,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "Trainer (225)",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Wyrmtongue Shoulders",
    entry: 13358,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Stratholme (Live)",
    detail: "Balnazzar",
  },
  {
    slot: "Back",
    item: "Cloak of Draconic Might",
    entry: 19436,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Chest",
    item: "Malfurion's Blessed Bulwark",
    entry: 19405,
    enchant: "Chest - Greater Stats",
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Agility",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Molten Belt",
    entry: 19163,
    enchant: null,
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Boots of the Shadow Flame",
    entry: 19381,
    enchant: "Boots - Greater Agility",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 1",
    item: "Circle of Applied Force",
    entry: 19432,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Flamegor",
  },
  {
    slot: "Ring 2",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
];

const FERAL_DPS_DRUID_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Wolfshead Helm",
    entry: 8345,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "Trainer (225)",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Wyrmtongue Shoulders",
    entry: 13358,
    enchant: "Zandalar Signet of Might",
    source: "Stratholme (Live)",
    detail: "Balnazzar",
  },
  {
    slot: "Back",
    item: "Cloak of Draconic Might",
    entry: 19436,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Chest",
    item: "Malfurion's Blessed Bulwark",
    entry: 19405,
    enchant: "Chest - Greater Stats",
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Agility",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Belt of Preserved Heads",
    entry: 20216,
    enchant: null,
    source: "Quest Reward",
    detail: "A Collection of Heads",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Boots of the Shadow Flame",
    entry: 19381,
    enchant: "Boots - Greater Agility",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 1",
    item: "Circle of Applied Force",
    entry: 19432,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Flamegor",
  },
  {
    slot: "Ring 2",
    item: "Don Julio's Band",
    entry: 19325,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
];

const FERAL_DPS_DRUID_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Wolfshead Helm",
    entry: 8345,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "Trainer (225)",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Mantle of Wicked Revenge",
    entry: 21665,
    enchant: "Zandalar Signet of Might",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Vest of Swift Execution",
    entry: 21680,
    enchant: "Chest - Greater Stats",
    source: "Ahn'Qiraj",
    detail: "Lord Kri",
  },
  {
    slot: "Wrist",
    item: "Qiraji Execution Bracers",
    entry: 21602,
    enchant: "Bracer - Superior Strength",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Hands",
    item: "Gloves of Enforcement",
    entry: 21672,
    enchant: "Gloves - Superior Agility",
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Waist",
    item: "Belt of Never-ending Agony",
    entry: 21586,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Genesis Trousers",
    entry: 21356,
    enchant: "Lesser Arcanum of Voracity",
    source: "Quest Reward",
    detail: "Genesis Trousers",
  },
  {
    slot: "Feet",
    item: "Boots of the Vanguard",
    entry: 21493,
    enchant: "Boots - Greater Agility",
    source: "Ruins of Ahn'Qiraj",
    detail: "General Rajaxx",
  },
  {
    slot: "Ring 1",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 2",
    item: "Signet Ring of the Bronze Dragonflight-v2",
    entry: 21200,
    enchant: null,
    source: "Quest Reward",
    detail: "The Qiraji Conqueror",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Jom Gabbar",
    entry: 23570,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Ouro",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
  {
    slot: "Relic",
    item: "Idol of Ferocity",
    entry: 22397,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Lord Roccor",
  },
];

const FERAL_DPS_DRUID_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Wolfshead Helm",
    entry: 8345,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "Trainer (225)",
  },
  {
    slot: "Shoulder",
    item: "Mantle of Wicked Revenge",
    entry: 21665,
    enchant: "Might of the Scourge",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Back",
    item: "Cloak of Concentrated Hatred",
    entry: 21701,
    enchant: "Cloak - Lesser Agility",
    source: "Ahn'Qiraj",
    detail: "The Prophet Skeram",
  },
  {
    slot: "Chest",
    item: "Vest of Swift Execution",
    entry: 21680,
    enchant: "Chest - Greater Stats",
    source: "Ahn'Qiraj",
    detail: "Lord Kri",
  },
  {
    slot: "Wrist",
    item: "Qiraji Execution Bracers",
    entry: 21602,
    enchant: "Bracer - Superior Strength",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Hands",
    item: "Gloves of Enforcement",
    entry: 21672,
    enchant: "Gloves - Superior Agility",
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Waist",
    item: "Belt of Never-ending Agony",
    entry: 21586,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of Apocalypse",
    entry: 23071,
    enchant: "Lesser Arcanum of Voracity",
    source: "Naxxramas",
    detail: "The Four Horsemen",
  },
  {
    slot: "Feet",
    item: "Boots of the Vanguard",
    entry: 21493,
    enchant: "Boots - Greater Agility",
    source: "Ruins of Ahn'Qiraj",
    detail: "General Rajaxx",
  },
  {
    slot: "Ring 1",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 2",
    item: "Band of Unnatural Forces",
    entry: 23038,
    enchant: null,
    source: "Naxxramas",
    detail: "Loatheb",
  },
  {
    slot: "Trinket 1",
    item: "Kiss of the Spider",
    entry: 22954,
    enchant: null,
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Champion-v2",
    enchant: null,
    source: "Quest Reward",
    detail: "The Fall of Kel'Thuzad",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
  {
    slot: "Relic",
    item: "Idol of Ferocity",
    entry: 22397,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Lord Roccor",
  },
];

export const FERAL_DPS_DRUID_BIS: BiSSpecData = {
  classSlug: "druid",
  specSlug: "feral-dps",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: FERAL_DPS_DRUID_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: FERAL_DPS_DRUID_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: FERAL_DPS_DRUID_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: FERAL_DPS_DRUID_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: FERAL_DPS_DRUID_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: FERAL_DPS_DRUID_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: FERAL_DPS_DRUID_PHASE_6_GEAR },
  ],
  talentImage: feralDpsDruidTalents,
  classGuide: {
    introduction: "Every raid will want at least one Feral Druid because of the utility provided by Leader of the Pack. Due to Power Shifting (details below), this spec has one of the more involved rotations of the expansion. They also have the added benefit of being able to tank content without needing to respec.",
    rotationNote: "Power Shifting correctly is critical for Feral Druids. Shifting into Cat Form will generate 60 energy because of Furor and Wolfshead Helm and you passively generate 20 energy every 2 seconds regardless of what form you are in.",
    singleTarget: [
      "Maintain Faerie Fire (Feral) if assigned to it.",
      "Use Shred with Omen of Clarity proc.",
      "Use Shred.",
      "Use Ferocious Bite.",
      "If your next Energy tick (20 Energy) won't give you enough Energy to perform your next priority ability, then Power Shift, otherwise stay in Cat Form.",
    ],
    aoe: [
      "For large groups (5+ mobs), it's worth casting Hurricane. For anything less you will perform your single target rotation.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Elixir of the Mongoose",
      alternatives: "Elixir of Greater Agility",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Grilled Squid",
      note: "undefined",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Juju Might, Juju Power, Ground Scorpok Assay, R.O.I.D.S.",
    },
  ],
};

const FERAL_TANK_DRUID_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mask of the Unforgiven",
    entry: 13404,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Live)",
    detail: "The Unforgiven",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Phantasmal Cloak",
    entry: 18689,
    enchant: "Cloak - Lesser Agility",
    source: "Scholomance",
    detail: "Jandice Barov",
  },
  {
    slot: "Chest",
    item: "Breastplate of Bloodthirst",
    entry: 12757,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Breastplate of Bloodthirst",
  },
  {
    slot: "Wrist",
    item: "Blackmist Armguards",
    entry: 12966,
    enchant: "Bracer - Superior Strength",
    source: "Blackrock Spire (Upper)",
    detail: "The Beast",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Minor Haste",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Cloudrunner Girdle",
    entry: 13252,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Pads of the Dread Wolf",
    entry: 13210,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Spire (Lower)",
    detail: "Halycon",
  },
  {
    slot: "Ring 1",
    item: "Thrall's Resolve",
    entry: 12544,
    enchant: null,
    source: "Quest Reward",
    detail: "The Princess Saved? (H)",
  },
  {
    slot: "Ring 2",
    item: "Blackstone Ring",
    entry: 17713,
    enchant: null,
    source: "Maraudon",
    detail: "Princess Theradras",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Chosen",
    entry: 17774,
    enchant: null,
    source: "Quest Reward",
    detail: "The Pariah's Instructions",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
];

const FERAL_TANK_DRUID_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mask of the Unforgiven",
    entry: 13404,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Live)",
    detail: "The Unforgiven",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Dragon's Blood Cape",
    entry: 17107,
    enchant: "Cloak - Lesser Agility",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Chest",
    item: "Breastplate of Bloodthirst",
    entry: 12757,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Breastplate of Bloodthirst",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Minor Haste",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Cloudrunner Girdle",
    entry: 13252,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Pads of the Dread Wolf",
    entry: 13210,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Spire (Lower)",
    detail: "Halycon",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Chosen",
    entry: 17774,
    enchant: null,
    source: "Quest Reward",
    detail: "The Pariah's Instructions",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
];

const FERAL_TANK_DRUID_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mask of the Unforgiven",
    entry: 13404,
    enchant: "Arcanum of Rapidity",
    source: "Stratholme (Live)",
    detail: "The Unforgiven",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Dragon's Blood Cape",
    entry: 17107,
    enchant: "Cloak - Lesser Agility",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Chest",
    item: "Breastplate of Bloodthirst",
    entry: 12757,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Breastplate of Bloodthirst",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Minor Haste",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Cloudrunner Girdle",
    entry: 13252,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Arcanum of Rapidity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Pads of the Dread Wolf",
    entry: 13210,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Spire (Lower)",
    detail: "Halycon",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Chosen",
    entry: 17774,
    enchant: null,
    source: "Quest Reward",
    detail: "The Pariah's Instructions",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
];

const FERAL_TANK_DRUID_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mask of the Unforgiven",
    entry: 13404,
    enchant: "Arcanum of Rapidity",
    source: "Stratholme (Live)",
    detail: "The Unforgiven",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Taut Dragonhide Shoulderpads",
    entry: 19389,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Back",
    item: "Dragon's Blood Cape",
    entry: 17107,
    enchant: "Cloak - Lesser Agility",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Chest",
    item: "Malfurion's Blessed Bulwark",
    entry: 19405,
    enchant: "Chest - Greater Stats",
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Minor Haste",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Taut Dragonhide Belt",
    entry: 19396,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Arcanum of Rapidity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Boots of the Shadow Flame",
    entry: 19381,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Circle of Applied Force",
    entry: 19432,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Flamegor",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
];

const FERAL_TANK_DRUID_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lizardscale Eyepatch",
    enchant: "Arcanum of Rapidity",
    source: "Zul'Gurub",
    detail: "Gahz'ranka",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Taut Dragonhide Shoulderpads",
    entry: 19389,
    enchant: "Zandalar Signet of Might",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Back",
    item: "Dragon's Blood Cape",
    entry: 17107,
    enchant: "Cloak - Lesser Agility",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Chest",
    item: "Malfurion's Blessed Bulwark",
    entry: 19405,
    enchant: "Chest - Greater Stats",
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Minor Haste",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Taut Dragonhide Belt",
    entry: 19396,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Arcanum of Rapidity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Boots of the Shadow Flame",
    entry: 19381,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
];

const FERAL_TANK_DRUID_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Guise of the Devourer",
    entry: 21693,
    enchant: "Arcanum of Rapidity",
    source: "Ahn'Qiraj",
    detail: "Bug Trio",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Mantle of Wicked Revenge",
    entry: 21665,
    enchant: "Zandalar Signet of Might",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Malfurion's Blessed Bulwark",
    entry: 19405,
    enchant: "Chest - Greater Stats",
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Wrist",
    item: "Qiraji Execution Bracers",
    entry: 21602,
    enchant: "Bracer - Superior Strength",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Hands",
    item: "Gloves of the Hidden Temple",
    entry: 21605,
    enchant: "Gloves - Threat",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Waist",
    item: "Belt of Never-ending Agony",
    entry: 21586,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Genesis Trousers",
    entry: 21356,
    enchant: "Arcanum of Rapidity",
    source: "Quest Reward",
    detail: "Genesis Trousers",
  },
  {
    slot: "Feet",
    item: "Boots of the Shadow Flame",
    entry: 19381,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 1",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Signet Ring of the Bronze Dragonflight-v2",
    entry: 21200,
    enchant: null,
    source: "Quest Reward",
    detail: "The Qiraji Conqueror",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Earthstrike",
    entry: 21180,
    enchant: null,
    source: "Quest Reward",
    detail: "Champion's Battlegear",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
  {
    slot: "Relic",
    item: "Idol of Brutality",
    entry: 23198,
    enchant: null,
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
];

const FERAL_TANK_DRUID_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Guise of the Devourer",
    entry: 21693,
    enchant: "Arcanum of Rapidity",
    source: "Ahn'Qiraj",
    detail: "Bug Trio",
  },
  {
    slot: "Neck",
    item: "Stormrage's Talisman of Seething",
    entry: 23053,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Mantle of Wicked Revenge",
    entry: 21665,
    enchant: "Might of the Scourge",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Ghoul Skin Tunic",
    entry: 23226,
    enchant: "Chest - Greater Stats",
    source: "Naxxramas",
    detail: "Trash Drop",
  },
  {
    slot: "Wrist",
    item: "Qiraji Execution Bracers",
    entry: 21602,
    enchant: "Bracer - Superior Strength",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Hands",
    item: "Gloves of the Hidden Temple",
    entry: 21605,
    enchant: "Gloves - Threat",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Waist",
    item: "Belt of Never-ending Agony",
    entry: 21586,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of Apocalypse",
    entry: 23071,
    enchant: "Arcanum of Rapidity",
    source: "Naxxramas",
    detail: "The Four Horsemen",
  },
  {
    slot: "Feet",
    item: "Boots of the Shadow Flame",
    entry: 19381,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 1",
    item: "Signet of the Fallen Defender",
    entry: 23018,
    enchant: null,
    source: "Naxxramas",
    detail: "Instructor Razuvious",
  },
  {
    slot: "Ring 2",
    item: "Signet Ring of the Bronze Dragonflight-v2",
    entry: 21200,
    enchant: null,
    source: "Quest Reward",
    detail: "The Qiraji Conqueror",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Kiss of the Spider",
    entry: 22954,
    enchant: null,
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Weapon",
    item: "Manual Crowd Pummeler",
    entry: 9449,
    enchant: "Iron Counterweight",
    source: "Gnomergan",
    detail: "Crowd Pummeler 9-60",
  },
  {
    slot: "Relic",
    item: "Idol of Brutality",
    entry: 23198,
    enchant: null,
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
];

export const FERAL_TANK_DRUID_BIS: BiSSpecData = {
  classSlug: "druid",
  specSlug: "feral-tank",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: FERAL_TANK_DRUID_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: FERAL_TANK_DRUID_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: FERAL_TANK_DRUID_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: FERAL_TANK_DRUID_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: FERAL_TANK_DRUID_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: FERAL_TANK_DRUID_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: FERAL_TANK_DRUID_PHASE_6_GEAR },
  ],
  talentImage: feralTankDruidTalents,
  classGuide: {
    introduction: "Every raid will want at least one Feral Druid because of the utility provided by Leader of the Pack. Feral Druids make great off tanks because they can switch to Cat Form when not needed.",
    singleTarget: [
      "Maintain Faerie Fire (Feral) if assigned to it.",
      "Maintain Demoralizing Roar if assigned to it. A Warrior should take this responsibility with their improved talents.",
      "Use Maul.",
      "Use Swipe.",
    ],
    aoe: [
      "Maintain Demoralizing Roar if assigned to it.",
      "Use Swipe.",
      "Use Maul if you have excess rage. Can use Hurricane to pull a large group of mobs and then quickly shift into Dire Bear Form.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Elixir of the Mongoose, Elixir of Superior Defense",
      alternatives: "Flask of the Titans, Elixir of Greater Agility",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Grilled Squid",
      note: "undefined",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Greater Stoneshield Potion",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Juju Might, Juju Power, Ground Scorpok Assay, R.O.I.D.S., Lung Juice Cocktail",
    },
  ],
};

const RESTORATION_DRUID_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Tribal War Feathers",
    entry: 12960,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Gyth",
  },
  {
    slot: "Neck",
    item: "Animated Chain Necklace",
    entry: 18723,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Ramstein the Gorger",
  },
  {
    slot: "Shoulder",
    item: "Living Shoulders",
    entry: 15061,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Leatherworking",
    detail: "BoE Pattern (270)",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Bleak Howler Armguards",
    entry: 13208,
    enchant: "Bracer - Superior Spirit",
    source: "Blackrock Spire (Lower)",
    detail: "Gizrul the Slavener",
  },
  {
    slot: "Hands",
    item: "Hands of the Exalted Herald",
    entry: 12554,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Waist",
    item: "Thuzadin Sash",
    entry: 18740,
    enchant: null,
    source: "Stratholme (Undead)",
    detail: "Nerub'enkan",
  },
  {
    slot: "Legs",
    item: "Senior Designer's Pantaloons",
    entry: 11841,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Depths",
    detail: "Fineous Darkvire",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Rosewine Circle",
    entry: 13178,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Urok Doomhowl",
  },
  {
    slot: "Ring 2",
    item: "Fordring's Seal",
    entry: 16058,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Trinket 1",
    item: "Second Wind",
    entry: 11819,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "The Hammer of Grace",
    entry: 11923,
    enchant: "Weapon - Healing Power",
    source: "Blackrock Depths",
    detail: "Chest of the Seven",
  },
  {
    slot: "Off Hand",
    item: "Thaurissan's Royal Scepter",
    entry: 11928,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
];

const RESTORATION_DRUID_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Stormrage Cover",
    entry: 16900,
    enchant: "Lesser Arcanum of Voracity",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Animated Chain Necklace",
    entry: 18723,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Ramstein the Gorger",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Bleak Howler Armguards",
    entry: 13208,
    enchant: "Bracer - Superior Spirit",
    source: "Blackrock Spire (Lower)",
    detail: "Gizrul the Slavener",
  },
  {
    slot: "Hands",
    item: "Hands of the Exalted Herald",
    entry: 12554,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Salamander Scale Pants",
    entry: 18875,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Second Wind",
    entry: 11819,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Aurastone Hammer",
    entry: 17105,
    enchant: "Weapon - Healing Power",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Thaurissan's Royal Scepter",
    entry: 11928,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
];

const RESTORATION_DRUID_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Stormrage Cover",
    entry: 16900,
    enchant: "Arcanum of Focus",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Animated Chain Necklace",
    entry: 18723,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Ramstein the Gorger",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Hide of the Wild",
    entry: 18510,
    enchant: "Cloak - Greater Resistance",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Bracers of Prosperity",
    entry: 18525,
    enchant: "Bracer - Superior Spirit",
    source: "Dire Maul (North)",
    detail: "King Gordok",
  },
  {
    slot: "Hands",
    item: "Hands of the Exalted Herald",
    entry: 12554,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Waist",
    item: "Eyestalk Cord",
    entry: 18391,
    enchant: null,
    source: "Dire Maul (West)",
    detail: "Immol'thar",
  },
  {
    slot: "Legs",
    item: "Salamander Scale Pants",
    entry: 18875,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Royal Seal of Eldre'Thalas (Druid)",
    entry: 18470,
    enchant: null,
    source: "Quest Reward",
    detail: "The Emerald Dream...",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Aurastone Hammer",
    entry: 17105,
    enchant: "Weapon - Healing Power",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Lei of the Lifegiver",
    entry: 19312,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const RESTORATION_DRUID_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Stormrage Cover",
    entry: 16900,
    enchant: "Arcanum of Focus",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Animated Chain Necklace",
    entry: 18723,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Ramstein the Gorger",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Hide of the Wild",
    entry: 18510,
    enchant: "Cloak - Greater Resistance",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Stormrage Bracers",
    entry: 16904,
    enchant: "Bracer - Healing Power",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Stormrage Handguards",
    entry: 16899,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Corehound Belt",
    entry: 19162,
    enchant: null,
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Royal Seal of Eldre'Thalas (Druid)",
    entry: 18470,
    enchant: null,
    source: "Quest Reward",
    detail: "The Emerald Dream...",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Healing Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Lei of the Lifegiver",
    entry: 19312,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const RESTORATION_DRUID_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Stormrage Cover",
    entry: 16900,
    enchant: "Animist's Caress",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Jin'do's Evil Eye",
    entry: 19885,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Jin'do the Hexxer",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Zandalar Signet of Serenity",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Hide of the Wild",
    entry: 18510,
    enchant: "Cloak - Greater Resistance",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Stormrage Bracers",
    entry: 16904,
    enchant: "Bracer - Healing Power",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Stormrage Handguards",
    entry: 16899,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Corehound Belt",
    entry: 19162,
    enchant: null,
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Animist's Caress",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Royal Seal of Eldre'Thalas (Druid)",
    entry: 18470,
    enchant: null,
    source: "Quest Reward",
    detail: "The Emerald Dream...",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Healing Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Lei of the Lifegiver",
    entry: 19312,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const RESTORATION_DRUID_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Don Rigoberto's Lost Hat",
    entry: 21615,
    enchant: "Animist's Caress",
    source: "Ahn'Qiraj",
    detail: "Ouro",
  },
  {
    slot: "Neck",
    item: "Amulet of the Fallen God",
    entry: 21712,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Zandalar Signet of Serenity",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Cloak of Clarity",
    entry: 21583,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Robes of the Guardian Saint",
    entry: 21663,
    enchant: "Chest - Greater Stats",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Wrist",
    item: "Bracelets of Royal Redemption",
    entry: 21604,
    enchant: "Bracer - Healing Power",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Hands",
    item: "Wasphide Gauntlets",
    entry: 21617,
    enchant: "Gloves - Healing Power",
    source: "Ahn'Qiraj",
    detail: "Princess Huhuran",
  },
  {
    slot: "Waist",
    item: "Corehound Belt",
    entry: 19162,
    enchant: null,
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Animist's Caress",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Ring of the Martyr",
    entry: 21620,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Princess Huhuran",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Royal Seal of Eldre'Thalas (Druid)",
    entry: 18470,
    enchant: null,
    source: "Quest Reward",
    detail: "The Emerald Dream...",
  },
  {
    slot: "Weapon",
    item: "Scepter of the False Prophet",
    entry: 21839,
    enchant: "Weapon - Healing Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Off Hand",
    item: "Lei of the Lifegiver",
    entry: 19312,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Relic",
    item: "Idol of Rejuvenation",
    entry: 22398,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Mor Grayhoof",
  },
];

const RESTORATION_DRUID_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Dreamwalker Headpiece",
    entry: 22490,
    enchant: "Animist's Caress",
    source: "Naxxramas",
    detail: "Dreamwalker Headpiece",
  },
  {
    slot: "Neck",
    item: "Amulet of the Fallen God",
    entry: 21712,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Zandalar Signet of Serenity",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Cloak of Suturing",
    entry: 22960,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Patchwerk",
  },
  {
    slot: "Chest",
    item: "Dreamwalker Tunic",
    entry: 22488,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Dreamwalker Tunic",
  },
  {
    slot: "Wrist",
    item: "Bracelets of Royal Redemption",
    entry: 21604,
    enchant: "Bracer - Healing Power",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Hands",
    item: "Dreamwalker Handguards",
    entry: 22493,
    enchant: "Gloves - Healing Power",
    source: "Quest Reward",
    detail: "Dreamwalker Handguards",
  },
  {
    slot: "Waist",
    item: "Dreamwalker Girdle",
    entry: 22494,
    enchant: null,
    source: "Quest Reward",
    detail: "Dreamwalker Girdle",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Animist's Caress",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Band of Unanswered Prayers",
    entry: 22939,
    enchant: null,
    source: "Naxxramas",
    detail: "Anub'Rekhan",
  },
  {
    slot: "Trinket 1",
    item: "Eye of the Dead",
    entry: 23047,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Trinket 2",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Weapon",
    item: "Hammer of the Twisting Nether",
    entry: 23056,
    enchant: "Weapon - Healing Power",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Off Hand",
    item: "Sapphiron's Right Eye",
    entry: 23048,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Relic",
    item: "Idol of Rejuvenation",
    entry: 22398,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Mor Grayhoof",
  },
];

export const RESTORATION_DRUID_BIS: BiSSpecData = {
  classSlug: "druid",
  specSlug: "restoration",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: RESTORATION_DRUID_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: RESTORATION_DRUID_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: RESTORATION_DRUID_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: RESTORATION_DRUID_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: RESTORATION_DRUID_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: RESTORATION_DRUID_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: RESTORATION_DRUID_PHASE_6_GEAR },
  ],
  talentImage: restorationDruidTalents,
  classGuide: {
    introduction: "Restoration Druids bring great utility to raids with Innervate and Rebirth and can react to spikes of large damage thanks to Nature's Swiftness and Swiftmend if specced for it.",
    rotationNote: "One of the unique things about healing is downranking heals. We mention some specific ranks of certain heals below as a starting point, but finding out which ranks work best will be up to you. The ranks you choose will change based on each boss depending on the situation and length of the encounter, as well your target and how much health they are missing.",
    singleTarget: [
      "Maintain Rejuvenation.",
      "Maintain Regrowth HoT.",
      "Cast Swiftmend for a solid instant burst heal.",
      "Cast Regrowth for larger heals, or Healing Touch R4 for smaller heals. Cast Nature's Swiftness with max rank Healing Touch for a huge instant burst heal.",
      "If you need to start conserving mana, you can start downranking and use spells such as Regrowth R4 or Regrowth R5, and Healing Touch R3.",
    ],
    aoe: [
      "Tranquility if most of your group is low on health and in range of being healing by it.",
      "Perform single target rotation.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Mageblood Potion (Phase 4)",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup, Sagefish Delight",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Mana Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

export const DRUID_BIS_SPECS: BiSSpecData[] = [BALANCE_DRUID_BIS, FERAL_DPS_DRUID_BIS, FERAL_TANK_DRUID_BIS, RESTORATION_DRUID_BIS];
