import {
  faFlask,
  faBreadSlice,
  faVial,
  faHammer,
  faDice,
} from "@fortawesome/free-solid-svg-icons";
import type { BiSGearEntry, BiSSpecData } from "../types";
import marksmanshipHunterTalents from "../assets/BiS Talents/Hunter - Marksmanship.png";

const MARKSMANSHIP_HUNTER_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mask of the Unforgiven",
    entry: 13404,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Live)",
    detail: "The Unforgiven",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Slashclaw Bracers",
    entry: 13211,
    enchant: "Bracer - Minor Agility",
    source: "Blackrock Spire (Lower)",
    detail: "Halycon",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Agility",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Chiselbrand Girdle",
    entry: 12634,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Bannok Grimaxe",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Windreaver Greaves",
    entry: 13967,
    enchant: "Boots - Greater Agility",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Ring 1",
    item: "Painweaver Band",
    entry: 13098,
    enchant: null,
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath",
  },
  {
    slot: "Ring 2",
    item: "Blackstone Ring",
    entry: 17713,
    enchant: null,
    source: "Maraudon",
    detail: "Princess Theradras",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Peacemaker",
    entry: 18725,
    enchant: null,
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Ranged",
    item: "Blackcrow",
    entry: 12651,
    enchant: "Sniper Scope",
    source: "Blackrock Spire (Lower)",
    detail: "Shadow Hunter Vosh'gajin",
  },
];

const MARKSMANSHIP_HUNTER_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Giantstalker's Helmet",
    entry: 16846,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Giantstalker's Epaulets",
    entry: 16848,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Sulfuron Harbinger",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Giantstalker's Breastplate",
    entry: 16845,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Wrist",
    item: "Giantstalker's Bracers",
    entry: 16850,
    enchant: "Bracer - Minor Agility",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Giantstalker's Gloves",
    entry: 16852,
    enchant: "Gloves - Greater Agility",
    source: "Molten Core",
    detail: "Shazzrah",
  },
  {
    slot: "Waist",
    item: "Giantstalker's Belt",
    entry: 16851,
    enchant: null,
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Legs",
    item: "Giantstalker's Leggings",
    entry: 16847,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Magmadar",
  },
  {
    slot: "Feet",
    item: "Giantstalker's Boots",
    entry: 16849,
    enchant: "Boots - Greater Agility",
    source: "Molten Core",
    detail: "Gehennas",
  },
  {
    slot: "Ring 1",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Brutality Blade",
    entry: 18832,
    enchant: null,
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Core Hound Tooth",
    entry: 18805,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ranged",
    item: "Rhok'delar, Longbow of the Ancient Keepers",
    entry: 18713,
    enchant: "Biznicks 247x128 Accurascope",
    source: "Quest Reward",
    detail: "Stave of the Ancients",
  },
];

const MARKSMANSHIP_HUNTER_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Giantstalker's Helmet",
    entry: 16846,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Giantstalker's Epaulets",
    entry: 16848,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Sulfuron Harbinger",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Giantstalker's Breastplate",
    entry: 16845,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Wrist",
    item: "Giantstalker's Bracers",
    entry: 16850,
    enchant: "Bracer - Minor Agility",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Giantstalker's Gloves",
    entry: 16852,
    enchant: "Gloves - Greater Agility",
    source: "Molten Core",
    detail: "Shazzrah",
  },
  {
    slot: "Waist",
    item: "Giantstalker's Belt",
    entry: 16851,
    enchant: null,
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Legs",
    item: "Giantstalker's Leggings",
    entry: 16847,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Magmadar",
  },
  {
    slot: "Feet",
    item: "Giantstalker's Boots",
    entry: 16849,
    enchant: "Boots - Greater Agility",
    source: "Molten Core",
    detail: "Gehennas",
  },
  {
    slot: "Ring 1",
    item: "Don Julio's Band",
    entry: 19325,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Ring 2",
    item: "Tarnished Elven Ring",
    entry: 18500,
    enchant: null,
    source: "Dire Maul (North)",
    detail: "Gordok Tribute",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Royal Seal of Eldre'Thalas (Hunter)",
    entry: 18473,
    enchant: null,
    source: "Quest Reward",
    detail: "The Greatest Race of Hunters",
  },
  {
    slot: "Weapon",
    item: "Brutality Blade",
    entry: 18832,
    enchant: null,
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Core Hound Tooth",
    entry: 18805,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ranged",
    item: "Rhok'delar, Longbow of the Ancient Keepers",
    entry: 18713,
    enchant: "Biznicks 247x128 Accurascope",
    source: "Quest Reward",
    detail: "Stave of the Ancients",
  },
];

const MARKSMANSHIP_HUNTER_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Dragonstalker's Helm",
    entry: 16939,
    enchant: "Lesser Arcanum of Voracity",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Dragonstalker's Spaulders",
    entry: 16937,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Dragonstalker's Breastplate",
    entry: 16942,
    enchant: "Chest - Greater Stats",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Wrist",
    item: "Dragonstalker's Bracers",
    entry: 16935,
    enchant: "Bracer - Minor Agility",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Dragonstalker's Gauntlets",
    entry: 16940,
    enchant: "Gloves - Greater Agility",
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Dragonstalker's Belt",
    entry: 16936,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Legs",
    item: "Dragonstalker's Legguards",
    entry: 16938,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Dragonstalker's Greaves",
    entry: 16941,
    enchant: "Boots - Greater Agility",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Ring 1",
    item: "Don Julio's Band",
    entry: 19325,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Brutality Blade",
    entry: 18832,
    enchant: "Weapon - Agility",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Core Hound Tooth",
    entry: 18805,
    enchant: "Weapon - Agility",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ranged",
    item: "Ashjre'thul, Crossbow of Smiting",
    entry: 19361,
    enchant: "Biznicks 247x128 Accurascope",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
];

const MARKSMANSHIP_HUNTER_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Dragonstalker's Helm",
    entry: 16939,
    enchant: "Falcon's Call",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Dragonstalker's Spaulders",
    entry: 16937,
    enchant: "Zandalar Signet of Might",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Dragonstalker's Breastplate",
    entry: 16942,
    enchant: "Chest - Greater Stats",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Wrist",
    item: "Dragonstalker's Bracers",
    entry: 16935,
    enchant: "Bracer - Minor Agility",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Dragonstalker's Gauntlets",
    entry: 16940,
    enchant: "Gloves - Greater Agility",
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Dragonstalker's Belt",
    entry: 16936,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Legs",
    item: "Dragonstalker's Legguards",
    entry: 16938,
    enchant: "Falcon's Call",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Dragonstalker's Greaves",
    entry: 16941,
    enchant: "Boots - Greater Agility",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Ring 1",
    item: "Don Julio's Band",
    entry: 19325,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Ring 2",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Renataki's Charm of Beasts",
    entry: 19953,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Crafted (Multiple Bosses)",
  },
  {
    slot: "Weapon",
    item: "Brutality Blade",
    entry: 18832,
    enchant: "Weapon - Agility",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Fang of the Faceless",
    entry: 19859,
    enchant: "Weapon - Agility",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Ranged",
    item: "Ashjre'thul, Crossbow of Smiting",
    entry: 19361,
    enchant: "Sniper Scope",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
];

const MARKSMANSHIP_HUNTER_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Striker's Diadem",
    entry: 21366,
    enchant: "Falcon's Call",
    source: "Quest Reward",
    detail: "Striker's Diadem",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Mantle of Wicked Revenge",
    entry: 21665,
    enchant: "Zandalar Signet of Might",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Striker's Hauberk",
    entry: 21370,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Striker's Hauberk",
  },
  {
    slot: "Wrist",
    item: "Dragonstalker's Bracers",
    entry: 16935,
    enchant: "Bracer - Minor Agility",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Vek'lor's Gloves of Devastation",
    entry: 21599,
    enchant: "Gloves - Superior Agility",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Waist",
    item: "Belt of Never-ending Agony",
    entry: 21586,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Dragonstalker's Legguards",
    entry: 16938,
    enchant: "Falcon's Call",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Dragonstalker's Greaves",
    entry: 16941,
    enchant: "Boots - Greater Agility",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Ring 1",
    item: "Signet Ring of the Bronze Dragonflight-v2",
    entry: 21200,
    enchant: null,
    source: "Quest Reward",
    detail: "The Qiraji Conqueror",
  },
  {
    slot: "Ring 2",
    item: "Ring of the Godslayer",
    entry: 21596,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Trinket 1",
    item: "Jom Gabbar",
    entry: 23570,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Ouro",
  },
  {
    slot: "Trinket 2",
    item: "Renataki's Charm of Beasts",
    entry: 19953,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Crafted (Multiple Bosses)",
  },
  {
    slot: "Weapon",
    item: "Silithid Claw",
    entry: 21673,
    enchant: "Weapon - Agility",
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Off Hand",
    item: "Fang of the Faceless",
    entry: 19859,
    enchant: "Weapon - Agility",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Ranged",
    item: "Ashjre'thul, Crossbow of Smiting",
    entry: 19361,
    enchant: "Biznicks 247x128 Accurascope",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
];

const MARKSMANSHIP_HUNTER_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Cryptstalker Headpiece",
    entry: 22438,
    enchant: "Falcon's Call",
    source: "Quest Reward",
    detail: "Cryptstalker Headpiece",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Cryptstalker Spaulders",
    entry: 22439,
    enchant: "Might of the Scourge",
    source: "Quest Reward",
    detail: "Cryptstalker Spaulders",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Cryptstalker Tunic",
    entry: 22436,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Cryptstalker Tunic",
  },
  {
    slot: "Wrist",
    item: "Cryptstalker Wristguards",
    entry: 22443,
    enchant: "Bracer - Minor Agility",
    source: "Quest Reward",
    detail: "Cryptstalker Wristguards",
  },
  {
    slot: "Hands",
    item: "Cryptstalker Handguards",
    entry: 22441,
    enchant: "Gloves - Superior Agility",
    source: "Quest Reward",
    detail: "Cryptstalker Handguards",
  },
  {
    slot: "Waist",
    item: "Cryptstalker Girdle",
    entry: 22442,
    enchant: null,
    source: "Quest Reward",
    detail: "Cryptstalker Girdle",
  },
  {
    slot: "Legs",
    item: "Cryptstalker Legguards",
    entry: 22437,
    enchant: "Falcon's Call",
    source: "Quest Reward",
    detail: "Cryptstalker Legguards",
  },
  {
    slot: "Feet",
    item: "Cryptstalker Boots",
    entry: 22440,
    enchant: "Boots - Greater Agility",
    source: "Quest Reward",
    detail: "Cryptstalker Boots",
  },
  {
    slot: "Ring 1",
    item: "Band of Reanimation",
    entry: 22961,
    enchant: null,
    source: "Naxxramas",
    detail: "Patchwerk",
  },
  {
    slot: "Ring 2",
    item: "Ring of the Cryptstalker",
    entry: 23067,
    enchant: null,
    source: "Quest Reward",
    detail: "Ring of the Cryptstalker",
  },
  {
    slot: "Trinket 1",
    item: "Slayer's Crest",
    entry: 23041,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Champion-v2",
    enchant: null,
    source: "Quest Reward",
    detail: "The Fall of Kel'Thuzad",
  },
  {
    slot: "Weapon",
    item: "Kingsfall",
    entry: 22802,
    enchant: "Weapon - Agility",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Off Hand",
    item: "Iblis, Blade of the Fallen Seraph",
    entry: 23014,
    enchant: "Weapon - Agility",
    source: "Naxxramas",
    detail: "Instructor Razuvious",
  },
  {
    slot: "Ranged",
    item: "Nerubian Slavemaker",
    entry: 22812,
    enchant: "Sniper Scope",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
];

export const MARKSMANSHIP_HUNTER_BIS: BiSSpecData = {
  classSlug: "hunter",
  specSlug: "marksmanship",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: MARKSMANSHIP_HUNTER_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: MARKSMANSHIP_HUNTER_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: MARKSMANSHIP_HUNTER_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: MARKSMANSHIP_HUNTER_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: MARKSMANSHIP_HUNTER_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: MARKSMANSHIP_HUNTER_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: MARKSMANSHIP_HUNTER_PHASE_6_GEAR },
  ],
  talentImage: marksmanshipHunterTalents,
  classGuide: {
    introduction: "Marksmanship is the go-to spec for all of WoW Classic. You bring Trueshot Aura which is a great additional to any melee group.",
    rotationNote: "Marksmanship Hunters use a slightly different rotation based on how fast their weapon is. If your weapon has a speed of 3 or more seconds you will perform a rotation prioritizing Auto Shot and delaying Aimed Shot, and if your weapon has a speed less than 3, you will perform a rotation using Aimed Shot as soon as its available.",
    singleTarget: [
      "Use Aspect of the Hawk",
      "Use Trueshot Aura.",
      "Maintain Hunter's Mark.",
      "Use Rapid Fire.",
      "Use Auto Shot.",
      "Use Aimed Shot without clipping Auto Shot unless you have a fast weapon, otherwise wait for and use Auto Shot, then use Aimed Shot.",
      "Use Multi-Shot without clipping Auto Shot, otherwise wait for and use Auto Shot, then use Multi-Shot.",
    ],
    aoe: [
      "Use Auto Shot.",
      "Use Multi-Shot.",
      "Use Volley.",
      "Perform single target rotation.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Elixir of the Mongoose",
      alternatives: "Elixir of Greater Agility",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Grilled Squid",
      note: "undefined",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Mana Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Juju Might, Juju Power (Pet Only), Ground Scorpok Assay, R.O.I.D.S., Cerebral Cortex Compound",
    },
  ],
};

export const HUNTER_BIS_SPECS: BiSSpecData[] = [MARKSMANSHIP_HUNTER_BIS];
