import {
  faFlask,
  faBreadSlice,
  faVial,
  faHammer,
  faDice,
} from "@fortawesome/free-solid-svg-icons";
import type { BiSGearEntry, BiSSpecData } from "../types";
import arcaneMageTalents from "../assets/BiS Talents/Mage - Arcane.png";
import fireMageTalents from "../assets/BiS Talents/Mage - Fire.png";
import frostMageTalents from "../assets/BiS Talents/Mage - Frost.png";

const ARCANE_MAGE_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Diana's Pearl Necklace",
    entry: 22403,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Cannon Master Willey",
  },
  {
    slot: "Shoulder",
    item: "Boreal Mantle",
    entry: 11782,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Depths",
    detail: "Warden Stilgiss",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Manacle Cuffs",
    entry: 11962,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "The Love Potion",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Ban'thok Sash",
    entry: 11662,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Omnicast Boots",
    entry: 11822,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Ring 1",
    item: "Eye of Orgrimmar",
    entry: 12545,
    enchant: null,
    source: "Quest Reward",
    detail: "The Princess Saved?",
  },
  {
    slot: "Ring 2",
    item: "Cyclopean Band",
    entry: 11824,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Trinket 1",
    item: "Eye of the Beast",
    entry: 13968,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Witchblade",
    entry: 13964,
    enchant: "Weapon - Spell Power",
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Bonecreeper Stylus",
    entry: 13938,
    enchant: null,
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
];

const ARCANE_MAGE_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Arcanist Crown",
    entry: 16795,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Boreal Mantle",
    entry: 11782,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Depths",
    detail: "Warden Stilgiss",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Arcanist Bindings",
    entry: 16799,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Netherwind Pants",
    entry: 16915,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Arcanist Boots",
    entry: 16800,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Lucifron",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Bonecreeper Stylus",
    entry: 13938,
    enchant: null,
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
];

const ARCANE_MAGE_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Arcanist Crown",
    entry: 16795,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Boreal Mantle",
    entry: 11782,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Depths",
    detail: "Warden Stilgiss",
  },
  {
    slot: "Back",
    item: "Amplifying Cloak",
    entry: 18350,
    enchant: "Cloak - Greater Resistance",
    source: "Dire Maul (West)",
    detail: "Magister Kalendris",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Arcanist Bindings",
    entry: 16799,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Arcanist Leggings",
    entry: 16796,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Magmadar",
  },
  {
    slot: "Feet",
    item: "Arcanist Boots",
    entry: 16800,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Lucifron",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Tome of the Ice Lord",
    entry: 19310,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Ranged",
    item: "Wand of Biting Cold",
    entry: 19108,
    enchant: null,
    source: "Quest Reward",
    detail: "Hero of the Frostwolf (H)",
  },
];

const ARCANE_MAGE_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Brood Lord",
    entry: 19378,
    enchant: "Cloak - Greater Resistance",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Netherwind Gloves",
    entry: 16913,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Netherwind Pants",
    entry: 16915,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Ringo's Blizzard Boots",
    entry: 19438,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mind Quickening Gem",
    entry: 19339,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Weapon",
    item: "Staff of the Shadow Flame",
    entry: 19356,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ranged",
    item: "Wand of Biting Cold",
    entry: 19108,
    enchant: null,
    source: "Quest Reward",
    detail: "Hero of the Frostwolf (H)",
  },
];

const ARCANE_MAGE_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Presence of Sight",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of Consumption",
    entry: 19857,
    enchant: "Cloak - Greater Resistance",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Netherwind Gloves",
    entry: 16913,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Presence of Sight",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mind Quickening Gem",
    entry: 19339,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Weapon",
    item: "Staff of the Shadow Flame",
    entry: 19356,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ranged",
    item: "Touch of Chaos",
    entry: 19861,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
];

const ARCANE_MAGE_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Presence of Sight",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Amulet of Vek'nilash",
    entry: 21608,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Devoured",
    entry: 22731,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Enigma Robes",
    entry: 21343,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Enigma Robes",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: "Gloves - Frost Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of the Black Blizzard",
    entry: 21461,
    enchant: "Presence of Sight",
    source: "Ruins of Ahn'Qiraj",
    detail: "Ossirian the Unscarred",
  },
  {
    slot: "Feet",
    item: "Ringo's Blizzard Boots",
    entry: 19438,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Ritssyn's Ring of Chaos",
    entry: 21836,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Trash Drop",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mind Quickening Gem",
    entry: 19339,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Weapon",
    item: "Sharpened Silithid Femur",
    entry: 21622,
    enchant: "Weapon - Spell Power",
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Off Hand",
    item: "Royal Scepter of Vek'lor",
    entry: 21597,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Ranged",
    item: "Wand of Qiraji Nobility",
    entry: 21603,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Lord Kri",
  },
];

const ARCANE_MAGE_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Frostfire Circlet",
    entry: 22498,
    enchant: "Presence of Sight",
    source: "Quest Reward",
    detail: "Frostfire Circlet",
  },
  {
    slot: "Neck",
    item: "Gem of Trapped Innocents",
    entry: 23057,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Rime Covered Mantle",
    entry: 22983,
    enchant: "Zandalar Signet of Mojo",
    source: "Naxxramas",
    detail: "Gluth",
  },
  {
    slot: "Back",
    item: "Cloak of the Necropolis",
    entry: 23050,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Chest",
    item: "Frostfire Robe",
    entry: 22496,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Frostfire Robe",
  },
  {
    slot: "Wrist",
    item: "The Soul Harvester's Bindings",
    entry: 23021,
    enchant: "Bracer - Greater Intellect",
    source: "Naxxramas",
    detail: "Gothik the Harvester",
  },
  {
    slot: "Hands",
    item: "Frostfire Gloves",
    entry: 22501,
    enchant: "Gloves - Frost Power",
    source: "Quest Reward",
    detail: "Frostfire Gloves",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of Polarity",
    entry: 23070,
    enchant: "Presence of Sight",
    source: "Naxxramas",
    detail: "Thaddius",
  },
  {
    slot: "Feet",
    item: "Frostfire Sandals",
    entry: 22500,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Frostfire Sandals",
  },
  {
    slot: "Ring 1",
    item: "Frostfire Ring",
    entry: 23062,
    enchant: null,
    source: "Quest Reward",
    detail: "Frostfire Ring",
  },
  {
    slot: "Ring 2",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "The Restrained Essence of Sapphiron",
    entry: 23046,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Weapon",
    item: "Wraith Blade",
    entry: 22807,
    enchant: "Weapon - Spell Power",
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Off Hand",
    item: "Sapphiron's Left Eye",
    entry: 23049,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Ranged",
    item: "Doomfinger",
    entry: 22821,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
];

export const ARCANE_MAGE_BIS: BiSSpecData = {
  classSlug: "mage",
  specSlug: "arcane",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: ARCANE_MAGE_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: ARCANE_MAGE_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: ARCANE_MAGE_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: ARCANE_MAGE_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: ARCANE_MAGE_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: ARCANE_MAGE_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: ARCANE_MAGE_PHASE_6_GEAR },
  ],
  talentImage: arcaneMageTalents,
  classGuide: {
    introduction: "Arcane Power Frost is the go-to PvE spec for Mages until Phase 4 since Molten Core and Blackwing Lair bosses have Fire immunity.",
    singleTarget: [
      "Cast Arcane Power and any on use trinkets when Winter's Chill reaches 5 stacks.",
      "Cast Presence of Mind with Frostbolt if your Arcane Power will expire before your next Frostbolt cast finishes.",
      "Cast Frostbolt.",
      "Cast Fire Blast or Arcane Explosion if the target will die before your next Frostbolt cast finishes or while moving.",
    ],
    aoe: [
      "Cast Cone of Cold.",
      "Cast Arcane Explosion if you can be close to the enemies, otherwise cast Blizzard.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Flask of Supreme Power",
      alternatives: "Greater Arcane Elixir",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Wizard Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

const FIRE_MAGE_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Diana's Pearl Necklace",
    entry: 22403,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Cannon Master Willey",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Manacle Cuffs",
    entry: 11962,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "The Love Potion",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Ban'thok Sash",
    entry: 11662,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Omnicast Boots",
    entry: 11822,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Ring 1",
    item: "Eye of Orgrimmar",
    entry: 12545,
    enchant: null,
    source: "Quest Reward",
    detail: "The Princess Saved?",
  },
  {
    slot: "Ring 2",
    item: "Cyclopean Band",
    entry: 11824,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Trinket 1",
    item: "Eye of the Beast",
    entry: 13968,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Witchblade",
    entry: 13964,
    enchant: "Weapon - Spell Power",
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Bonecreeper Stylus",
    entry: 13938,
    enchant: null,
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
];

const FIRE_MAGE_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Arcanist Crown",
    entry: 16795,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Arcanist Bindings",
    entry: 16799,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Netherwind Pants",
    entry: 16915,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Arcanist Boots",
    entry: 16800,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Lucifron",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Bonecreeper Stylus",
    entry: 13938,
    enchant: null,
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
];

const FIRE_MAGE_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Arcanist Crown",
    entry: 16795,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Back",
    item: "Amplifying Cloak",
    entry: 18350,
    enchant: "Cloak - Greater Resistance",
    source: "Dire Maul (West)",
    detail: "Magister Kalendris",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Arcanist Bindings",
    entry: 16799,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Arcanist Leggings",
    entry: 16796,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Magmadar",
  },
  {
    slot: "Feet",
    item: "Arcanist Boots",
    entry: 16800,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Lucifron",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
];

const FIRE_MAGE_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Brood Lord",
    entry: 19378,
    enchant: "Cloak - Greater Resistance",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Netherwind Gloves",
    entry: 16913,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Netherwind Pants",
    entry: 16915,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mind Quickening Gem",
    entry: 19339,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Weapon",
    item: "Staff of the Shadow Flame",
    entry: 19356,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
];

const FIRE_MAGE_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Presence of Sight",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of Consumption",
    entry: 19857,
    enchant: "Cloak - Greater Resistance",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Netherwind Gloves",
    entry: 16913,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Presence of Sight",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mind Quickening Gem",
    entry: 19339,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Weapon",
    item: "Staff of the Shadow Flame",
    entry: 19356,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ranged",
    item: "Touch of Chaos",
    entry: 19861,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
];

const FIRE_MAGE_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Presence of Sight",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Amulet of Vek'nilash",
    entry: 21608,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Devoured",
    entry: 22731,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Enigma Robes",
    entry: 21343,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Enigma Robes",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: "Gloves - Fire Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of the Black Blizzard",
    entry: 21461,
    enchant: "Presence of Sight",
    source: "Ruins of Ahn'Qiraj",
    detail: "Ossirian the Unscarred",
  },
  {
    slot: "Feet",
    item: "Enigma Boots",
    entry: 21344,
    enchant: null,
    source: "Quest Reward",
    detail: "Enigma Boots",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Ritssyn's Ring of Chaos",
    entry: 21836,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Trash Drop",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mind Quickening Gem",
    entry: 19339,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Weapon",
    item: "Sharpened Silithid Femur",
    entry: 21622,
    enchant: "Weapon - Spell Power",
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Off Hand",
    item: "Royal Scepter of Vek'lor",
    entry: 21597,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Ranged",
    item: "Wand of Qiraji Nobility",
    entry: 21603,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Lord Kri",
  },
];

const FIRE_MAGE_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Frostfire Circlet",
    entry: 22498,
    enchant: "Presence of Sight",
    source: "Quest Reward",
    detail: "Frostfire Circlet",
  },
  {
    slot: "Neck",
    item: "Gem of Trapped Innocents",
    entry: 23057,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Rime Covered Mantle",
    entry: 22983,
    enchant: "Zandalar Signet of Mojo",
    source: "Naxxramas",
    detail: "Gluth",
  },
  {
    slot: "Back",
    item: "Cloak of the Necropolis",
    entry: 23050,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Chest",
    item: "Frostfire Robe",
    entry: 22496,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Frostfire Robe",
  },
  {
    slot: "Wrist",
    item: "The Soul Harvester's Bindings",
    entry: 23021,
    enchant: "Bracer - Greater Intellect",
    source: "Naxxramas",
    detail: "Gothik the Harvester",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: "Gloves - Fire Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of Polarity",
    entry: 23070,
    enchant: "Presence of Sight",
    source: "Naxxramas",
    detail: "Thaddius",
  },
  {
    slot: "Feet",
    item: "Frostfire Sandals",
    entry: 22500,
    enchant: null,
    source: "Quest Reward",
    detail: "Frostfire Sandals",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Eternal Flame",
    entry: 23237,
    enchant: null,
    source: "Naxxramas",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 2",
    item: "Frostfire Ring",
    entry: 23062,
    enchant: null,
    source: "Quest Reward",
    detail: "Frostfire Ring",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "The Restrained Essence of Sapphiron",
    entry: 23046,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Weapon",
    item: "Wraith Blade",
    entry: 22807,
    enchant: "Weapon - Spell Power",
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Off Hand",
    item: "Sapphiron's Left Eye",
    entry: 23049,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Ranged",
    item: "Doomfinger",
    entry: 22821,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
];

export const FIRE_MAGE_BIS: BiSSpecData = {
  classSlug: "mage",
  specSlug: "fire",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: FIRE_MAGE_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: FIRE_MAGE_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: FIRE_MAGE_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: FIRE_MAGE_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: FIRE_MAGE_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: FIRE_MAGE_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: FIRE_MAGE_PHASE_6_GEAR },
  ],
  talentImage: fireMageTalents,
  classGuide: {
    introduction: "Fire is the go-to spec for Mages once Phase 4 begins since bosses in the current raid tier will no longer be immune to Fire damage. Fire is very dependent on Critical Strikes because of talents such as Ignite and Master of Elements.",
    singleTarget: [
      "Maintain 5 stacks of Improved Scorch if assigned.",
      "Cast Combustion and any on use trinkets.",
      "Cast Fireball.",
      "Cast Fire Blast or Arcane Explosion if the target will die before your next Fireball cast finishes or while moving.",
    ],
    aoe: [
      "Cast Blast Wave.",
      "Cast Flamestrike.",
      "Cast Arcane Explosion.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Flask of Supreme Power",
      alternatives: "Greater Arcane Elixir",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Wizard Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

const FROST_MAGE_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Diana's Pearl Necklace",
    entry: 22403,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Cannon Master Willey",
  },
  {
    slot: "Shoulder",
    item: "Boreal Mantle",
    entry: 11782,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Depths",
    detail: "Warden Stilgiss",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Manacle Cuffs",
    entry: 11962,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "The Love Potion",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Ban'thok Sash",
    entry: 11662,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Omnicast Boots",
    entry: 11822,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Ring 1",
    item: "Eye of Orgrimmar",
    entry: 12545,
    enchant: null,
    source: "Quest Reward",
    detail: "The Princess Saved?",
  },
  {
    slot: "Ring 2",
    item: "Cyclopean Band",
    entry: 11824,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Trinket 1",
    item: "Eye of the Beast",
    entry: 13968,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Witchblade",
    entry: 13964,
    enchant: "Weapon - Spell Power",
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Bonecreeper Stylus",
    entry: 13938,
    enchant: null,
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
];

const FROST_MAGE_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Arcanist Crown",
    entry: 16795,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Boreal Mantle",
    entry: 11782,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Depths",
    detail: "Warden Stilgiss",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Arcanist Bindings",
    entry: 16799,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Netherwind Pants",
    entry: 16915,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Arcanist Boots",
    entry: 16800,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Lucifron",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Bonecreeper Stylus",
    entry: 13938,
    enchant: null,
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
];

const FROST_MAGE_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Arcanist Crown",
    entry: 16795,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Boreal Mantle",
    entry: 11782,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Depths",
    detail: "Warden Stilgiss",
  },
  {
    slot: "Back",
    item: "Amplifying Cloak",
    entry: 18350,
    enchant: "Cloak - Greater Resistance",
    source: "Dire Maul (West)",
    detail: "Magister Kalendris",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Arcanist Bindings",
    entry: 16799,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Arcanist Leggings",
    entry: 16796,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Magmadar",
  },
  {
    slot: "Feet",
    item: "Arcanist Boots",
    entry: 16800,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Lucifron",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Tome of the Ice Lord",
    entry: 19310,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Ranged",
    item: "Wand of Biting Cold",
    entry: 19108,
    enchant: null,
    source: "Quest Reward",
    detail: "Hero of the Frostwolf (H)",
  },
];

const FROST_MAGE_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Brood Lord",
    entry: 19378,
    enchant: "Cloak - Greater Resistance",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Chest",
    item: "Robe of the Archmage",
    entry: 14152,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Netherwind Gloves",
    entry: 16913,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Netherwind Pants",
    entry: 16915,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Ringo's Blizzard Boots",
    entry: 19438,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mind Quickening Gem",
    entry: 19339,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Weapon",
    item: "Staff of the Shadow Flame",
    entry: 19356,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ranged",
    item: "Wand of Biting Cold",
    entry: 19108,
    enchant: null,
    source: "Quest Reward",
    detail: "Hero of the Frostwolf (H)",
  },
];

const FROST_MAGE_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Presence of Sight",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of Consumption",
    entry: 19857,
    enchant: "Cloak - Greater Resistance",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Netherwind Gloves",
    entry: 16913,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Presence of Sight",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mind Quickening Gem",
    entry: 19339,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Weapon",
    item: "Staff of the Shadow Flame",
    entry: 19356,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ranged",
    item: "Touch of Chaos",
    entry: 19861,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
];

const FROST_MAGE_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Presence of Sight",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Amulet of Vek'nilash",
    entry: 21608,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Devoured",
    entry: 22731,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Enigma Robes",
    entry: 21343,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Enigma Robes",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: "Gloves - Frost Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of the Black Blizzard",
    entry: 21461,
    enchant: "Presence of Sight",
    source: "Ruins of Ahn'Qiraj",
    detail: "Ossirian the Unscarred",
  },
  {
    slot: "Feet",
    item: "Ringo's Blizzard Boots",
    entry: 19438,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Ritssyn's Ring of Chaos",
    entry: 21836,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Trash Drop",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mind Quickening Gem",
    entry: 19339,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Weapon",
    item: "Sharpened Silithid Femur",
    entry: 21622,
    enchant: "Weapon - Spell Power",
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Off Hand",
    item: "Royal Scepter of Vek'lor",
    entry: 21597,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Ranged",
    item: "Wand of Qiraji Nobility",
    entry: 21603,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Lord Kri",
  },
];

const FROST_MAGE_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Frostfire Circlet",
    entry: 22498,
    enchant: "Presence of Sight",
    source: "Quest Reward",
    detail: "Frostfire Circlet",
  },
  {
    slot: "Neck",
    item: "Gem of Trapped Innocents",
    entry: 23057,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Rime Covered Mantle",
    entry: 22983,
    enchant: "Zandalar Signet of Mojo",
    source: "Naxxramas",
    detail: "Gluth",
  },
  {
    slot: "Back",
    item: "Cloak of the Necropolis",
    entry: 23050,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Chest",
    item: "Frostfire Robe",
    entry: 22496,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Frostfire Robe",
  },
  {
    slot: "Wrist",
    item: "The Soul Harvester's Bindings",
    entry: 23021,
    enchant: "Bracer - Greater Intellect",
    source: "Naxxramas",
    detail: "Gothik the Harvester",
  },
  {
    slot: "Hands",
    item: "Frostfire Gloves",
    entry: 22501,
    enchant: "Gloves - Frost Power",
    source: "Quest Reward",
    detail: "Frostfire Gloves",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of Polarity",
    entry: 23070,
    enchant: "Presence of Sight",
    source: "Naxxramas",
    detail: "Thaddius",
  },
  {
    slot: "Feet",
    item: "Frostfire Sandals",
    entry: 22500,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Frostfire Sandals",
  },
  {
    slot: "Ring 1",
    item: "Frostfire Ring",
    entry: 23062,
    enchant: null,
    source: "Quest Reward",
    detail: "Frostfire Ring",
  },
  {
    slot: "Ring 2",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "The Restrained Essence of Sapphiron",
    entry: 23046,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Weapon",
    item: "Wraith Blade",
    entry: 22807,
    enchant: "Weapon - Spell Power",
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Off Hand",
    item: "Sapphiron's Left Eye",
    entry: 23049,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Ranged",
    item: "Doomfinger",
    entry: 22821,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
];

export const FROST_MAGE_BIS: BiSSpecData = {
  classSlug: "mage",
  specSlug: "frost",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: FROST_MAGE_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: FROST_MAGE_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: FROST_MAGE_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: FROST_MAGE_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: FROST_MAGE_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: FROST_MAGE_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: FROST_MAGE_PHASE_6_GEAR },
  ],
  talentImage: frostMageTalents,
  classGuide: {
    introduction: "At least one Frost Mage will be imperative for a raid group with multipe Arcane Power Mages in it because of Winter's Chill.",
    rotationNote: "This build will do less damage than the Arcane Power Mages, but you do gain acess to great utility spells such as Cold Snap and Ice Block. You can even take Ice Barrier instead of Presence of Mind if you want.",
    singleTarget: [
      "Maintain 5 stacks of Winter's Chill if assigned.",
      "Cast Presence of Mind with Frostbolt.",
      "Cast Frostbolt.",
      "Cast Fire Blast or Arcane Explosion if the target will die before your next Frostbolt cast finishes or while moving.",
    ],
    aoe: [
      "Cast Cone of Cold.",
      "Cast Arcane Explosion if you can be close to the enemies, otherwise cast Blizzard.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Flask of Supreme Power",
      alternatives: "Greater Arcane Elixir",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Wizard Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

export const MAGE_BIS_SPECS: BiSSpecData[] = [ARCANE_MAGE_BIS, FIRE_MAGE_BIS, FROST_MAGE_BIS];
