import {
  faFlask,
  faBreadSlice,
  faVial,
  faHammer,
  faDice,
} from "@fortawesome/free-solid-svg-icons";
import type { BiSGearEntry, BiSSpecData } from "../types";
import holyPaladinTalents from "../assets/BiS Talents/Paladin - Holy.png";

const HOLY_PALADIN_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Whitesoul Helm",
    entry: 12633,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "Animated Chain Necklace",
    entry: 18723,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Ramstein the Gorger",
  },
  {
    slot: "Shoulder",
    item: "Living Shoulders",
    entry: 15061,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Leatherworking",
    detail: "BoE Pattern (270)",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Loomguard Armbraces",
    entry: 13969,
    enchant: "Bracer - Greater Intellect",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Hands",
    item: "Hands of the Exalted Herald",
    entry: 12554,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Waist",
    item: "Belt of the Ordained",
    entry: 18702,
    enchant: null,
    source: "Scholomance",
    detail: "Trash Drop",
  },
  {
    slot: "Legs",
    item: "Senior Designer's Pantaloons",
    entry: 11841,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Depths",
    detail: "Fineous Darkvire",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Fordring's Seal",
    entry: 16058,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Ring 2",
    item: "Rosewine Circle",
    entry: 13178,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Urok Doomhowl",
  },
  {
    slot: "Trinket 1",
    item: "Second Wind",
    entry: 11819,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "The Hammer of Grace",
    entry: 11923,
    enchant: "Weapon - Healing Power",
    source: "Blackrock Depths",
    detail: "Chest of the Seven",
  },
  {
    slot: "Off Hand",
    item: "Thaurissan's Royal Scepter",
    entry: 11928,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
];

const HOLY_PALADIN_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Helm of the Lifegiver",
    entry: 18870,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Loomguard Armbraces",
    entry: 13969,
    enchant: "Bracer - Greater Intellect",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Hands",
    item: "Hands of the Exalted Herald",
    entry: 12554,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Salamander Scale Pants",
    entry: 18875,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Healing Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Thaurissan's Royal Scepter",
    entry: 11928,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
];

const HOLY_PALADIN_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Helm of the Lifegiver",
    entry: 18870,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Hide of the Wild",
    entry: 18510,
    enchant: "Cloak - Greater Resistance",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Loomguard Armbraces",
    entry: 13969,
    enchant: "Bracer - Greater Intellect",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Hands",
    item: "Harmonious Gauntlets",
    entry: 18527,
    enchant: null,
    source: "Dire Maul (North)",
    detail: "King Gordok",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Salamander Scale Pants",
    entry: 18875,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Healing Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Lei of the Lifegiver",
    entry: 19312,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const HOLY_PALADIN_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Hide of the Wild",
    entry: 18510,
    enchant: "Cloak - Greater Resistance",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Loomguard Armbraces",
    entry: 13969,
    enchant: "Bracer - Healing Power",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Hands",
    item: "Harmonious Gauntlets",
    entry: 18527,
    enchant: null,
    source: "Dire Maul (North)",
    detail: "King Gordok",
  },
  {
    slot: "Waist",
    item: "Corehound Belt",
    entry: 19162,
    enchant: null,
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Scrolls of Blinding Light",
    entry: 19343,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Healing Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Lei of the Lifegiver",
    entry: 19312,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const HOLY_PALADIN_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Syncretist's Sigil",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Jin'do's Evil Eye",
    entry: 19885,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Jin'do the Hexxer",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Zandalar Signet of Serenity",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Hide of the Wild",
    entry: 18510,
    enchant: "Cloak - Greater Resistance",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Loomguard Armbraces",
    entry: 13969,
    enchant: "Bracer - Healing Power",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Hands",
    item: "Peacekeeper Gauntlets",
    entry: 20264,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Waist",
    item: "Corehound Belt",
    entry: 19162,
    enchant: null,
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Syncretist's Sigil",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Scrolls of Blinding Light",
    entry: 19343,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Healing Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Lei of the Lifegiver",
    entry: 19312,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const HOLY_PALADIN_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Don Rigoberto's Lost Hat",
    entry: 21615,
    enchant: "Syncretist's Sigil",
    source: "Ahn'Qiraj",
    detail: "Ouro",
  },
  {
    slot: "Neck",
    item: "Amulet of the Fallen God",
    entry: 21712,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Zandalar Signet of Serenity",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Cloak of Clarity",
    entry: 21583,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Robes of the Guardian Saint",
    entry: 21663,
    enchant: "Chest - Greater Stats",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Wrist",
    item: "Bracelets of Royal Redemption",
    entry: 21604,
    enchant: "Bracer - Healing Power",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Hands",
    item: "Peacekeeper Gauntlets",
    entry: 20264,
    enchant: "Gloves - Healing Power",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Waist",
    item: "Grasp of the Old God",
    entry: 21582,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Legplates of Blazing Light",
    entry: 21667,
    enchant: "Syncretist's Sigil",
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Ring of the Martyr",
    entry: 21620,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Princess Huhuran",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Scrolls of Blinding Light",
    entry: 19343,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Weapon",
    item: "Scepter of the False Prophet",
    entry: 21839,
    enchant: "Weapon - Healing Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Off Hand",
    item: "Sartura's Might",
    entry: 21666,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Relic",
    item: "Libram of Divinity",
    entry: 23201,
    enchant: null,
    source: "Scholomance",
    detail: "Multiple Bosses",
  },
];

const HOLY_PALADIN_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Redemption Headpiece",
    entry: 22428,
    enchant: "Syncretist's Sigil",
    source: "Quest Reward",
    detail: "Redemption Headpiece",
  },
  {
    slot: "Neck",
    item: "Necklace of Necropsy",
    entry: 23036,
    enchant: null,
    source: "Naxxramas",
    detail: "Heigan the Unclean",
  },
  {
    slot: "Shoulder",
    item: "Redemption Spaulders",
    entry: 22429,
    enchant: "Zandalar Signet of Serenity",
    source: "Quest Reward",
    detail: "Redemption Spaulders",
  },
  {
    slot: "Back",
    item: "Cloak of Suturing",
    entry: 22960,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Patchwerk",
  },
  {
    slot: "Chest",
    item: "Redemption Tunic",
    entry: 22425,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Redemption Tunic",
  },
  {
    slot: "Wrist",
    item: "Bracelets of Royal Redemption",
    entry: 21604,
    enchant: "Bracer - Healing Power",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Hands",
    item: "Peacekeeper Gauntlets",
    entry: 20264,
    enchant: "Gloves - Healing Power",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Waist",
    item: "Grasp of the Old God",
    entry: 21582,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Legplates of Blazing Light",
    entry: 21667,
    enchant: "Syncretist's Sigil",
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Feet",
    item: "Redemption Boots",
    entry: 22430,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Redemption Boots",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Band of Unanswered Prayers",
    entry: 22939,
    enchant: null,
    source: "Naxxramas",
    detail: "Anub'Rekhan",
  },
  {
    slot: "Trinket 1",
    item: "Eye of the Dead",
    entry: 23047,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Trinket 2",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Weapon",
    item: "Hammer of the Twisting Nether",
    entry: 23056,
    enchant: "Weapon - Healing Power",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Off Hand",
    item: "Sapphiron's Right Eye",
    entry: 23048,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Relic",
    item: "Libram of Light",
    entry: 23006,
    enchant: null,
    source: "Naxxramas",
    detail: "Noth the Plaguebringer",
  },
];

export const HOLY_PALADIN_BIS: BiSSpecData = {
  classSlug: "paladin",
  specSlug: "holy",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: HOLY_PALADIN_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: HOLY_PALADIN_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: HOLY_PALADIN_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: HOLY_PALADIN_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: HOLY_PALADIN_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: HOLY_PALADIN_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: HOLY_PALADIN_PHASE_6_GEAR },
  ],
  talentImage: holyPaladinTalents,
  classGuide: {
    introduction: "Paladins are extremely important to raid compositions because of their Blessings. Holy Paladins excel at single target healing, and are very mana efficient healers thanks to Illumination.",
    rotationNote: "One of the unique things about healing is downranking heals. We mention some specific ranks of certain heals below as a starting point, but finding out which ranks work best will be up to you. The ranks you choose will change based on each boss depending on the situation and length of the encounter, as well your target and how much health they are missing.",
    singleTarget: [
      "Maintain your assigned Aura.",
      "Maintain Seal of Light's or Seal of Wisdom's Judgement debuff.",
      "Use Divine Favor with Holy Shock or Holy Light for a guaranteed crit.",
      "Cast Flash of Light. This is your spam heal.",
      "Cast Holy Light for big heals.",
      "Cast Holy Shock on the move or if you need to heal someone faster than a Flash of Light cast (1.5 sec).",
      "If you need to start conserving mana, you can start downranking and use spells such as Flash of Light R4 or Holy Light R6.",
    ],
    aoe: [
      "Same as single target.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Mageblood Potion (Phase 4)",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup, Sagefish Delight",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Mana Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

export const PALADIN_BIS_SPECS: BiSSpecData[] = [HOLY_PALADIN_BIS];
