import {
  faFlask,
  faBreadSlice,
  faVial,
  faHammer,
  faDice,
} from "@fortawesome/free-solid-svg-icons";
import type { BiSGearEntry, BiSSpecData } from "../types";
import holyPriestTalents from "../assets/BiS Talents/Priest - Holy.png";
import shadowPriestTalents from "../assets/BiS Talents/Priest - Shadow.png";

const HOLY_PRIEST_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Rumination",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Animated Chain Necklace",
    entry: 18723,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Ramstein the Gorger",
  },
  {
    slot: "Shoulder",
    item: "Burial Shawl",
    entry: 18681,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Scholomance",
    detail: "Lord Alexei Barov",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Truefaith Vestments",
    entry: 14154,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Devout Bracers",
    entry: 16697,
    enchant: "Bracer - Superior Spirit",
    source: "Stratholme",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of the Exalted Herald",
    entry: 12554,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Waist",
    item: "Thuzadin Sash",
    entry: 18740,
    enchant: null,
    source: "Stratholme (Undead)",
    detail: "Nerub'enkan",
  },
  {
    slot: "Legs",
    item: "Senior Designer's Pantaloons",
    entry: 11841,
    enchant: "Lesser Arcanum of Rumination",
    source: "Blackrock Depths",
    detail: "Fineous Darkvire",
  },
  {
    slot: "Feet",
    item: "Omnicast Boots",
    entry: 11822,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Ring 1",
    item: "Fordring's Seal",
    entry: 16058,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Ring 2",
    item: "Rosewine Circle",
    entry: 13178,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Urok Doomhowl",
  },
  {
    slot: "Trinket 1",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Trinket 2",
    item: "Second Wind",
    entry: 11819,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Weapon",
    item: "The Hammer of Grace",
    entry: 11923,
    enchant: "Weapon - Healing Power",
    source: "Blackrock Depths",
    detail: "Chest of the Seven",
  },
  {
    slot: "Off Hand",
    item: "Thaurissan's Royal Scepter",
    entry: 11928,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Ranged",
    item: "Bonecreeper Stylus",
    entry: 13938,
    enchant: null,
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
];

const HOLY_PRIEST_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Halo of Transcendence",
    entry: 16921,
    enchant: "Lesser Arcanum of Rumination",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Animated Chain Necklace",
    entry: 18723,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Ramstein the Gorger",
  },
  {
    slot: "Shoulder",
    item: "Mantle of Prophecy",
    entry: 16816,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Sulfuron Harbinger",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Truefaith Vestments",
    entry: 14154,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Vambraces of Prophecy",
    entry: 16819,
    enchant: "Bracer - Superior Spirit",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of the Exalted Herald",
    entry: 12554,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Waist",
    item: "Girdle of Prophecy",
    entry: 16817,
    enchant: null,
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Legs",
    item: "Leggings of Transcendence",
    entry: 16922,
    enchant: "Lesser Arcanum of Rumination",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Boots of Prophecy",
    entry: 16811,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Shazzrah",
  },
  {
    slot: "Ring 1",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Trinket 2",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Weapon",
    item: "Benediction",
    entry: 18608,
    enchant: "Weapon - Healing Power",
    source: "Quest Reward",
    detail: "The Balance of Light and Shadow",
  },
  {
    slot: "Ranged",
    item: "Bonecreeper Stylus",
    entry: 13938,
    enchant: null,
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
];

const HOLY_PRIEST_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Halo of Transcendence",
    entry: 16921,
    enchant: "Arcanum of Focus",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Animated Chain Necklace",
    entry: 18723,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Ramstein the Gorger",
  },
  {
    slot: "Shoulder",
    item: "Mantle of Prophecy",
    entry: 16816,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Sulfuron Harbinger",
  },
  {
    slot: "Back",
    item: "Hide of the Wild",
    entry: 18510,
    enchant: "Cloak - Greater Resistance",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Chest",
    item: "Truefaith Vestments",
    entry: 14154,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Vambraces of Prophecy",
    entry: 16819,
    enchant: "Bracer - Superior Spirit",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of the Exalted Herald",
    entry: 12554,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Waist",
    item: "Whipvine Cord",
    entry: 18327,
    enchant: null,
    source: "Dire Maul (East)",
    detail: "Alzzin the Wildshaper",
  },
  {
    slot: "Legs",
    item: "Leggings of Transcendence",
    entry: 16922,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Boots of Prophecy",
    entry: 16811,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Shazzrah",
  },
  {
    slot: "Ring 1",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Royal Seal of Eldre'Thalas (Priest)",
    entry: 18469,
    enchant: null,
    source: "Quest Reward",
    detail: "Holy Bologna: What the Light Won't Tell You",
  },
  {
    slot: "Weapon",
    item: "Benediction",
    entry: 18608,
    enchant: "Weapon - Healing Power",
    source: "Quest Reward",
    detail: "The Balance of Light and Shadow",
  },
  {
    slot: "Ranged",
    item: "Bonecreeper Stylus",
    entry: 13938,
    enchant: null,
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
];

const HOLY_PRIEST_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Halo of Transcendence",
    entry: 16921,
    enchant: "Arcanum of Focus",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Animated Chain Necklace",
    entry: 18723,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Ramstein the Gorger",
  },
  {
    slot: "Shoulder",
    item: "Pauldrons of Transcendence",
    entry: 16924,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Back",
    item: "Hide of the Wild",
    entry: 18510,
    enchant: "Cloak - Greater Resistance",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Chest",
    item: "Truefaith Vestments",
    entry: 14154,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Bindings of Transcendence",
    entry: 16926,
    enchant: "Bracer - Healing Power",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Handguards of Transcendence",
    entry: 16920,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Firemaw's Clutch",
    entry: 19400,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Weapon",
    item: "Benediction",
    entry: 18608,
    enchant: "Weapon - Healing Power",
    source: "Quest Reward",
    detail: "The Balance of Light and Shadow",
  },
  {
    slot: "Ranged",
    item: "Bonecreeper Stylus",
    entry: 13938,
    enchant: null,
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
];

const HOLY_PRIEST_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Zulian Headdress",
    entry: 22720,
    enchant: "Prophetic Aura",
    source: "Zul'Gurub",
    detail: "Multiple Bosses",
  },
  {
    slot: "Neck",
    item: "Jin'do's Evil Eye",
    entry: 19885,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Jin'do the Hexxer",
  },
  {
    slot: "Shoulder",
    item: "Pauldrons of Transcendence",
    entry: 16924,
    enchant: "Zandalar Signet of Serenity",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Back",
    item: "Hide of the Wild",
    entry: 18510,
    enchant: "Cloak - Greater Resistance",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Chest",
    item: "Truefaith Vestments",
    entry: 14154,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Bindings of Transcendence",
    entry: 16926,
    enchant: "Bracer - Healing Power",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Handguards of Transcendence",
    entry: 16920,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Firemaw's Clutch",
    entry: 19400,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Prophetic Aura",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Zandalarian Hero Charm",
    entry: 19950,
    enchant: null,
    source: "Quest Reward",
    detail: "The Heart of Hakkar",
  },
  {
    slot: "Weapon",
    item: "Benediction",
    entry: 18608,
    enchant: "Weapon - Healing Power",
    source: "Quest Reward",
    detail: "The Balance of Light and Shadow",
  },
  {
    slot: "Ranged",
    item: "Touch of Chaos",
    entry: 19861,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
];

const HOLY_PRIEST_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Don Rigoberto's Lost Hat",
    entry: 21615,
    enchant: "Prophetic Aura",
    source: "Ahn'Qiraj",
    detail: "Ouro",
  },
  {
    slot: "Neck",
    item: "Amulet of the Fallen God",
    entry: 21712,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Shoulder",
    item: "Ternary Mantle",
    entry: 21694,
    enchant: "Zandalar Signet of Serenity",
    source: "Ahn'Qiraj",
    detail: "Bug Trio",
  },
  {
    slot: "Back",
    item: "Cloak of Clarity",
    entry: 21583,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Robes of the Guardian Saint",
    entry: 21663,
    enchant: "Chest - Greater Stats",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Wrist",
    item: "Bracelets of Royal Redemption",
    entry: 21604,
    enchant: "Bracer - Healing Power",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Hands",
    item: "Desert Bloom Gloves",
    entry: 20717,
    enchant: "Gloves - Healing Power",
    source: "Quest Reward",
    detail: "Armaments of War",
  },
  {
    slot: "Waist",
    item: "Grasp of the Old God",
    entry: 21582,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Prophetic Aura",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Ring of the Martyr",
    entry: 21620,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Princess Huhuran",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Scarab Brooch",
    entry: 21625,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Weapon",
    item: "Scepter of the False Prophet",
    entry: 21839,
    enchant: "Weapon - Healing Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Off Hand",
    item: "Sartura's Might",
    entry: 21666,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Ranged",
    item: "Wand of Qiraji Nobility",
    entry: 21603,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Lord Kri",
  },
];

const HOLY_PRIEST_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Circlet of Faith",
    entry: 22514,
    enchant: "Prophetic Aura",
    source: "Quest Reward",
    detail: "Circlet of Faith",
  },
  {
    slot: "Neck",
    item: "Amulet of the Fallen God",
    entry: 21712,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Shoulder",
    item: "Shoulderpads of Faith",
    entry: 22515,
    enchant: "Zandalar Signet of Serenity",
    source: "Quest Reward",
    detail: "Shoulderpads of Faith",
  },
  {
    slot: "Back",
    item: "Cloak of Suturing",
    entry: 22960,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Patchwerk",
  },
  {
    slot: "Chest",
    item: "Robe of Faith",
    entry: 22512,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Robe of Faith",
  },
  {
    slot: "Wrist",
    item: "Bindings of Faith",
    entry: 22519,
    enchant: "Bracer - Healing Power",
    source: "Quest Reward",
    detail: "Bindings of Faith",
  },
  {
    slot: "Hands",
    item: "Gloves of Faith",
    entry: 22517,
    enchant: "Gloves - Healing Power",
    source: "Naxxramas",
    detail: "Gloves of Faith",
  },
  {
    slot: "Waist",
    item: "Belt of Faith",
    entry: 22518,
    enchant: null,
    source: "Quest Reward",
    detail: "Belt of Faith",
  },
  {
    slot: "Legs",
    item: "Leggings of Faith",
    entry: 22513,
    enchant: "Prophetic Aura",
    source: "Quest Reward",
    detail: "Leggings of Faith",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Ring of Faith",
    entry: 23061,
    enchant: null,
    source: "Quest Reward",
    detail: "Ring of Faith",
  },
  {
    slot: "Ring 2",
    item: "Band of Unanswered Prayers",
    entry: 22939,
    enchant: null,
    source: "Naxxramas",
    detail: "Anub'Rekhan",
  },
  {
    slot: "Trinket 1",
    item: "Eye of the Dead",
    entry: 23047,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Trinket 2",
    item: "Zandalarian Hero Charm",
    entry: 19950,
    enchant: null,
    source: "Quest Reward",
    detail: "The Heart of Hakkar",
  },
  {
    slot: "Weapon",
    item: "Hammer of the Twisting Nether",
    entry: 23056,
    enchant: "Weapon - Healing Power",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Off Hand",
    item: "Sapphiron's Right Eye",
    entry: 23048,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Ranged",
    item: "Wand of the Whispering Dead",
    entry: 23009,
    enchant: null,
    source: "Naxxramas",
    detail: "Instructor Razuvious",
  },
];

export const HOLY_PRIEST_BIS: BiSSpecData = {
  classSlug: "priest",
  specSlug: "holy",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: HOLY_PRIEST_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: HOLY_PRIEST_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: HOLY_PRIEST_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: HOLY_PRIEST_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: HOLY_PRIEST_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: HOLY_PRIEST_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: HOLY_PRIEST_PHASE_6_GEAR },
  ],
  talentImage: holyPriestTalents,
  classGuide: {
    introduction: "Holy Priests are versatile healers that excel at both single target and AoE healing. They also bring powerful utility in the form of Divine Spirit and Power Infusion if specced for it.",
    rotationNote: "One of the unique things about healing is downranking heals. We mention some specific ranks of certain heals below as a starting point, but finding out which ranks work best will be up to you. The ranks you choose will change based on each boss depending on the situation and length of the encounter, as well your target and how much health they are missing.",
    singleTarget: [
      "Maintain Renew on players taking constant damage.",
      "Cast Flash Heal. This is your spam heal.",
      "Cast Power Word: Shield or Renew on the move.",
      "Cast Greater Heal for huge heals, best combined with Inner Focus when off cooldown.",
      "If you need to start conserving mana, you can start downranking and use spells such as Greater Heal R2 or Greater Heal R4, and Flash Heal R4 .",
    ],
    aoe: [
      "Cast Prayer of Healing, best combined with Inner Focus when off cooldown. Only heals your party.",
      "Cast Renew on targets that will be taking constant damage.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Mageblood Potion (Phase 4)",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup, Sagefish Delight",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Mana Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

const SHADOW_PRIEST_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Dark Advisor's Pendant",
    entry: 18691,
    enchant: null,
    source: "Scholomance",
    detail: "Vectus",
  },
  {
    slot: "Shoulder",
    item: "Felcloth Shoulders",
    entry: 14112,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Robe of Winter Night",
    entry: 14136,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern (285)",
  },
  {
    slot: "Wrist",
    item: "Shadowy Bracers",
    entry: 10461,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward (Tailor Only)",
    detail: "Shadoweaver",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Ban'thok Sash",
    entry: 11662,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Eye of Orgrimmar",
    entry: 12545,
    enchant: null,
    source: "Quest Reward",
    detail: "The Princess Saved?",
  },
  {
    slot: "Ring 2",
    item: "Cyclopean Band",
    entry: 11824,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Trinket 1",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Trinket 2",
    item: "Eye of the Beast",
    entry: 13968,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Scepter of the Unholy",
    entry: 13349,
    enchant: "Weapon - Spell Power",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const SHADOW_PRIEST_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Felcloth Shoulders",
    entry: 14112,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robe of Winter Night",
    entry: 14136,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern (285)",
  },
  {
    slot: "Wrist",
    item: "Shadowy Bracers",
    entry: 10461,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward (Tailor Only)",
    detail: "Shadoweaver",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Sash of Whispered Secrets",
    entry: 18809,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Anathema",
    entry: 18609,
    enchant: "Weapon - Spell Power",
    source: "Quest Reward",
    detail: "The Balance of Light and Shadow",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const SHADOW_PRIEST_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Arcanum of Focus",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Felcloth Shoulders",
    entry: 14112,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Amplifying Cloak",
    entry: 18350,
    enchant: "Cloak - Greater Resistance",
    source: "Dire Maul (West)",
    detail: "Magister Kalendris",
  },
  {
    slot: "Chest",
    item: "Robe of Winter Night",
    entry: 14136,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern (285)",
  },
  {
    slot: "Wrist",
    item: "Sublime Wristguards",
    entry: 18497,
    enchant: "Bracer - Greater Intellect",
    source: "Dire Maul (North)",
    detail: "Guard Mol'dar, Guard Slip'kik",
  },
  {
    slot: "Hands",
    item: "Felcloth Gloves",
    entry: 18407,
    enchant: null,
    source: "Tailoring",
    detail: "BoP Pattern (300)",
  },
  {
    slot: "Waist",
    item: "Sash of Whispered Secrets",
    entry: 18809,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Arcanum of Focus",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Anathema",
    entry: 18609,
    enchant: "Weapon - Spell Power",
    source: "Quest Reward",
    detail: "The Balance of Light and Shadow",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const SHADOW_PRIEST_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Brood Lord",
    entry: 19378,
    enchant: "Cloak - Greater Resistance",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Chest",
    item: "Robe of Winter Night",
    entry: 14136,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern (285)",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Ebony Flame Gloves",
    entry: 19407,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Waist",
    item: "Firemaw's Clutch",
    entry: 19400,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Legs",
    item: "Flarecore Leggings",
    entry: 19165,
    enchant: "Arcanum of Focus",
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Band of Dark Dominion",
    entry: 19434,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Tome of Shadow Force",
    entry: 19309,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const SHADOW_PRIEST_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "The Hexxer's Cover",
    entry: 19886,
    enchant: "Arcanum of Focus",
    source: "Zul'Gurub",
    detail: "Jin'do the Hexxer",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of Consumption",
    entry: 19857,
    enchant: "Cloak - Greater Resistance",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Ebony Flame Gloves",
    entry: 19407,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Waist",
    item: "Firemaw's Clutch",
    entry: 19400,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Legs",
    item: "Flarecore Leggings",
    entry: 19165,
    enchant: "Arcanum of Focus",
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Band of Dark Dominion",
    entry: 19434,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Tome of Shadow Force",
    entry: 19309,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Ranged",
    item: "Touch of Chaos",
    entry: 19861,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
];

const SHADOW_PRIEST_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Spellweaver's Turban",
    entry: 22267,
    enchant: "Arcanum of Focus",
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Devoured",
    entry: 22731,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Robe of Winter Night",
    entry: 14136,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern (285)",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Ebony Flame Gloves",
    entry: 19407,
    enchant: "Gloves - Shadow Power",
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Flarecore Leggings",
    entry: 19165,
    enchant: "Arcanum of Focus",
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Feet",
    item: "Boots of Epiphany",
    entry: 21600,
    enchant: "Boots - Minor Speed",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Band of Dark Dominion",
    entry: 19434,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Tome of Shadow Force",
    entry: 19309,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Ranged",
    item: "Wand of Qiraji Nobility",
    entry: 21603,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Lord Kri",
  },
];

const SHADOW_PRIEST_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Preceptor's Hat",
    entry: 23035,
    enchant: "Arcanum of Focus",
    source: "Naxxramas",
    detail: "Heigan the Unclean",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Rime Covered Mantle",
    entry: 22983,
    enchant: "Zandalar Signet of Mojo",
    source: "Naxxramas",
    detail: "Gluth",
  },
  {
    slot: "Back",
    item: "Cloak of the Devoured",
    entry: 22731,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Crystal Webbed Robe",
    entry: 23220,
    enchant: "Chest - Greater Stats",
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Ebony Flame Gloves",
    entry: 19407,
    enchant: "Gloves - Shadow Power",
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of Polarity",
    entry: 23070,
    enchant: "Arcanum of Focus",
    source: "Naxxramas",
    detail: "Thaddius",
  },
  {
    slot: "Feet",
    item: "Boots of Epiphany",
    entry: 21600,
    enchant: "Boots - Minor Speed",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Band of the Inevitable",
    entry: 23031,
    enchant: null,
    source: "Naxxramas",
    detail: "Noth the Plaguebringer",
  },
  {
    slot: "Trinket 1",
    item: "The Restrained Essence of Sapphiron",
    entry: 23046,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Champion (SP)",
    enchant: null,
    source: "Quest Reward",
    detail: "The Fall of Kel'Thuzad",
  },
  {
    slot: "Weapon",
    item: "The End of Dreams",
    entry: 22988,
    enchant: "Weapon - Spell Power",
    source: "Naxxramas",
    detail: "Grobbulus",
  },
  {
    slot: "Off Hand",
    item: "Sapphiron's Left Eye",
    entry: 23049,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Ranged",
    item: "Wand of Fates",
    entry: 22820,
    enchant: null,
    source: "Naxxramas",
    detail: "Patchwerk",
  },
];

export const SHADOW_PRIEST_BIS: BiSSpecData = {
  classSlug: "priest",
  specSlug: "shadow",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: SHADOW_PRIEST_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: SHADOW_PRIEST_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: SHADOW_PRIEST_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: SHADOW_PRIEST_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: SHADOW_PRIEST_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: SHADOW_PRIEST_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: SHADOW_PRIEST_PHASE_6_GEAR },
  ],
  talentImage: shadowPriestTalents,
  classGuide: {
    introduction: "Every raid will want at least one Shadow Priest because of the utility provided by Shadow Weaving.",
    singleTarget: [
      "Maintain 5 stacks of Shadow Weaving.",
      "Maintain Shadow Word: Pain.",
      "Use Inner Focus with Mind Blast or Devouring Plague if you are an Undead Priest.",
      "Cast Mind Blast.",
      "Cast Mind Flay.",
      "Use Shoot Wand if you are out of mana.",
      "Use Mind Flay R1 if you are low on mana to help maintain Shadow Weaving",
    ],
    aoe: [
      "Maintain Shadow Word: Pain on up to 4 targets.",
      "Follow single target priority.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Flask of Supreme Power",
      alternatives: "Flask of Distilled Wisdom, Elixir of Shadow Power",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Wizard Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

export const PRIEST_BIS_SPECS: BiSSpecData[] = [HOLY_PRIEST_BIS, SHADOW_PRIEST_BIS];
