import {
  faFlask,
  faBreadSlice,
  faHammer,
  faDice,
} from "@fortawesome/free-solid-svg-icons";
import type { BiSGearEntry, BiSSpecData } from "../types";
import combatRogueTalents from "../assets/BiS Talents/Rogue - Combat.png";

const COMBAT_ROGUE_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mask of the Unforgiven",
    entry: 13404,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Live)",
    detail: "The Unforgiven",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Cadaverous Armor",
    entry: 14637,
    enchant: "Chest - Greater Stats",
    source: "Scholomance",
    detail: "Lord Alex Barov",
  },
  {
    slot: "Wrist",
    item: "Shadowcraft Bracers",
    entry: 16710,
    enchant: "Bracer - Superior Strength",
    source: "Scholomance",
    detail: "Instructor Malicia",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Agility",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Cloudrunner Girdle",
    entry: 13252,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Swiftwalker Boots",
    entry: 12553,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Ring 1",
    item: "Painweaver Band",
    entry: 13098,
    enchant: null,
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath",
  },
  {
    slot: "Ring 2",
    item: "Blackstone Ring",
    entry: 17713,
    enchant: null,
    source: "Maraudon",
    detail: "Princess Theradras",
  },
  {
    slot: "Trinket 1",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Dal'Rend's Sacred Charge",
    entry: 12940,
    enchant: "Weapon - Crusader",
    source: "Blackrock Spire (Upper)",
    detail: "Warchief Rend Blackhand",
  },
  {
    slot: "Off Hand",
    item: "Dal'Rend's Tribal Guardian",
    entry: 12939,
    enchant: "Weapon - Crusader",
    source: "Blackrock Spire (Upper)",
    detail: "Warchief Rend Blackhand",
  },
  {
    slot: "Ranged",
    item: "Blackcrow",
    entry: 12651,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Shadow Hunter Vosh'gajin",
  },
];

const COMBAT_ROGUE_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Bloodfang Hood",
    entry: 16908,
    enchant: "Lesser Arcanum of Voracity",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Nightslayer Shoulder Pads",
    entry: 16823,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Sulfuron Harbinger",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Nightslayer Chestpiece",
    entry: 16820,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Wrist",
    item: "Nightslayer Bracelets",
    entry: 16825,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Nightslayer Gloves",
    entry: 16826,
    enchant: "Gloves - Greater Agility",
    source: "Molten Core",
    detail: "Gehennas",
  },
  {
    slot: "Waist",
    item: "Nightslayer Belt",
    entry: 16827,
    enchant: null,
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Legs",
    item: "Bloodfang Pants",
    entry: 16909,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Nightslayer Boots",
    entry: 16824,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Shazzrah",
  },
  {
    slot: "Ring 1",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Vis'kag the Bloodletter",
    entry: 17075,
    enchant: "Weapon - Crusader",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Off Hand",
    item: "Brutality Blade",
    entry: 18832,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Ranged",
    item: "Striker's Mark",
    entry: 17069,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar",
  },
];

const COMBAT_ROGUE_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Bloodfang Hood",
    entry: 16908,
    enchant: "Lesser Arcanum of Voracity",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Nightslayer Shoulder Pads",
    entry: 16823,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Sulfuron Harbinger",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Nightslayer Chestpiece",
    entry: 16820,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Wrist",
    item: "Forest Stalker's Bracers",
    entry: 19587,
    enchant: "Bracer - Superior Strength",
    source: "Reputation",
    detail: "Warsong Outriders, Silverwing Sentinels - Exalted",
  },
  {
    slot: "Hands",
    item: "Nightslayer Gloves",
    entry: 16826,
    enchant: "Gloves - Greater Agility",
    source: "Molten Core",
    detail: "Gehennas",
  },
  {
    slot: "Waist",
    item: "Nightslayer Belt",
    entry: 16827,
    enchant: null,
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Legs",
    item: "Bloodfang Pants",
    entry: 16909,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Nightslayer Boots",
    entry: 16824,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Shazzrah",
  },
  {
    slot: "Ring 1",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 2",
    item: "Don Julio's Band",
    entry: 19325,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Trinket 1",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Vis'kag the Bloodletter",
    entry: 17075,
    enchant: "Weapon - Crusader",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Off Hand",
    item: "Brutality Blade",
    entry: 18832,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Ranged",
    item: "Striker's Mark",
    entry: 17069,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar",
  },
];

const COMBAT_ROGUE_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Bloodfang Hood",
    entry: 16908,
    enchant: "Lesser Arcanum of Voracity",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Bloodfang Spaulders",
    entry: 16832,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Back",
    item: "Cloak of Firemaw",
    entry: 19398,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Chest",
    item: "Bloodfang Chestpiece",
    entry: 16905,
    enchant: "Chest - Greater Stats",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Wrist",
    item: "Bloodfang Bracers",
    entry: 16911,
    enchant: "Bracer - Superior Strength",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Bloodfang Gloves",
    entry: 16907,
    enchant: "Gloves - Greater Agility",
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Bloodfang Belt",
    entry: 16910,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Legs",
    item: "Bloodfang Pants",
    entry: 16909,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Bloodfang Boots",
    entry: 16906,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Ring 1",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 2",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Chromatically Tempered Sword",
    entry: 19352,
    enchant: "Weapon - Crusader",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Off Hand",
    item: "Maladath, Runed Blade of the Black Flight",
    entry: 19351,
    enchant: "Weapon - Crusader",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Ranged",
    item: "Striker's Mark",
    entry: 17069,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar",
  },
];

const COMBAT_ROGUE_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Darkmantle Cap",
    entry: 22005,
    enchant: "Death's Embrace",
    source: "Quest Reward",
    detail: "Saving the Best for Last",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Zandalar Madcap's Mantle",
    entry: 19835,
    enchant: "Zandalar Signet of Might",
    source: "Quest Reward",
    detail: "Paragons of Power: The Madcap's Mantle",
  },
  {
    slot: "Back",
    item: "Cloak of Firemaw",
    entry: 19398,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Chest",
    item: "Darkmantle Tunic",
    entry: 22009,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Saving the Best for Last",
  },
  {
    slot: "Wrist",
    item: "Bloodfang Bracers",
    entry: 16911,
    enchant: "Bracer - Superior Strength",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Darkmantle Gloves",
    entry: 22006,
    enchant: "Gloves - Greater Agility",
    source: "Quest Reward",
    detail: "Just Compensation",
  },
  {
    slot: "Waist",
    item: "Bloodfang Belt",
    entry: 16910,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Legs",
    item: "Bloodfang Pants",
    entry: 16909,
    enchant: "Death's Embrace",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Darkmantle Boots",
    entry: 22003,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Anthion's Parting Words",
  },
  {
    slot: "Ring 1",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 2",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Renataki's Charm of Trickery",
    entry: 19954,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Crafted (Multiple Bosses)",
  },
  {
    slot: "Weapon",
    item: "Chromatically Tempered Sword",
    entry: 19352,
    enchant: "Weapon - Crusader",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Off Hand",
    item: "Maladath, Runed Blade of the Black Flight",
    entry: 19351,
    enchant: "Weapon - Crusader",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Ranged",
    item: "Striker's Mark",
    entry: 17069,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar",
  },
];

const COMBAT_ROGUE_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Deathdealer's Helm",
    entry: 21360,
    enchant: "Death's Embrace",
    source: "Quest Reward",
    detail: "Deathdealer's Helm",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Deathdealer's Spaulders",
    entry: 21361,
    enchant: "Zandalar Signet of Might",
    source: "Quest Reward",
    detail: "Deathdealer's Spaulders",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Deathdealer's Vest",
    entry: 21364,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Deathdealer's Vest",
  },
  {
    slot: "Wrist",
    item: "Qiraji Execution Bracers",
    entry: 21602,
    enchant: "Bracer - Superior Strength",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Hands",
    item: "Gloves of Enforcement",
    entry: 21672,
    enchant: "Gloves - Superior Agility",
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Waist",
    item: "Belt of Never-ending Agony",
    entry: 21586,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Deathdealer's Leggings",
    entry: 21362,
    enchant: "Death's Embrace",
    source: "Quest Reward",
    detail: "Deathdealer's Leggings",
  },
  {
    slot: "Feet",
    item: "Deathdealer's Boots",
    entry: 21359,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Deathdealer's Boots",
  },
  {
    slot: "Ring 1",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Ring 2",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Jom Gabbar",
    entry: 23570,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Ouro",
  },
  {
    slot: "Weapon",
    item: "Ancient Qiraji Ripper",
    entry: 21650,
    enchant: "Weapon - Crusader",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Off Hand",
    item: "Maladath, Runed Blade of the Black Flight",
    entry: 19351,
    enchant: "Weapon - Crusader",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Ranged",
    item: "Larvae of the Great Worm",
    entry: 23557,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Ouro",
  },
];

const COMBAT_ROGUE_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Bonescythe Helmet",
    entry: 22478,
    enchant: "Death's Embrace",
    source: "Quest Reward",
    detail: "Bonescythe Helmet",
  },
  {
    slot: "Neck",
    item: "Prestor's Talisman of Connivery",
    entry: 19377,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Shoulder",
    item: "Bonescythe Pauldrons",
    entry: 22479,
    enchant: "Might of the Scourge",
    source: "Quest Reward",
    detail: "Bonescythe Pauldrons",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Bonescythe Breastplate",
    entry: 22476,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Bonescythe Breastplate",
  },
  {
    slot: "Wrist",
    item: "Bonescythe Bracers",
    entry: 22483,
    enchant: "Bracer - Superior Strength",
    source: "Quest Reward",
    detail: "Bonescythe Bracers",
  },
  {
    slot: "Hands",
    item: "Bonescythe Gauntlets",
    entry: 22481,
    enchant: "Gloves - Superior Agility",
    source: "Quest Reward",
    detail: "Bonescythe Gauntlets",
  },
  {
    slot: "Waist",
    item: "Bonescythe Waistguard",
    entry: 22482,
    enchant: null,
    source: "Quest Reward",
    detail: "Bonescythe Waistguard",
  },
  {
    slot: "Legs",
    item: "Bonescythe Legplates",
    entry: 22477,
    enchant: "Death's Embrace",
    source: "Quest Reward",
    detail: "Bonescythe Legplates",
  },
  {
    slot: "Feet",
    item: "Bonescythe Sabatons",
    entry: 22480,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Bonescythe Sabatons",
  },
  {
    slot: "Ring 1",
    item: "Band of Unnatural Forces",
    entry: 23038,
    enchant: null,
    source: "Naxxramas",
    detail: "Loatheb",
  },
  {
    slot: "Ring 2",
    item: "Bonescythe Ring",
    entry: 23060,
    enchant: null,
    source: "Quest Reward",
    detail: "Bonescythe Ring",
  },
  {
    slot: "Trinket 1",
    item: "Kiss of the Spider",
    entry: 22954,
    enchant: null,
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Champion-v2",
    enchant: null,
    source: "Quest Reward",
    detail: "The Fall of Kel'Thuzad",
  },
  {
    slot: "Weapon",
    item: "Gressil, Dawn of Ruin",
    entry: 23054,
    enchant: "Weapon - Crusader",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Off Hand",
    item: "The Hungering Cold",
    entry: 23577,
    enchant: "Weapon - Crusader",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Ranged",
    item: "Striker's Mark",
    entry: 17069,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar",
  },
];

export const COMBAT_ROGUE_BIS: BiSSpecData = {
  classSlug: "rogue",
  specSlug: "combat",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: COMBAT_ROGUE_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: COMBAT_ROGUE_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: COMBAT_ROGUE_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: COMBAT_ROGUE_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: COMBAT_ROGUE_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: COMBAT_ROGUE_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: COMBAT_ROGUE_PHASE_6_GEAR },
  ],
  talentImage: combatRogueTalents,
  classGuide: {
    introduction: "Combat is the go-to spec for Rogues during all of Classic. There are two different variations the spec based on if you are using Swords or Daggers, but they both play virtually the same.",
    singleTarget: [
      "Maintain Slice and Dice.",
      "Use Blade Flurry and Adrenaline Rush when available.",
      "Use Eviscerate when you have excess combo points and Slice and Dice doesn't need to be refreshed.",
      "Use Ambush while stealthed if you are using Daggers Build.",
      "Use Sinister Strike (Swords) or Backstab (Daggers) to generate combo points.",
    ],
    aoe: [
      "Use Blade Flurry.",
      "Perform single target rotation.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Elixir of the Mongoose",
      alternatives: "Elixir of Greater Agility",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Grilled Squid",
      note: "undefined",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Windfury Weapon, Deadly Poison",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Thistle Tea, Juju Might, Juju Power, Ground Scorpok Assay, R.O.I.D.S.",
    },
  ],
};

export const ROGUE_BIS_SPECS: BiSSpecData[] = [COMBAT_ROGUE_BIS];
