import {
  faFlask,
  faBreadSlice,
  faVial,
  faHammer,
  faDice,
} from "@fortawesome/free-solid-svg-icons";
import type { BiSGearEntry, BiSSpecData } from "../types";
import elementalShamanTalents from "../assets/BiS Talents/Shaman - Elemental.png";
import enhancementShamanTalents from "../assets/BiS Talents/Shaman - Enhancement.png";
import restorationShamanTalents from "../assets/BiS Talents/Shaman - Resto.png";

const ELEMENTAL_SHAMAN_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Diana's Pearl Necklace",
    entry: 22403,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Cannon Master Willey",
  },
  {
    slot: "Shoulder",
    item: "Burial Shawl",
    entry: 18681,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Scholomance",
    detail: "Lord Alexei Barov",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Wildthorn Mail",
    entry: 12624,
    enchant: "Chest - Greater Stats",
    source: "Blacksmithing",
    detail: "BoE Pattern (270)",
  },
  {
    slot: "Wrist",
    item: "Manacle Cuffs",
    entry: 11962,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "The Love Potion",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Ban'thok Sash",
    entry: 11662,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Eye of Orgrimmar",
    entry: 12545,
    enchant: null,
    source: "Quest Reward",
    detail: "The Princess Saved?",
  },
  {
    slot: "Ring 2",
    item: "Cyclopean Band",
    entry: 11824,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Trinket 1",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Trinket 2",
    item: "Eye of the Beast",
    entry: 13968,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Witchblade",
    entry: 13964,
    enchant: "Weapon - Spell Power",
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
];

const ELEMENTAL_SHAMAN_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Deep Earth Spaulders",
    entry: 18829,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Manacle Cuffs",
    entry: 11962,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "The Love Potion",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Legplates of Ten Storms",
    entry: 16946,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Staff of Dominance",
    entry: 18842,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
];

const ELEMENTAL_SHAMAN_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Arcanum of Focus",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Deep Earth Spaulders",
    entry: 18829,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Back",
    item: "Amplifying Cloak",
    entry: 18350,
    enchant: "Cloak - Greater Resistance",
    source: "Dire Maul (West)",
    detail: "Magister Kalendris",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Sublime Wristguards",
    entry: 18497,
    enchant: "Bracer - Greater Intellect",
    source: "Dire Maul (North)",
    detail: "Guard Mol'dar, Guard Slip'kik",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Legplates of Ten Storms",
    entry: 16946,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Waterspout Boots",
    entry: 18322,
    enchant: "Boots - Minor Speed",
    source: "Dire Maul (East)",
    detail: "Hydrospawn",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Aurastone Hammer",
    entry: 17105,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Therazane's Touch",
    entry: 19315,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const ELEMENTAL_SHAMAN_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Deep Earth Spaulders",
    entry: 18829,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Back",
    item: "Cloak of the Brood Lord",
    entry: 19378,
    enchant: "Cloak - Greater Resistance",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Firemaw's Clutch",
    entry: 19400,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Legs",
    item: "Flarecore Leggings",
    entry: 19165,
    enchant: "Arcanum of Focus",
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Feet",
    item: "Waterspout Boots",
    entry: 18322,
    enchant: "Boots - Minor Speed",
    source: "Dire Maul (East)",
    detail: "Hydrospawn",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Natural Alignment Crystal",
    entry: 19344,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Therazane's Touch",
    entry: 19315,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const ELEMENTAL_SHAMAN_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Deep Earth Spaulders",
    entry: 18829,
    enchant: "Zandalar Signet of Mojo",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Back",
    item: "Cloak of Consumption",
    entry: 19857,
    enchant: "Cloak - Greater Resistance",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Bloodtinged Gloves",
    entry: 19929,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Jin'do the Hexxer",
  },
  {
    slot: "Waist",
    item: "Firemaw's Clutch",
    entry: 19400,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Natural Alignment Crystal",
    entry: 19344,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Jin'do's Bag of Whammies",
    entry: 19891,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Jin'do the Hexxer",
  },
];

const ELEMENTAL_SHAMAN_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Amulet of Vek'nilash",
    entry: 21608,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Shoulder",
    item: "Deep Earth Spaulders",
    entry: 18829,
    enchant: "Zandalar Signet of Mojo",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Back",
    item: "Cloak of the Devoured",
    entry: 22731,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Stormcaller's Hauberk",
    entry: 21374,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Stormcaller's Hauberk",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: "Gloves - Fire Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Stormcaller's Leggings",
    entry: 21375,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Quest Reward",
    detail: "Stormcaller's Leggings",
  },
  {
    slot: "Feet",
    item: "Stormcaller's Footguards",
    entry: 21373,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Stormcaller's Footguards",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Natural Alignment Crystal",
    entry: 19344,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Royal Scepter of Vek'lor",
    entry: 21597,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Relic",
    item: "Totem of the Storm",
    entry: 23199,
    enchant: null,
    source: "Auction House",
    detail: "World Drop",
  },
];

const ELEMENTAL_SHAMAN_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Preceptor's Hat",
    entry: 23035,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Naxxramas",
    detail: "Heigan the Unclean",
  },
  {
    slot: "Neck",
    item: "Amulet of Vek'nilash",
    entry: 21608,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Shoulder",
    item: "Pauldrons of Elemental Fury",
    entry: 23664,
    enchant: "Power of the Scourge",
    source: "Naxxramas",
    detail: "Trash Drop",
  },
  {
    slot: "Back",
    item: "Cloak of the Necropolis",
    entry: 23050,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Chest",
    item: "Crystal Webbed Robe",
    entry: 23220,
    enchant: "Chest - Greater Stats",
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Wrist",
    item: "The Soul Harvester's Bindings",
    entry: 23021,
    enchant: "Bracer - Greater Intellect",
    source: "Naxxramas",
    detail: "Gothik the Harvester",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: "Gloves - Fire Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of Polarity",
    entry: 23070,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Naxxramas",
    detail: "Thaddius",
  },
  {
    slot: "Feet",
    item: "Boots of Epiphany",
    entry: 21600,
    enchant: "Boots - Minor Speed",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Band of the Inevitable",
    entry: 23031,
    enchant: null,
    source: "Naxxramas",
    detail: "Noth the Plaguebringer",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "The Restrained Essence of Sapphiron",
    entry: 23046,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Weapon",
    item: "Brimstone Staff",
    entry: 22800,
    enchant: "Weapon - Spell Power",
    source: "Naxxramas",
    detail: "Loatheb",
  },
  {
    slot: "Relic",
    item: "Totem of the Storm",
    entry: 23199,
    enchant: null,
    source: "Auction House",
    detail: "World Drop",
  },
];

export const ELEMENTAL_SHAMAN_BIS: BiSSpecData = {
  classSlug: "shaman",
  specSlug: "elemental",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: ELEMENTAL_SHAMAN_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: ELEMENTAL_SHAMAN_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: ELEMENTAL_SHAMAN_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: ELEMENTAL_SHAMAN_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: ELEMENTAL_SHAMAN_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: ELEMENTAL_SHAMAN_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: ELEMENTAL_SHAMAN_PHASE_6_GEAR },
  ],
  talentImage: elementalShamanTalents,
  classGuide: {
    introduction: "Elemental Shamans bring great burst damage, along with amazing utilty for every situation with their Totems. They run out of mana very quickly so you might need to downrank spells during some fights.",
    rotationNote: "If you find yourself going OOM, you can remove Chain Lightning completely from your rotation or you can start downranking to Chain Lightning R1 and Lightning Bolt R4 to help make it through fights.",
    singleTarget: [
      "Maintain Searing Totem and Mana Spring Totem and your assigned Earth and Air Totems.",
      "Use Elemental Mastery with Chain Lightning.",
      "Cast Chain Lightning.",
      "Cast Lightning Bolt.",
      "Cast Flame Shock while moving.",
      "Cast Earth Shock if the target will die before your next Lightning Bolt cast finishes.",
    ],
    aoe: [
      "Use Fire Nova Totem.",
      "Cast Chain Lightning.",
      "Use Magma Totem after Fire Nova Totem explodes.",
      "Cast Lightning Bolt.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Flask of Supreme Power",
      alternatives: "Greater Arcane Elixir",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Wizard Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

const ENHANCEMENT_SHAMAN_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Eye of Rend",
    entry: 12587,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Warchief Rend Blackhand",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Bracers of the Stone Princess",
    entry: 17714,
    enchant: "Bracer - Superior Strength",
    source: "Maraudon",
    detail: "Princess Theradras",
  },
  {
    slot: "Hands",
    item: "Gargoyle Slashers",
    entry: 13957,
    enchant: "Gloves - Minor Haste",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Waist",
    item: "Cloudrunner Girdle",
    entry: 13252,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Pads of the Dread Wolf",
    entry: 13210,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Spire (Lower)",
    detail: "Halycon",
  },
  {
    slot: "Ring 1",
    item: "Painweaver Band",
    entry: 13098,
    enchant: null,
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath",
  },
  {
    slot: "Ring 2",
    item: "Blackstone Ring",
    entry: 17713,
    enchant: null,
    source: "Maraudon",
    detail: "Princess Theradras",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Arcanite Reaper",
    entry: 12784,
    enchant: "Weapon - Crusader",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
];

const ENHANCEMENT_SHAMAN_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crown of Destruction",
    entry: 18817,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Black Dragonscale Shoulders",
    entry: 15051,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Gargoyle Slashers",
    entry: 13957,
    enchant: "Gloves - Minor Haste",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Waist",
    item: "Cloudrunner Girdle",
    entry: 13252,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Pads of the Dread Wolf",
    entry: 13210,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Spire (Lower)",
    detail: "Halycon",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Sulfuras, Hand of Ragnaros",
    entry: 17182,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Crafted",
  },
];

const ENHANCEMENT_SHAMAN_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crown of Destruction",
    entry: 18817,
    enchant: "Arcanum of Rapidity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Black Dragonscale Shoulders",
    entry: 15051,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Minor Haste",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Cloudrunner Girdle",
    entry: 13252,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Arcanum of Rapidity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Pads of the Dread Wolf",
    entry: 13210,
    enchant: "Boots - Minor Speed",
    source: "Blackrock Spire (Lower)",
    detail: "Halycon",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Don Julio's Band",
    entry: 19325,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Sulfuras, Hand of Ragnaros",
    entry: 17182,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Crafted",
  },
];

const ENHANCEMENT_SHAMAN_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crown of Destruction",
    entry: 18817,
    enchant: "Arcanum of Rapidity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Taut Dragonhide Shoulderpads",
    entry: 19389,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Back",
    item: "Cloak of Draconic Might",
    entry: 19436,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Chromatic Gauntlets",
    entry: 19157,
    enchant: "Gloves - Minor Haste",
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Waist",
    item: "Therazane's Link",
    entry: 19380,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Arcanum of Rapidity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Boots of the Shadow Flame",
    entry: 19381,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 1",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Sulfuras, Hand of Ragnaros",
    entry: 17182,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Crafted",
  },
];

const ENHANCEMENT_SHAMAN_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crown of Destruction",
    entry: 18817,
    enchant: "Arcanum of Rapidity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Neck",
    item: "The Eye of Hakkar",
    entry: 19856,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Shoulder",
    item: "Taut Dragonhide Shoulderpads",
    entry: 19389,
    enchant: "Zandalar Signet of Might",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Back",
    item: "Cloak of Draconic Might",
    entry: 19436,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Chromatic Gauntlets",
    entry: 19157,
    enchant: "Gloves - Minor Haste",
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Waist",
    item: "Therazane's Link",
    entry: 19380,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Arcanum of Rapidity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Boots of the Shadow Flame",
    entry: 19381,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 1",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Sulfuras, Hand of Ragnaros",
    entry: 17182,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Crafted",
  },
];

const ENHANCEMENT_SHAMAN_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crown of Destruction",
    entry: 18817,
    enchant: "Arcanum of Rapidity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Neck",
    item: "Barbed Choker",
    entry: 21664,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Shoulder",
    item: "Mantle of Wicked Revenge",
    entry: 21665,
    enchant: "Zandalar Signet of Might",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Qiraji Execution Bracers",
    entry: 21602,
    enchant: "Bracer - Superior Strength",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Hands",
    item: "Gloves of Enforcement",
    entry: 21672,
    enchant: "Gloves - Minor Haste",
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Waist",
    item: "Belt of Never-ending Agony",
    entry: 21586,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Scaled Sand Reaver Leggings",
    entry: 21651,
    enchant: "Arcanum of Rapidity",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Feet",
    item: "Boots of the Vanguard",
    entry: 21493,
    enchant: "Boots - Minor Speed",
    source: "Ruins of Ahn'Qiraj",
    detail: "General Rajaxx",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Qiraji Fury",
    entry: 21677,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Jom Gabbar",
    entry: 23570,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Ouro",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Dark Edge of Insanity",
    entry: 21134,
    enchant: "Weapon - Crusader",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Relic",
    item: "Totem of Rage",
    entry: 22395,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Magmus",
  },
];

const ENHANCEMENT_SHAMAN_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crown of Destruction",
    entry: 18817,
    enchant: "Arcanum of Rapidity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Neck",
    item: "Stormrage's Talisman of Seething",
    entry: 23053,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Mantle of Wicked Revenge",
    entry: 21665,
    enchant: "Might of the Scourge",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Back",
    item: "Shroud of Dominion",
    entry: 23045,
    enchant: "Cloak - Lesser Agility",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Chest",
    item: "Ghoul Skin Tunic",
    entry: 23226,
    enchant: "Chest - Greater Stats",
    source: "Naxxramas",
    detail: "Trash Drop",
  },
  {
    slot: "Wrist",
    item: "Qiraji Execution Bracers",
    entry: 21602,
    enchant: "Bracer - Superior Strength",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Hands",
    item: "Gloves of Enforcement",
    entry: 21672,
    enchant: "Gloves - Minor Haste",
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Waist",
    item: "Belt of Never-ending Agony",
    entry: 21586,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of Apocalypse",
    entry: 23071,
    enchant: "Arcanum of Rapidity",
    source: "Naxxramas",
    detail: "The Four Horsemen",
  },
  {
    slot: "Feet",
    item: "Boots of the Shadow Flame",
    entry: 19381,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 1",
    item: "Band of Unnatural Forces",
    entry: 23038,
    enchant: null,
    source: "Naxxramas",
    detail: "Loatheb",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Kiss of the Spider",
    entry: 22954,
    enchant: null,
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Champion-v2",
    enchant: null,
    source: "Quest Reward",
    detail: "The Fall of Kel'Thuzad",
  },
  {
    slot: "Weapon",
    item: "Might of Menethil",
    entry: 22798,
    enchant: "Weapon - Crusader",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Relic",
    item: "Totem of Rage",
    entry: 22395,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Magmus",
  },
];

export const ENHANCEMENT_SHAMAN_BIS: BiSSpecData = {
  classSlug: "shaman",
  specSlug: "enhancement",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: ENHANCEMENT_SHAMAN_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: ENHANCEMENT_SHAMAN_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: ENHANCEMENT_SHAMAN_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: ENHANCEMENT_SHAMAN_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: ENHANCEMENT_SHAMAN_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: ENHANCEMENT_SHAMAN_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: ENHANCEMENT_SHAMAN_PHASE_6_GEAR },
  ],
  talentImage: enhancementShamanTalents,
  classGuide: {
    introduction: "Enhancement Shaman are a great addition to any raid because of their improved melee totems. Totem Twisting (details below) will be essential to making the most out of your supportive role.",
    singleTarget: [
      "Use Windfury Weapon on both of your weapons.",
      "Maintain Strength of Earth Totem, Mana Spring Totem, and Searing Totem.",
      "If you are Totem Twisting, maintain Windfury Totem and Grace of Air Totem (details below). Otherwise, just mantain Grace of Air Totem.",
      "Cast Stormstrike.",
      "Cast Flame Shock or Earth Shock. If the target has the Flame Shock DoT, prioritize Earth Shock.",
    ],
    aoe: [
      "Use Fire Nova Totem.",
      "Use Magma Totem after Fire Nova Totem explodes.",
      "Maintain Flame Shock on 2 targets.",
      "Perform single target rotation.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Elixir of the Mongoose",
      alternatives: "Elixir of Greater Agility",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Grilled Squid",
      note: "undefined",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Windfury Weapon x2",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Juju Might, Juju Power, Ground Scorpok Assay, R.O.I.D.S., Cerebral Cortex Compound",
    },
  ],
};

const RESTORATION_SHAMAN_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Tribal War Feathers",
    entry: 12960,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Gyth",
  },
  {
    slot: "Neck",
    item: "Animated Chain Necklace",
    entry: 18723,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Ramstein the Gorger",
  },
  {
    slot: "Shoulder",
    item: "Living Shoulders",
    entry: 15061,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Leatherworking",
    detail: "BoE Pattern (270)",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Loomguard Armbraces",
    entry: 13969,
    enchant: "Bracer - Greater Intellect",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Hands",
    item: "Hands of the Exalted Herald",
    entry: 12554,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Waist",
    item: "Crystallized Girdle",
    entry: 12606,
    enchant: null,
    source: "Blackrock Spire (Upper)",
    detail: "Solakar Flamewreath",
  },
  {
    slot: "Legs",
    item: "Ghoul Skin Leggings",
    entry: 18682,
    enchant: "Lesser Arcanum of Voracity",
    source: "Scholomance",
    detail: "Lord Alex Barov",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Rosewine Circle",
    entry: 13178,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Urok Doomhowl",
  },
  {
    slot: "Ring 2",
    item: "Fordring's Seal",
    entry: 16058,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Trinket 1",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Trinket 2",
    item: "Second Wind",
    entry: 11819,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Golem Lord Argelmach",
  },
  {
    slot: "Weapon",
    item: "The Hammer of Grace",
    entry: 11923,
    enchant: "Weapon - Healing Power",
    source: "Blackrock Depths",
    detail: "Chest of the Seven",
  },
  {
    slot: "Off Hand",
    item: "Thaurissan's Royal Scepter",
    entry: 11928,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
];

const RESTORATION_SHAMAN_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Helm of the Lifegiver",
    entry: 18870,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Loomguard Armbraces",
    entry: 13969,
    enchant: "Bracer - Greater Intellect",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Hands",
    item: "Hands of the Exalted Herald",
    entry: 12554,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Princess Moira Bronzebeard",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Salamander Scale Pants",
    entry: 18875,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Aurastone Hammer",
    entry: 17105,
    enchant: "Weapon - Healing Power",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Thaurissan's Royal Scepter",
    entry: 11928,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
];

const RESTORATION_SHAMAN_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Helm of the Lifegiver",
    entry: 18870,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Hide of the Wild",
    entry: 18510,
    enchant: "Cloak - Greater Resistance",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Loomguard Armbraces",
    entry: 13969,
    enchant: "Bracer - Greater Intellect",
    source: "Scholomance",
    detail: "Kirtonos the Herald",
  },
  {
    slot: "Hands",
    item: "Harmonious Gauntlets",
    entry: 18527,
    enchant: null,
    source: "Dire Maul (North)",
    detail: "King Gordok",
  },
  {
    slot: "Waist",
    item: "Eyestalk Cord",
    entry: 18391,
    enchant: null,
    source: "Dire Maul (West)",
    detail: "Immol'thar",
  },
  {
    slot: "Legs",
    item: "Salamander Scale Pants",
    entry: 18875,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Feet",
    item: "Verdant Footpads",
    entry: 13954,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Ring 1",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Aurastone Hammer",
    entry: 17105,
    enchant: "Weapon - Healing Power",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Lei of the Lifegiver",
    entry: 19312,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const RESTORATION_SHAMAN_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Helmet of Ten Storms",
    entry: 16947,
    enchant: "Arcanum of Focus",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Shroud of Pure Thought",
    entry: 19430,
    enchant: "Cloak - Greater Resistance",
    source: "Blackwing Lair",
    detail: "Flamegor",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Bracers of Ten Storms",
    entry: 16943,
    enchant: "Bracer - Healing Power",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Ten Storms",
    entry: 16948,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Corehound Belt",
    entry: 19162,
    enchant: null,
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Natural Alignment Crystal",
    entry: 19344,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Healing Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Lei of the Lifegiver",
    entry: 19312,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const RESTORATION_SHAMAN_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Helmet of Ten Storms",
    entry: 16947,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Jin'do's Evil Eye",
    entry: 19885,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Jin'do the Hexxer",
  },
  {
    slot: "Shoulder",
    item: "Wild Growth Spaulders",
    entry: 18810,
    enchant: "Zandalar Signet of Serenity",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Back",
    item: "Shroud of Pure Thought",
    entry: 19430,
    enchant: "Cloak - Greater Resistance",
    source: "Blackwing Lair",
    detail: "Flamegor",
  },
  {
    slot: "Chest",
    item: "Robes of the Exalted",
    entry: 13346,
    enchant: "Chest - Greater Stats",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Wrist",
    item: "Bracers of Ten Storms",
    entry: 16943,
    enchant: "Bracer - Healing Power",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Ten Storms",
    entry: 16948,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Corehound Belt",
    entry: 19162,
    enchant: null,
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Legs",
    item: "Empowered Leggings",
    entry: 19385,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Feet",
    item: "Boots of Pure Thought",
    entry: 19437,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Cauterizing Band",
    entry: 19140,
    enchant: null,
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Natural Alignment Crystal",
    entry: 19344,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Weapon",
    item: "Lok'amir il Romathis",
    entry: 19360,
    enchant: "Weapon - Healing Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Lei of the Lifegiver",
    entry: 19312,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
];

const RESTORATION_SHAMAN_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Stormcaller's Diadem",
    entry: 21372,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Quest Reward",
    detail: "Stormcaller's Diadem",
  },
  {
    slot: "Neck",
    item: "Amulet of the Fallen God",
    entry: 21712,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Shoulder",
    item: "Stormcaller's Pauldrons",
    entry: 21376,
    enchant: "Zandalar Signet of Serenity",
    source: "Quest Reward",
    detail: "Stormcaller's Pauldrons",
  },
  {
    slot: "Back",
    item: "Cloak of Clarity",
    entry: 21583,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Stormcaller's Hauberk",
    entry: 21374,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Stormcaller's Hauberk",
  },
  {
    slot: "Wrist",
    item: "Bracers of Ten Storms",
    entry: 16943,
    enchant: "Bracer - Healing Power",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Ten Storms",
    entry: 16948,
    enchant: "Gloves - Healing Power",
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Belt of Ten Storms",
    entry: 16944,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Legs",
    item: "Stormcaller's Leggings",
    entry: 21375,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Quest Reward",
    detail: "Stormcaller's Leggings",
  },
  {
    slot: "Feet",
    item: "Stormcaller's Footguards",
    entry: 21373,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Stormcaller's Footguards",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Martyr",
    entry: 21620,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Princess Huhuran",
  },
  {
    slot: "Ring 2",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 1",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Trinket 2",
    item: "Scarab Brooch",
    entry: 21625,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Weapon",
    item: "Scepter of the False Prophet",
    entry: 21839,
    enchant: "Weapon - Healing Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Off Hand",
    item: "Sartura's Might",
    entry: 21666,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Battleguard Sartura",
  },
  {
    slot: "Relic",
    item: "Totem of Sustaining",
    entry: 23200,
    enchant: null,
    source: "Scholomance",
    detail: "Multiple Bosses",
  },
];

const RESTORATION_SHAMAN_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Stormcaller's Diadem",
    entry: 21372,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Quest Reward",
    detail: "Stormcaller's Diadem",
  },
  {
    slot: "Neck",
    item: "Amulet of the Fallen God",
    entry: 21712,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Shoulder",
    item: "Stormcaller's Pauldrons",
    entry: 21376,
    enchant: "Zandalar Signet of Serenity",
    source: "Quest Reward",
    detail: "Stormcaller's Pauldrons",
  },
  {
    slot: "Back",
    item: "Cloak of Suturing",
    entry: 22960,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Patchwerk",
  },
  {
    slot: "Chest",
    item: "Stormcaller's Hauberk",
    entry: 21374,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Stormcaller's Hauberk",
  },
  {
    slot: "Wrist",
    item: "Bracers of Ten Storms",
    entry: 16943,
    enchant: "Bracer - Healing Power",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Ten Storms",
    entry: 16948,
    enchant: "Gloves - Healing Power",
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Waist",
    item: "Belt of Ten Storms",
    entry: 16944,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Legs",
    item: "Stormcaller's Leggings",
    entry: 21375,
    enchant: "Vodouisant's Vigilant Embrace",
    source: "Quest Reward",
    detail: "Stormcaller's Leggings",
  },
  {
    slot: "Feet",
    item: "Stormcaller's Footguards",
    entry: 21373,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Stormcaller's Footguards",
  },
  {
    slot: "Ring 1",
    item: "Pure Elementium Band",
    entry: 19382,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Band of Unanswered Prayers",
    entry: 22939,
    enchant: null,
    source: "Naxxramas",
    detail: "Anub'Rekhan",
  },
  {
    slot: "Trinket 1",
    item: "Eye of the Dead",
    entry: 23047,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Trinket 2",
    item: "Rejuvenating Gem",
    entry: 19395,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Weapon",
    item: "Hammer of the Twisting Nether",
    entry: 23056,
    enchant: "Weapon - Healing Power",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Off Hand",
    item: "Sapphiron's Right Eye",
    entry: 23048,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
];

export const RESTORATION_SHAMAN_BIS: BiSSpecData = {
  classSlug: "shaman",
  specSlug: "restoration",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: RESTORATION_SHAMAN_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: RESTORATION_SHAMAN_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: RESTORATION_SHAMAN_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: RESTORATION_SHAMAN_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: RESTORATION_SHAMAN_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: RESTORATION_SHAMAN_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: RESTORATION_SHAMAN_PHASE_6_GEAR },
  ],
  talentImage: restorationShamanTalents,
  classGuide: {
    introduction: "Restoration Shamans excel at raid-wide healing thanks to the power of Chain Heal. The utility provided by Mana Tide Totem and the rest of their totems is a great addition to a healer and caster groups in raids.",
    rotationNote: "One of the unique things about healing is downranking heals. We mention some specific ranks of certain heals below as a starting point, but finding out which ranks work best will be up to you. The ranks you choose will change based on each boss depending on the situation and length of the encounter, as well your target and how much health they are missing.",
    singleTarget: [
      "Maintain totems that will benefit your group the most.",
      "Use Mana Tide Totem when everyone in your group will benefit the most from it.",
      "Cast Chain Heal. This is your spam heal.",
      "Use Nature's Swiftness with Healing Wave for a big instant heal.",
      "Cast Healing Wave if you need to burst heal someone.",
      "Cast Lesser Healing Wave if you need to heal someone faster than a Chain Heal cast (2.5 sec).",
      "If you need to start conserving mana, you can start downranking and use spells such as Chain Heal R1.",
    ],
    aoe: [
      "Same as single target.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Mageblood Potion (Phase 4)",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup, Sagefish Delight",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Mana Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

export const SHAMAN_BIS_SPECS: BiSSpecData[] = [ELEMENTAL_SHAMAN_BIS, ENHANCEMENT_SHAMAN_BIS, RESTORATION_SHAMAN_BIS];
