import {
  faFlask,
  faBreadSlice,
  faVial,
  faHammer,
  faDice,
} from "@fortawesome/free-solid-svg-icons";
import type { BiSGearEntry, BiSSpecData } from "../types";
import afflictionWarlockTalents from "../assets/BiS Talents/Warlock - Affliction.png";
import destructionWarlockTalents from "../assets/BiS Talents/Warlock - Destruction.png";

const AFFLICTION_WARLOCK_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Diana's Pearl Necklace",
    entry: 22403,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Cannon Master Willey",
  },
  {
    slot: "Shoulder",
    item: "Felcloth Shoulders",
    entry: 14112,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Robe of the Void",
    entry: 14153,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Shadowy Bracers",
    entry: 10461,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward (Tailor Only)",
    detail: "Shadoweaver",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Ban'thok Sash",
    entry: 11662,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Eye of Orgrimmar",
    entry: 12545,
    enchant: null,
    source: "Quest Reward",
    detail: "The Princess Saved?",
  },
  {
    slot: "Ring 2",
    item: "Cyclopean Band",
    entry: 11824,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Trinket 1",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Trinket 2",
    item: "Eye of the Beast",
    entry: 13968,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Witchblade",
    entry: 13964,
    enchant: "Weapon - Spell Power",
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const AFFLICTION_WARLOCK_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Nemesis Skullcap",
    entry: 16929,
    enchant: "Lesser Arcanum of Voracity",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Felcloth Shoulders",
    entry: 14112,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Felheart Bracers",
    entry: 16804,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Nemesis Leggings",
    entry: 16930,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const AFFLICTION_WARLOCK_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Nemesis Skullcap",
    entry: 16929,
    enchant: "Arcanum of Focus",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Felcloth Shoulders",
    entry: 14112,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Amplifying Cloak",
    entry: 18350,
    enchant: "Cloak - Greater Resistance",
    source: "Dire Maul (West)",
    detail: "Magister Kalendris",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Felheart Bracers",
    entry: 16804,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Felcloth Gloves",
    entry: 18407,
    enchant: null,
    source: "Tailoring",
    detail: "BoP Pattern (300)",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Nemesis Leggings",
    entry: 16930,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Tome of Shadow Force",
    entry: 19309,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const AFFLICTION_WARLOCK_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Brood Lord",
    entry: 19378,
    enchant: "Cloak - Greater Resistance",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Ebony Flame Gloves",
    entry: 19407,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Waist",
    item: "Nemesis Belt",
    entry: 16933,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Legs",
    item: "Flarecore Leggings",
    entry: 19165,
    enchant: "Arcanum of Focus",
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Band of Dark Dominion",
    entry: 19434,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Weapon",
    item: "Staff of the Shadow Flame",
    entry: 19356,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const AFFLICTION_WARLOCK_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Hoodoo Hex",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of Consumption",
    entry: 19857,
    enchant: "Cloak - Greater Resistance",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Ebony Flame Gloves",
    entry: 19407,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Waist",
    item: "Nemesis Belt",
    entry: 16933,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Hoodoo Hex",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Band of Dark Dominion",
    entry: 19434,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Trinket 1",
    item: "Zandalarian Hero Charm",
    entry: 19950,
    enchant: null,
    source: "Quest Reward",
    detail: "The Heart of Hakkar",
  },
  {
    slot: "Trinket 2",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Weapon",
    item: "Staff of the Shadow Flame",
    entry: 19356,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ranged",
    item: "Touch of Chaos",
    entry: 19861,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
];

const AFFLICTION_WARLOCK_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Doomcaller's Circlet",
    entry: 21337,
    enchant: "Hoodoo Hex",
    source: "Quest Reward",
    detail: "Doomcaller's Circlet",
  },
  {
    slot: "Neck",
    item: "Amulet of Vek'nilash",
    entry: 21608,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Shoulder",
    item: "Doomcaller's Mantle",
    entry: 21335,
    enchant: "Zandalar Signet of Mojo",
    source: "Quest Reward",
    detail: "Doomcaller's Mantle",
  },
  {
    slot: "Back",
    item: "Cloak of the Devoured",
    entry: 22731,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: "Gloves - Shadow Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Hoodoo Hex",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Ring of Unspoken Names",
    entry: 21417,
    enchant: null,
    source: "Quest Reward",
    detail: "Ring of Unspoken Names",
  },
  {
    slot: "Trinket 1",
    item: "Zandalarian Hero Charm",
    entry: 19950,
    enchant: null,
    source: "Quest Reward",
    detail: "The Heart of Hakkar",
  },
  {
    slot: "Trinket 2",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Weapon",
    item: "Sharpened Silithid Femur",
    entry: 21622,
    enchant: "Weapon - Spell Power",
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Off Hand",
    item: "Royal Scepter of Vek'lor",
    entry: 21597,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Ranged",
    item: "Wand of Qiraji Nobility",
    entry: 21603,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Lord Kri",
  },
];

const AFFLICTION_WARLOCK_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Plagueheart Circlet",
    entry: 22506,
    enchant: "Hoodoo Hex",
    source: "Quest Reward",
    detail: "Plagueheart Circlet",
  },
  {
    slot: "Neck",
    item: "Gem of Trapped Innocents",
    entry: 23057,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Plagueheart Shoulderpads",
    entry: 22507,
    enchant: "Power of the Scourge",
    source: "Quest Reward",
    detail: "Plagueheart Shoulderpads",
  },
  {
    slot: "Back",
    item: "Cloak of the Necropolis",
    entry: 23050,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Chest",
    item: "Plagueheart Robe",
    entry: 22504,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Plagueheart Robe",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: "Gloves - Shadow Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of Polarity",
    entry: 23070,
    enchant: "Hoodoo Hex",
    source: "Naxxramas",
    detail: "Thaddius",
  },
  {
    slot: "Feet",
    item: "Plagueheart Sandals",
    entry: 22508,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Plagueheart Sandals",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Band of the Inevitable",
    entry: 23031,
    enchant: null,
    source: "Naxxramas",
    detail: "Noth the Plaguebringer",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Champion (SP)",
    enchant: null,
    source: "Quest Reward",
    detail: "The Fall of Kel'Thuzad",
  },
  {
    slot: "Weapon",
    item: "Wraith Blade",
    entry: 22807,
    enchant: "Weapon - Spell Power",
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Off Hand",
    item: "Sapphiron's Left Eye",
    entry: 23049,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Ranged",
    item: "Wand of Fates",
    entry: 22820,
    enchant: null,
    source: "Naxxramas",
    detail: "Patchwerk",
  },
];

export const AFFLICTION_WARLOCK_BIS: BiSSpecData = {
  classSlug: "warlock",
  specSlug: "affliction",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: AFFLICTION_WARLOCK_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: AFFLICTION_WARLOCK_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: AFFLICTION_WARLOCK_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: AFFLICTION_WARLOCK_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: AFFLICTION_WARLOCK_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: AFFLICTION_WARLOCK_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: AFFLICTION_WARLOCK_PHASE_6_GEAR },
  ],
  talentImage: afflictionWarlockTalents,
  classGuide: {
    introduction: "Affliction Warlocks will do less damage than Destruction Warlocks, but you do gain access to a fun talent in Nightfall and you will also provide Blood Pact with your Summon Imp.",
    singleTarget: [
      "Maintain your assigned curse between Curse of the Elements, Curse of Shadow, Curse of Recklessness. or Curse of Agony",
      "Maintain Corruption.",
      "Maintain Siphon Life.",
      "Cast Shadow Bolt as a filler.",
      "Cast Searing Pain followed by Shadowburn and Death Coil if the target will die before your next Shadow Bolt cast finishes or while moving. Be sure to cast Life Tap when you need mana, ideally while moving.",
    ],
    aoe: [
      "For 1 additional target:",
      "Maintain your DoTs on both targets.",
      "Cast Shadow Bolt.",
      "For large pulls:",
      "Cast Hellfire.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Flask of Supreme Power",
      alternatives: "Elixir of Shadow Power, Greater Arcane Elixir",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Wizard Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

const DESTRUCTION_WARLOCK_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Crimson Felt Hat",
    entry: 18727,
    enchant: "Lesser Arcanum of Voracity",
    source: "Stratholme (Undead)",
    detail: "Magistrate Barthilas",
  },
  {
    slot: "Neck",
    item: "Diana's Pearl Necklace",
    entry: 22403,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Cannon Master Willey",
  },
  {
    slot: "Shoulder",
    item: "Felcloth Shoulders",
    entry: 14112,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Spritecaster Cape",
    entry: 11623,
    enchant: "Cloak - Greater Resistance",
    source: "Blackrock Depths",
    detail: "Houndmaster Grebmar",
  },
  {
    slot: "Chest",
    item: "Robe of the Void",
    entry: 14153,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Wrist",
    item: "Shadowy Bracers",
    entry: 10461,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward (Tailor Only)",
    detail: "Shadoweaver",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Ban'thok Sash",
    entry: 11662,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Legs",
    item: "Skyshroud Leggings",
    entry: 13170,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackrock Spire (Upper)",
    detail: "Highlord Omokk",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Eye of Orgrimmar",
    entry: 12545,
    enchant: null,
    source: "Quest Reward",
    detail: "The Princess Saved?",
  },
  {
    slot: "Ring 2",
    item: "Cyclopean Band",
    entry: 11824,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Ok'thor the Breaker",
  },
  {
    slot: "Trinket 1",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Trinket 2",
    item: "Eye of the Beast",
    entry: 13968,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Witchblade",
    entry: 13964,
    enchant: "Weapon - Spell Power",
    source: "Scholomance",
    detail: "Darkmaster Gandling",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const DESTRUCTION_WARLOCK_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Nemesis Skullcap",
    entry: 16929,
    enchant: "Lesser Arcanum of Voracity",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Felcloth Shoulders",
    entry: 14112,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Sapphiron Drape",
    entry: 17078,
    enchant: "Cloak - Greater Resistance",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Felheart Bracers",
    entry: 16804,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Hands of Power",
    entry: 13253,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Quartermaster Zigris",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Nemesis Leggings",
    entry: 16930,
    enchant: "Lesser Arcanum of Voracity",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Spirit of Aquementas",
    entry: 11904,
    enchant: null,
    source: "Quest Reward",
    detail: "It's Dangerous to Go Alone",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const DESTRUCTION_WARLOCK_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Nemesis Skullcap",
    entry: 16929,
    enchant: "Arcanum of Focus",
    source: "Onyxia's Lair",
    detail: "Onyxia",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Felcloth Shoulders",
    entry: 14112,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Tailoring",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Back",
    item: "Amplifying Cloak",
    entry: 18350,
    enchant: "Cloak - Greater Resistance",
    source: "Dire Maul (West)",
    detail: "Magister Kalendris",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Felheart Bracers",
    entry: 16804,
    enchant: "Bracer - Greater Intellect",
    source: "Molten Core",
    detail: "Trash Drop",
  },
  {
    slot: "Hands",
    item: "Felcloth Gloves",
    entry: 18407,
    enchant: null,
    source: "Tailoring",
    detail: "BoP Pattern (300)",
  },
  {
    slot: "Waist",
    item: "Mana Igniting Cord",
    entry: 19136,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Legs",
    item: "Nemesis Leggings",
    entry: 16930,
    enchant: "Arcanum of Focus",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Ring 2",
    item: "Ring of Spell Power",
    entry: 19147,
    enchant: null,
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Trinket 1",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 2",
    item: "Briarwood Reed",
    entry: 12930,
    enchant: null,
    source: "Blackrock Spire",
    detail: "Jed Runewatcher",
  },
  {
    slot: "Weapon",
    item: "Azuresong Mageblade",
    entry: 17103,
    enchant: "Weapon - Spell Power",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
  {
    slot: "Off Hand",
    item: "Tome of Shadow Force",
    entry: 19309,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const DESTRUCTION_WARLOCK_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Arcanum of Focus",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of the Brood Lord",
    entry: 19378,
    enchant: "Cloak - Greater Resistance",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Chest",
    item: "Robe of Volatile Power",
    entry: 19145,
    enchant: "Chest - Greater Stats",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Ebony Flame Gloves",
    entry: 19407,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Waist",
    item: "Nemesis Belt",
    entry: 16933,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Legs",
    item: "Flarecore Leggings",
    entry: 19165,
    enchant: "Arcanum of Focus",
    source: "Reputation",
    detail: "Thorium Brotherhood - Revered",
  },
  {
    slot: "Feet",
    item: "Maleki's Footwraps",
    entry: 18735,
    enchant: "Boots - Minor Speed",
    source: "Stratholme (Undead)",
    detail: "Maleki the Pallid",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Band of Dark Dominion",
    entry: 19434,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Talisman of Ephemeral Power",
    entry: 18820,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar, Garr, Baron Geddon, Golemagg",
  },
  {
    slot: "Weapon",
    item: "Staff of the Shadow Flame",
    entry: 19356,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ranged",
    item: "Skul's Ghastly Touch",
    entry: 13396,
    enchant: null,
    source: "Stratholme (Live)",
    detail: "Skul",
  },
];

const DESTRUCTION_WARLOCK_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Mish'undare, Circlet of the Mind Flayer",
    entry: 19375,
    enchant: "Hoodoo Hex",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Neck",
    item: "Choker of the Fire Lord",
    entry: 18814,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Shoulder",
    item: "Mantle of the Blackwing Cabal",
    entry: 19370,
    enchant: "Zandalar Signet of Mojo",
    source: "Blackwing Lair",
    detail: "Razoregore the Untamed",
  },
  {
    slot: "Back",
    item: "Cloak of Consumption",
    entry: 19857,
    enchant: "Cloak - Greater Resistance",
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Bracers of Arcane Accuracy",
    entry: 19374,
    enchant: "Bracer - Greater Intellect",
    source: "Blackwing Lair",
    detail: "Broodlord Lashlayer",
  },
  {
    slot: "Hands",
    item: "Ebony Flame Gloves",
    entry: 19407,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Waist",
    item: "Nemesis Belt",
    entry: 16933,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Hoodoo Hex",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Band of Forced Concentration",
    entry: 19403,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Ring 2",
    item: "Band of Dark Dominion",
    entry: 19434,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Trinket 1",
    item: "Zandalarian Hero Charm",
    entry: 19950,
    enchant: null,
    source: "Quest Reward",
    detail: "The Heart of Hakkar",
  },
  {
    slot: "Trinket 2",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Weapon",
    item: "Staff of the Shadow Flame",
    entry: 19356,
    enchant: "Weapon - Spell Power",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ranged",
    item: "Touch of Chaos",
    entry: 19861,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
];

const DESTRUCTION_WARLOCK_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Doomcaller's Circlet",
    entry: 21337,
    enchant: "Hoodoo Hex",
    source: "Quest Reward",
    detail: "Doomcaller's Circlet",
  },
  {
    slot: "Neck",
    item: "Amulet of Vek'nilash",
    entry: 21608,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'nilash",
  },
  {
    slot: "Shoulder",
    item: "Doomcaller's Mantle",
    entry: 21335,
    enchant: "Zandalar Signet of Mojo",
    source: "Quest Reward",
    detail: "Doomcaller's Mantle",
  },
  {
    slot: "Back",
    item: "Cloak of the Devoured",
    entry: 22731,
    enchant: "Cloak - Greater Resistance",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Chest",
    item: "Bloodvine Vest",
    entry: 19682,
    enchant: "Chest - Greater Stats",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: "Gloves - Shadow Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Bloodvine Leggings",
    entry: 19683,
    enchant: "Hoodoo Hex",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Feet",
    item: "Bloodvine Boots",
    entry: 19684,
    enchant: "Boots - Minor Speed",
    source: "Tailoring",
    detail: "BoP Pattern",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Ring of Unspoken Names",
    entry: 21417,
    enchant: null,
    source: "Quest Reward",
    detail: "Ring of Unspoken Names",
  },
  {
    slot: "Trinket 1",
    item: "Zandalarian Hero Charm",
    entry: 19950,
    enchant: null,
    source: "Quest Reward",
    detail: "The Heart of Hakkar",
  },
  {
    slot: "Trinket 2",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Weapon",
    item: "Sharpened Silithid Femur",
    entry: 21622,
    enchant: "Weapon - Spell Power",
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Off Hand",
    item: "Royal Scepter of Vek'lor",
    entry: 21597,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Ranged",
    item: "Wand of Qiraji Nobility",
    entry: 21603,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Lord Kri",
  },
];

const DESTRUCTION_WARLOCK_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Plagueheart Circlet",
    entry: 22506,
    enchant: "Hoodoo Hex",
    source: "Quest Reward",
    detail: "Plagueheart Circlet",
  },
  {
    slot: "Neck",
    item: "Gem of Trapped Innocents",
    entry: 23057,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Plagueheart Shoulderpads",
    entry: 22507,
    enchant: "Power of the Scourge",
    source: "Quest Reward",
    detail: "Plagueheart Shoulderpads",
  },
  {
    slot: "Back",
    item: "Cloak of the Necropolis",
    entry: 23050,
    enchant: "Cloak - Greater Resistance",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Chest",
    item: "Plagueheart Robe",
    entry: 22504,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Plagueheart Robe",
  },
  {
    slot: "Wrist",
    item: "Rockfury Bracers",
    entry: 21186,
    enchant: "Bracer - Greater Intellect",
    source: "Quest Reward",
    detail: "Stalwart's Battlegear",
  },
  {
    slot: "Hands",
    item: "Dark Storm Gauntlets",
    entry: 21585,
    enchant: "Gloves - Shadow Power",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Eyestalk Waist Cord",
    entry: 22730,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Legs",
    item: "Leggings of Polarity",
    entry: 23070,
    enchant: "Hoodoo Hex",
    source: "Naxxramas",
    detail: "Thaddius",
  },
  {
    slot: "Feet",
    item: "Plagueheart Sandals",
    entry: 22508,
    enchant: "Boots - Minor Speed",
    source: "Quest Reward",
    detail: "Plagueheart Sandals",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Fallen God",
    entry: 21709,
    enchant: null,
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Ring 2",
    item: "Band of the Inevitable",
    entry: 23031,
    enchant: null,
    source: "Naxxramas",
    detail: "Noth the Plaguebringer",
  },
  {
    slot: "Trinket 1",
    item: "Neltharion's Tear",
    entry: 19379,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Champion (SP)",
    enchant: null,
    source: "Quest Reward",
    detail: "The Fall of Kel'Thuzad",
  },
  {
    slot: "Weapon",
    item: "Wraith Blade",
    entry: 22807,
    enchant: "Weapon - Spell Power",
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Off Hand",
    item: "Sapphiron's Left Eye",
    entry: 23049,
    enchant: null,
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Ranged",
    item: "Wand of Fates",
    entry: 22820,
    enchant: null,
    source: "Naxxramas",
    detail: "Patchwerk",
  },
];

export const DESTRUCTION_WARLOCK_BIS: BiSSpecData = {
  classSlug: "warlock",
  specSlug: "destruction",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: DESTRUCTION_WARLOCK_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: DESTRUCTION_WARLOCK_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: DESTRUCTION_WARLOCK_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: DESTRUCTION_WARLOCK_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: DESTRUCTION_WARLOCK_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: DESTRUCTION_WARLOCK_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: DESTRUCTION_WARLOCK_PHASE_6_GEAR },
  ],
  talentImage: destructionWarlockTalents,
  classGuide: {
    introduction: "This is the go-to spec for Warlocks for all of Classic. Their rotation is extremely simple and they will see some huge Shadow Bolt crits in the process.",
    singleTarget: [
      "Use Demonic Sacrifice on your Succubus.",
      "Maintain your assigned curse between Curse of the Elements, Curse of Shadow, Curse of Recklessness. or Curse of Agony",
      "Maintain Corruption.",
      "Cast Shadow Bolt.",
      "Cast Searing Pain followed if the target will die before your next Shadow Bolt cast finishes.",
      "Cast Shadowburn and Death Coil on the move or if the target is about to die.",
      "Cast Life Tap when you need mana, ideally while moving.",
    ],
    aoe: [
      "For 1 additional target:",
      "Maintain your curse and Corruption on both targets.",
      "Cast Shadow Bolt.",
      "For large pulls:",
      "Cast Hellfire.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Flask of Supreme Power",
      alternatives: "Elixir of Shadow Power, Greater Arcane Elixir",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Nightfin Soup",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Major Mana Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Brilliant Wizard Oil (Phase 4)",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Dark Rune or Demonic Rune, Cerebral Cortex Compound",
    },
  ],
};

export const WARLOCK_BIS_SPECS: BiSSpecData[] = [AFFLICTION_WARLOCK_BIS, DESTRUCTION_WARLOCK_BIS];
