import {
  faFlask,
  faBreadSlice,
  faVial,
  faHammer,
  faDice,
} from "@fortawesome/free-solid-svg-icons";
import type { BiSGearEntry, BiSSpecData } from "../types";
import furyWarriorTalents from "../assets/BiS Talents/Warrior - Fury.png";
import protectionWarriorTalents from "../assets/BiS Talents/Warrior - Protection.png";

const FURY_WARRIOR_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lionheart Helm",
    entry: 12640,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Vambraces of the Sadist",
    entry: 13400,
    enchant: "Bracer - Superior Strength",
    source: "Stratholme (Live)",
    detail: "Timmy the Cruel",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Strength",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Omokk's Girth Restrainer",
    entry: 13959,
    enchant: null,
    source: "Quest Reward",
    detail: "Warlord's Command (H)",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Battlechaser's Greaves",
    entry: 12555,
    enchant: "Boots - Greater Agility",
    source: "Auction House",
    detail: "BoE World Drop",
  },
  {
    slot: "Ring 1",
    item: "Blackstone Ring",
    entry: 17713,
    enchant: null,
    source: "Maraudon",
    detail: "Princess Theradras",
  },
  {
    slot: "Ring 2",
    item: "Painweaver Band",
    entry: 13098,
    enchant: null,
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath",
  },
  {
    slot: "Trinket 1",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Dal'Rend's Sacred Charge",
    entry: 12940,
    enchant: "Weapon - Crusader",
    source: "Blackrock Spire (Upper)",
    detail: "Warchief Rend Blackhand",
  },
  {
    slot: "Off Hand",
    item: "Dal'Rend's Tribal Guardian",
    entry: 12939,
    enchant: "Weapon - Crusader",
    source: "Blackrock Spire (Upper)",
    detail: "Warchief Rend Blackhand",
  },
  {
    slot: "Ranged",
    item: "Riphook",
    entry: 12653,
    enchant: null,
    source: "Blackrock Spire (Lower)",
    detail: "Shadow Hunter Vosh'gajin",
  },
];

const FURY_WARRIOR_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lionheart Helm",
    entry: 12640,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Devilsaur Gauntlets",
    entry: 15063,
    enchant: "Gloves - Greater Strength",
    source: "Leatherworking",
    detail: "BoE Pattern (290)",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Battlechaser's Greaves",
    entry: 12555,
    enchant: "Boots - Greater Agility",
    source: "Auction House",
    detail: "BoE World Drop",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Painweaver Band",
    entry: 13098,
    enchant: null,
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath",
  },
  {
    slot: "Trinket 1",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Brutality Blade",
    entry: 18832,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Core Hound Tooth",
    entry: 18805,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ranged",
    item: "Striker's Mark",
    entry: 17069,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar",
  },
];

const FURY_WARRIOR_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lionheart Helm",
    entry: 12640,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Truestrike Shoulders",
    entry: 12927,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Pyroguard Emberseer",
  },
  {
    slot: "Back",
    item: "Cape of the Black Baron",
    entry: 13340,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Flameguard Gauntlets",
    entry: 19143,
    enchant: "Gloves - Greater Strength",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Legs",
    item: "Devilsaur Leggings",
    entry: 15062,
    enchant: "Lesser Arcanum of Voracity",
    source: "Leatherworking",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Feet",
    item: "Battlechaser's Greaves",
    entry: 12555,
    enchant: "Boots - Greater Agility",
    source: "Auction House",
    detail: "BoE World Drop",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Don Julio's Band",
    entry: 19325,
    enchant: null,
    source: "Reputation",
    detail: "Frostwolf Clan, Stormpike Guard - Exalted",
  },
  {
    slot: "Trinket 1",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Brutality Blade",
    entry: 18832,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Off Hand",
    item: "Core Hound Tooth",
    entry: 18805,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Ranged",
    item: "Striker's Mark",
    entry: 17069,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar",
  },
];

const FURY_WARRIOR_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lionheart Helm",
    entry: 12640,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Drake Talon Pauldrons",
    entry: 19394,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Back",
    item: "Cloak of Draconic Might",
    entry: 19436,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Flameguard Gauntlets",
    entry: 19143,
    enchant: "Gloves - Greater Strength",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Legs",
    item: "Legguards of the Fallen Crusader",
    entry: 19402,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Feet",
    item: "Chromatic Boots",
    entry: 19387,
    enchant: "Boots - Greater Agility",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ring 1",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Diamond Flask",
    entry: 20130,
    enchant: null,
    source: "Quest Reward",
    detail: "Voodoo Feathers",
  },
  {
    slot: "Weapon",
    item: "Crul'shorukh, Edge of Chaos",
    entry: 19363,
    enchant: "Weapon - Crusader",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Chromatically Tempered Sword",
    entry: 19352,
    enchant: "Weapon - Crusader",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ranged",
    item: "Striker's Mark",
    entry: 17069,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar",
  },
];

const FURY_WARRIOR_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lionheart Helm",
    entry: 12640,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "The Eye of Hakkar",
    entry: 19856,
    enchant: null,
    source: "Zul'Gurub",
    detail: "Hakkar",
  },
  {
    slot: "Shoulder",
    item: "Drake Talon Pauldrons",
    entry: 19394,
    enchant: "Zandalar Signet of Might",
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Back",
    item: "Cloak of Draconic Might",
    entry: 19436,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Trash Drop",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Stability",
    entry: 19146,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Gehennas, Sulfuron, Lucifron, Shazzrah",
  },
  {
    slot: "Hands",
    item: "Flameguard Gauntlets",
    entry: 19143,
    enchant: "Gloves - Greater Strength",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Legs",
    item: "Legguards of the Fallen Crusader",
    entry: 19402,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Feet",
    item: "Chromatic Boots",
    entry: 19387,
    enchant: "Boots - Greater Agility",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ring 1",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Diamond Flask",
    entry: 20130,
    enchant: null,
    source: "Quest Reward",
    detail: "Voodoo Feathers",
  },
  {
    slot: "Weapon",
    item: "Crul'shorukh, Edge of Chaos",
    entry: 19363,
    enchant: "Weapon - Crusader",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Chromatically Tempered Sword",
    entry: 19352,
    enchant: "Weapon - Crusader",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ranged",
    item: "Striker's Mark",
    entry: 17069,
    enchant: null,
    source: "Molten Core",
    detail: "Magmadar",
  },
];

const FURY_WARRIOR_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lionheart Helm",
    entry: 12640,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "Barbed Choker",
    entry: 21664,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Shoulder",
    item: "Conqueror's Spaulders",
    entry: 21330,
    enchant: "Zandalar Signet of Might",
    source: "Quest Reward",
    detail: "Conqueror's Spaulders",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Breastplate of Annihilation",
    entry: 21814,
    enchant: "Chest - Greater Stats",
    source: "Ahn'Qiraj",
    detail: "The Prophet Skeram",
  },
  {
    slot: "Wrist",
    item: "Qiraji Execution Bracers",
    entry: 21602,
    enchant: "Bracer - Superior Strength",
    source: "Ahn'Qiraj",
    detail: "Emperor Vek'lor",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Annihilation",
    entry: 21581,
    enchant: "Gloves - Superior Agility",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Legs",
    item: "Conqueror's Legguards",
    entry: 21332,
    enchant: "Lesser Arcanum of Voracity",
    source: "Quest Reward",
    detail: "Conqueror's Legguards",
  },
  {
    slot: "Feet",
    item: "Chromatic Boots",
    entry: 19387,
    enchant: "Boots - Greater Agility",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ring 1",
    item: "Ring of the Qiraji Fury",
    entry: 21677,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Drake Fang Talisman",
    entry: 19406,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Ebonroc",
  },
  {
    slot: "Trinket 2",
    item: "Diamond Flask",
    entry: 20130,
    enchant: null,
    source: "Quest Reward",
    detail: "Voodoo Feathers",
  },
  {
    slot: "Weapon",
    item: "Crul'shorukh, Edge of Chaos",
    entry: 19363,
    enchant: "Weapon - Crusader",
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Off Hand",
    item: "Death's Sting",
    entry: 21126,
    enchant: "Weapon - Crusader",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Ranged",
    item: "Larvae of the Great Worm",
    entry: 23557,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Ouro",
  },
];

const FURY_WARRIOR_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lionheart Helm",
    entry: 12640,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "Stormrage's Talisman of Seething",
    entry: 23053,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Mantle of Wicked Revenge",
    entry: 21665,
    enchant: "Might of the Scourge",
    source: "Ahn'Qiraj",
    detail: "Fankriss the Unyielding",
  },
  {
    slot: "Back",
    item: "Shroud of Dominion",
    entry: 23045,
    enchant: "Cloak - Lesser Agility",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Chest",
    item: "Ghoul Skin Tunic",
    entry: 23226,
    enchant: "Chest - Greater Stats",
    source: "Naxxramas",
    detail: "Trash Drop",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Vengeance",
    entry: 22936,
    enchant: "Bracer - Superior Strength",
    source: "Naxxramas",
    detail: "Anub'Rekhan",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Annihilation",
    entry: 21581,
    enchant: "Gloves - Superior Agility",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Girdle of the Mentor",
    entry: 23219,
    enchant: null,
    source: "Naxxramas",
    detail: "Instructor Razuvious",
  },
  {
    slot: "Legs",
    item: "Legplates of Carnage",
    entry: 23068,
    enchant: "Lesser Arcanum of Voracity",
    source: "Naxxramas",
    detail: "Heigan the Unclean",
  },
  {
    slot: "Feet",
    item: "Chromatic Boots",
    entry: 19387,
    enchant: "Boots - Greater Agility",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ring 1",
    item: "Band of Unnatural Forces",
    entry: 23038,
    enchant: null,
    source: "Naxxramas",
    detail: "Loatheb",
  },
  {
    slot: "Ring 2",
    item: "Ring of the Qiraji Fury",
    entry: 21677,
    enchant: null,
    source: "Ahn'Qiraj",
    detail: "Viscidus",
  },
  {
    slot: "Trinket 1",
    item: "Kiss of the Spider",
    entry: 22954,
    enchant: null,
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Champion-v2",
    enchant: null,
    source: "Quest Reward",
    detail: "The Fall of Kel'Thuzad",
  },
  {
    slot: "Weapon",
    item: "Gressil, Dawn of Ruin",
    entry: 23054,
    enchant: "Weapon - Crusader",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Off Hand",
    item: "The Hungering Cold",
    entry: 23577,
    enchant: "Weapon - Crusader",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Ranged",
    item: "Nerubian Slavemaker",
    entry: 22812,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
];

export const FURY_WARRIOR_BIS: BiSSpecData = {
  classSlug: "warrior",
  specSlug: "fury",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: FURY_WARRIOR_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: FURY_WARRIOR_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: FURY_WARRIOR_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: FURY_WARRIOR_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: FURY_WARRIOR_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: FURY_WARRIOR_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: FURY_WARRIOR_PHASE_6_GEAR },
  ],
  talentImage: furyWarriorTalents,
  classGuide: {
    introduction: "Fury is the go-to spec for Warriors during all of Classic. There are two different variations the spec based on if you are using a 2 handed weapon or dual wielding, but they both play virtually the same.",
    singleTarget: [
      "Maintain Battle Shout.",
      "Maintain Demoralizing Shout unless there is a Warrior with Improved Demoralizing Shout.",
      "Use Bloodrage.",
      "Use Recklessness.",
      "Use Death Wish. Make sure it's available for Execute phase.",
      "Use Sunder Armor if not fully stacked or about to fall off.",
      "Use Execute if enemy is below 20% health.",
      "Use Bloodthirst.",
      "Use Slam after an auto attack if you you are playing the 2 handed Slam spec .",
      "Use Whirlwind.",
      "Use Heroic Strike and Use Hamstring to dump excess rage.",
    ],
    aoe: [
      "For 1 additional target:",
      "Perform single target rotation, but replace Heroic Strike with Cleave.",
      "For large pulls:",
      "Perform single target rotation, but replace Heroic Strike with Cleave and prioritize Whirlwind over Bloodthirst.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Elixir of the Mongoose",
      alternatives: "Elixir of Greater Agility",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Blessed Sunfruit, Smoked Desert Dumplings",
      note: "Only available from Phase 5 onward.",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Mighty Rage Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Windfury Weapon, Elemental Sharpening Stone",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Juju Might, Juju Power, Ground Scorpok Assay, R.O.I.D.S.",
    },
  ],
};

const PROTECTION_WARRIOR_PRE_RAID_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lionheart Helm",
    entry: 12640,
    enchant: "Lesser Arcanum of Voracity",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "Mark of Fordring",
    entry: 15411,
    enchant: null,
    source: "Quest Reward",
    detail: "In Dreams",
  },
  {
    slot: "Shoulder",
    item: "Spaulders of Valor",
    entry: 16733,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackrock Spire (Upper)",
    detail: "Warchief Rend Blackhand",
  },
  {
    slot: "Back",
    item: "Stoneskin Gargoyle Cape",
    entry: 13397,
    enchant: "Cloak - Lesser Agility",
    source: "Stratholme (Undead)",
    detail: "Stonespine",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Battleborn Armbraces",
    entry: 12936,
    enchant: "Bracer - Superior Strength",
    source: "Blackrock Spire (Upper)",
    detail: "Warchief Rend Blackhand",
  },
  {
    slot: "Hands",
    item: "Voone's Vice Grips",
    entry: 13963,
    enchant: "Gloves - Greater Strength",
    source: "Quest Reward",
    detail: "Warlord's Command (H)",
  },
  {
    slot: "Waist",
    item: "Brigam Girdle",
    entry: 13142,
    enchant: null,
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath",
  },
  {
    slot: "Legs",
    item: "Legplates of Valor",
    entry: 16732,
    enchant: "Lesser Arcanum of Constitution",
    source: "Stratholme (Undead)",
    detail: "Baron Rivendare",
  },
  {
    slot: "Feet",
    item: "Bloodmail Boots",
    entry: 14616,
    enchant: "Boots - Minor Speed",
    source: "Scholomance",
    detail: "Multiple Bosses",
  },
  {
    slot: "Ring 1",
    item: "Painweaver Band",
    entry: 13098,
    enchant: null,
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath",
  },
  {
    slot: "Ring 2",
    item: "Blackstone Ring",
    entry: 17713,
    enchant: null,
    source: "Maraudon",
    detail: "Princess Theradras",
  },
  {
    slot: "Trinket 1",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Dal'Rend's Sacred Charge",
    entry: 12940,
    enchant: "Weapon - Crusader",
    source: "Blackrock Spire (Upper)",
    detail: "Warchief Rend Blackhand",
  },
  {
    slot: "Off Hand",
    item: "Draconian Deflector",
    entry: 12602,
    enchant: "Shield - Greater Stamina",
    source: "Blackrock Spire (Upper)",
    detail: "General Drakkisath",
  },
  {
    slot: "Ranged",
    item: "Blackcrow",
    entry: 12651,
    enchant: "Sniper Scope",
    source: "Blackrock Spire (Lower)",
    detail: "Shadow Hunter Vosh'gajin",
  },
];

const PROTECTION_WARRIOR_PHASE_1_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lionheart Helm",
    entry: 12640,
    enchant: "Lesser Arcanum of Constitution",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Pauldrons of Might",
    entry: 16868,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Sulfuron Harbinger",
  },
  {
    slot: "Back",
    item: "Cloak of the Shrouded Mists",
    entry: 17102,
    enchant: "Cloak - Lesser Agility",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of True Flight",
    entry: 18812,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Hands",
    item: "Aged Core Leather Gloves",
    entry: 18823,
    enchant: "Gloves - Greater Strength",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Legs",
    item: "Legplates of Wrath",
    entry: 16962,
    enchant: "Lesser Arcanum of Constitution",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Sabatons of Might",
    entry: 16862,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Gehennas",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Trinket 1",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Perdition's Blade",
    entry: 18816,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Off Hand",
    item: "Drillborer Disk",
    entry: 17066,
    enchant: "Shield - Greater Stamina",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Ranged",
    item: "Blastershot Launcher",
    entry: 17072,
    enchant: "Sniper Scope",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
];

const PROTECTION_WARRIOR_PHASE_2_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Lionheart Helm",
    entry: 12640,
    enchant: "Lesser Arcanum of Constitution",
    source: "Blacksmithing",
    detail: "BoE Pattern (300)",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Pauldrons of Might",
    entry: 16868,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Molten Core",
    detail: "Sulfuron Harbinger",
  },
  {
    slot: "Back",
    item: "Cloak of the Shrouded Mists",
    entry: 17102,
    enchant: "Cloak - Lesser Agility",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of True Flight",
    entry: 18812,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Hands",
    item: "Aged Core Leather Gloves",
    entry: 18823,
    enchant: "Gloves - Greater Strength",
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Legs",
    item: "Legplates of Wrath",
    entry: 16962,
    enchant: "Lesser Arcanum of Constitution",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Feet",
    item: "Sabatons of Might",
    entry: 16862,
    enchant: "Boots - Minor Speed",
    source: "Molten Core",
    detail: "Gehennas",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Band of Accuria",
    entry: 17063,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Trinket 1",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Trinket 2",
    item: "Blackhand's Breadth",
    entry: 13965,
    enchant: null,
    source: "Quest Reward",
    detail: "For The Horde! (H)",
  },
  {
    slot: "Weapon",
    item: "Perdition's Blade",
    entry: 18816,
    enchant: "Weapon - Crusader",
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Off Hand",
    item: "Drillborer Disk",
    entry: 17066,
    enchant: "Shield - Greater Stamina",
    source: "Molten Core",
    detail: "Garr",
  },
  {
    slot: "Ranged",
    item: "Blastershot Launcher",
    entry: 17072,
    enchant: "Sniper Scope",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
];

const PROTECTION_WARRIOR_PHASE_3_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Helm of Endless Rage",
    entry: 19372,
    enchant: "Lesser Arcanum of Constitution",
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Drake Talon Pauldrons",
    entry: 19394,
    enchant: "Chromatic Mantle of the Dawn",
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Back",
    item: "Cloak of Firemaw",
    entry: 19398,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Wristguards of True Flight",
    entry: 18812,
    enchant: "Bracer - Superior Strength",
    source: "Molten Core",
    detail: "Majordomo Executus",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Might",
    entry: 16863,
    enchant: "Gloves - Greater Strength",
    source: "Molten Core",
    detail: "Lucifron",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Legs",
    item: "Legguards of the Fallen Crusader",
    entry: 19402,
    enchant: "Lesser Arcanum of Constitution",
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Feet",
    item: "Chromatic Boots",
    entry: 19387,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 1",
    item: "Diamond Flask",
    entry: 20130,
    enchant: null,
    source: "Quest Reward",
    detail: "Voodoo Feathers",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Thunderfury, Blessed Blade of the Windseeker",
    entry: 19019,
    enchant: "Weapon - Crusader",
    source: "Quest Reward",
    detail: "Rise, Thunderfury!",
  },
  {
    slot: "Off Hand",
    item: "Elementium Reinforced Bulwark",
    entry: 19349,
    enchant: "Shield - Greater Stamina",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ranged",
    item: "Blastershot Launcher",
    entry: 17072,
    enchant: "Sniper Scope",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
];

const PROTECTION_WARRIOR_PHASE_4_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Helm of Endless Rage",
    entry: 19372,
    enchant: "Lesser Arcanum of Constitution",
    source: "Blackwing Lair",
    detail: "Vaelastrasz the Corrupt",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Drake Talon Pauldrons",
    entry: 19394,
    enchant: "Zandalar Signet of Might",
    source: "Blackwing Lair",
    detail: "Firemaw, Ebonroc, & Flamegor",
  },
  {
    slot: "Back",
    item: "Cloak of Firemaw",
    entry: 19398,
    enchant: "Cloak - Lesser Agility",
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Chest",
    item: "Savage Gladiator Chain",
    entry: 11726,
    enchant: "Chest - Greater Stats",
    source: "Blackrock Depths",
    detail: "Gorosh the Dervish",
  },
  {
    slot: "Wrist",
    item: "Zandalar Vindicator's Armguards",
    entry: 19824,
    enchant: "Bracer - Superior Strength",
    source: "Quest Reward",
    detail: "Paragons of Power: The Vindicator's Armguards",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Might",
    entry: 16863,
    enchant: "Gloves - Greater Strength",
    source: "Molten Core",
    detail: "Lucifron",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Legs",
    item: "Legguards of the Fallen Crusader",
    entry: 19402,
    enchant: "Lesser Arcanum of Constitution",
    source: "Blackwing Lair",
    detail: "Firemaw",
  },
  {
    slot: "Feet",
    item: "Chromatic Boots",
    entry: 19387,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ring 1",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Ring 2",
    item: "Master Dragonslayer's Ring",
    entry: 19384,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Nefarian",
  },
  {
    slot: "Trinket 1",
    item: "Diamond Flask",
    entry: 20130,
    enchant: null,
    source: "Quest Reward",
    detail: "Voodoo Feathers",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Thunderfury, Blessed Blade of the Windseeker",
    entry: 19019,
    enchant: "Weapon - Crusader",
    source: "Quest Reward",
    detail: "Rise, Thunderfury!",
  },
  {
    slot: "Off Hand",
    item: "Elementium Reinforced Bulwark",
    entry: 19349,
    enchant: "Shield - Greater Stamina",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ranged",
    item: "Blastershot Launcher",
    entry: 17072,
    enchant: "Sniper Scope",
    source: "Molten Core",
    detail: "Golemagg the Incinerator",
  },
];

const PROTECTION_WARRIOR_PHASE_5_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Conqueror's Crown",
    entry: 21329,
    enchant: "Lesser Arcanum of Constitution",
    source: "Quest Reward",
    detail: "Conqueror's Crown",
  },
  {
    slot: "Neck",
    item: "Onyxia Tooth Pendant",
    entry: 18404,
    enchant: null,
    source: "Quest Reward",
    detail: "For All To See",
  },
  {
    slot: "Shoulder",
    item: "Conqueror's Spaulders",
    entry: 21330,
    enchant: "Zandalar Signet of Might",
    source: "Quest Reward",
    detail: "Conqueror's Spaulders",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Conqueror's Breastplate",
    entry: 21331,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Conqueror's Breastplate",
  },
  {
    slot: "Wrist",
    item: "Hive Defiler Wristguards",
    entry: 21618,
    enchant: "Bracer - Superior Strength",
    source: "Ahn'Qiraj",
    detail: "Princess Huhuran",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Annihilation",
    entry: 21581,
    enchant: "Gloves - Greater Strength",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Onslaught Girdle",
    entry: 19137,
    enchant: null,
    source: "Molten Core",
    detail: "Ragnaros",
  },
  {
    slot: "Legs",
    item: "Conqueror's Legguards",
    entry: 21332,
    enchant: "Lesser Arcanum of Constitution",
    source: "Quest Reward",
    detail: "Conqueror's Legguards",
  },
  {
    slot: "Feet",
    item: "Chromatic Boots",
    entry: 19387,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ring 1",
    item: "Circle of Applied Force",
    entry: 19432,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Flamegor",
  },
  {
    slot: "Ring 2",
    item: "Quick Strike Ring",
    entry: 18821,
    enchant: null,
    source: "Molten Core",
    detail: "Garr, Magmadar, Baron Geddon, Golemagg",
  },
  {
    slot: "Trinket 1",
    item: "Diamond Flask",
    entry: 20130,
    enchant: null,
    source: "Quest Reward",
    detail: "Voodoo Feathers",
  },
  {
    slot: "Trinket 2",
    item: "Hand of Justice",
    entry: 11815,
    enchant: null,
    source: "Blackrock Depths",
    detail: "Emperor Dagran Thaurissan",
  },
  {
    slot: "Weapon",
    item: "Thunderfury, Blessed Blade of the Windseeker",
    entry: 19019,
    enchant: "Weapon - Crusader",
    source: "Quest Reward",
    detail: "Rise, Thunderfury!",
  },
  {
    slot: "Off Hand",
    item: "Elementium Reinforced Bulwark",
    entry: 19349,
    enchant: "Shield - Greater Stamina",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ranged",
    item: "Crossbow of Imminent Doom",
    entry: 21459,
    enchant: "Sniper Scope",
    source: "Ruins of Ahn'Qiraj",
    detail: "Ossirian the Unscarred",
  },
];

const PROTECTION_WARRIOR_PHASE_6_GEAR: BiSGearEntry[] = [
  {
    slot: "Head",
    item: "Conqueror's Crown",
    entry: 21329,
    enchant: "Lesser Arcanum of Constitution",
    source: "Quest Reward",
    detail: "Conqueror's Crown",
  },
  {
    slot: "Neck",
    item: "Stormrage's Talisman of Seething",
    entry: 23053,
    enchant: null,
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
  {
    slot: "Shoulder",
    item: "Conqueror's Spaulders",
    entry: 21330,
    enchant: "Might of the Scourge",
    source: "Quest Reward",
    detail: "Conqueror's Spaulders",
  },
  {
    slot: "Back",
    item: "Cloak of the Fallen God",
    entry: 21710,
    enchant: "Cloak - Lesser Agility",
    source: "Quest Reward",
    detail: "The Savior of Kalimdor",
  },
  {
    slot: "Chest",
    item: "Conqueror's Breastplate",
    entry: 21331,
    enchant: "Chest - Greater Stats",
    source: "Quest Reward",
    detail: "Conqueror's Breastplate",
  },
  {
    slot: "Wrist",
    item: "Wristguards of Vengeance",
    entry: 22936,
    enchant: "Bracer - Superior Strength",
    source: "Naxxramas",
    detail: "Anub'Rekhan",
  },
  {
    slot: "Hands",
    item: "Gauntlets of Annihilation",
    entry: 21581,
    enchant: "Gloves - Greater Strength",
    source: "Ahn'Qiraj",
    detail: "C'Thun",
  },
  {
    slot: "Waist",
    item: "Girdle of the Mentor",
    entry: 23219,
    enchant: null,
    source: "Naxxramas",
    detail: "Instructor Razuvious",
  },
  {
    slot: "Legs",
    item: "Conqueror's Legguards",
    entry: 21332,
    enchant: "Lesser Arcanum of Constitution",
    source: "Quest Reward",
    detail: "Conqueror's Legguards",
  },
  {
    slot: "Feet",
    item: "Chromatic Boots",
    entry: 19387,
    enchant: "Boots - Minor Speed",
    source: "Blackwing Lair",
    detail: "Chromaggus",
  },
  {
    slot: "Ring 1",
    item: "Band of Unnatural Forces",
    entry: 23038,
    enchant: null,
    source: "Naxxramas",
    detail: "Loatheb",
  },
  {
    slot: "Ring 2",
    item: "Circle of Applied Force",
    entry: 19432,
    enchant: null,
    source: "Blackwing Lair",
    detail: "Flamegor",
  },
  {
    slot: "Trinket 1",
    item: "Kiss of the Spider",
    entry: 22954,
    enchant: null,
    source: "Naxxramas",
    detail: "Maexxna",
  },
  {
    slot: "Trinket 2",
    item: "Mark of the Champion-v2",
    enchant: null,
    source: "Quest Reward",
    detail: "The Fall of Kel'Thuzad",
  },
  {
    slot: "Weapon",
    item: "Thunderfury, Blessed Blade of the Windseeker",
    entry: 19019,
    enchant: "Weapon - Crusader",
    source: "Quest Reward",
    detail: "Rise, Thunderfury!",
  },
  {
    slot: "Off Hand",
    item: "The Face of Death",
    entry: 23043,
    enchant: "Shield - Greater Stamina",
    source: "Naxxramas",
    detail: "Sapphiron",
  },
  {
    slot: "Ranged",
    item: "Nerubian Slavemaker",
    entry: 22812,
    enchant: "Sniper Scope",
    source: "Naxxramas",
    detail: "Kel'Thuzad",
  },
];

export const PROTECTION_WARRIOR_BIS: BiSSpecData = {
  classSlug: "warrior",
  specSlug: "protection",
  phases: [
    { id: "pre-raid", label: "Pre-Raid", zone: "Questing / Dungeons / Professions", gear: PROTECTION_WARRIOR_PRE_RAID_GEAR },
    { id: "phase-1", label: "Phase 1", zone: "Molten Core", gear: PROTECTION_WARRIOR_PHASE_1_GEAR },
    { id: "phase-2", label: "Phase 2", zone: "Onyxia / Dire Maul", gear: PROTECTION_WARRIOR_PHASE_2_GEAR },
    { id: "phase-3", label: "Phase 3", zone: "Blackwing Lair", gear: PROTECTION_WARRIOR_PHASE_3_GEAR },
    { id: "phase-4", label: "Phase 4", zone: "Zul'Gurub", gear: PROTECTION_WARRIOR_PHASE_4_GEAR },
    { id: "phase-5", label: "Phase 5", zone: "Ahn'Qiraj", gear: PROTECTION_WARRIOR_PHASE_5_GEAR },
    { id: "phase-6", label: "Phase 6", zone: "Naxxramas", gear: PROTECTION_WARRIOR_PHASE_6_GEAR },
  ],
  talentImage: protectionWarriorTalents,
  classGuide: {
    introduction: "Protection Warriors are the best tank for all of Classic. They are extremely versatile with their ability to gear and spec for threat or mitigation.",
    singleTarget: [
      "Maintain Battle Shout.",
      "Maintain Demoralizing Shout if assigned.",
      "Use Bloodrage if you need rage and can afford the health loss.",
      "Use Shield Block. If you are safe and need rage you can hold off on using this.",
      "Use Death Wish if Deep Fury build.",
      "Use Recklessness at your own discretion.",
      "Use Sunder Armor if not fully stacked or about to fall off.",
      "Use Execute if enemy is below 20% health.",
      "Use Shield Slam or Bloodthirst depending on spec.",
      "Use Revenge.",
      "Use Sunder Armor while your other abilities are on cooldown.",
      "Use Heroic Strike to dump extra rage.",
      "Use Shield Wall, Last Stand, and Retaliation when appropriate.",
    ],
    aoe: [
      "Maintain Demoralizing Shout if assigned.",
      "Use Shield Block. If you are safe and need rage you can hold off on using this.",
      "Spam Demoralizing Shout. Use Cleave to dump extra rage.",
    ],
  },
  consumables: [
    {
      category: "Flasks & Elixirs",
      slug: "flasks",
      icon: faFlask,
      best: "Elixir of the Mongoose, Elixir of Superior Defense",
      alternatives: "Flask of the Titans, Elixir of Greater Agility",
    },
    {
      category: "Food",
      slug: "food",
      icon: faBreadSlice,
      best: "Blessed Sunfruit, Smoked Desert Dumplings",
      note: "Only available from Phase 5 onward.",
    },
    {
      category: "Potions",
      slug: "potions",
      icon: faVial,
      best: "Mighty Rage Potion",
    },
    {
      category: "Weapon Buffs",
      slug: "weaponBuffs",
      icon: faHammer,
      best: "Windfury Weapon, Dense Sharpening Stone",
    },
    {
      category: "Miscellaneous",
      slug: "misc",
      icon: faDice,
      best: "Juju Might, Juju Power, Ground Scorpok Assay, R.O.I.D.S., Lung Juice Cocktail",
    },
  ],
};

export const WARRIOR_BIS_SPECS: BiSSpecData[] = [FURY_WARRIOR_BIS, PROTECTION_WARRIOR_BIS];
